### Healthcare payment analysis

* **Goal: Analysis of gender based payment disparity in pharmaceutical industry**

*  **Scope:  Research data preprocessing: Cleanup, standardization, EDA for identifying important features, feature engineering- Gender columns for recipients and investigators.** 

* Date: 21 oct 2024

In [1]:
# Importing packages
import pandas as pd
import numpy as np
import sys

In [ ]:
# Data file import
df1=pd.read_csv('OP_DTL_RSRCH_PGYR2023_P06282024_06122024.csv', low_memory=False)

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Columns: 252 entries, Change_Type to Context_of_Research
dtypes: float64(94), int64(3), object(155)
memory usage: 1.9+ GB

In [4]:
df1_columns=df1.columns

In [5]:
l1=list(enumerate(df1_columns))
for i,j in l1:
    print(j)

Change_Type
Covered_Recipient_Type
Noncovered_Recipient_Entity_Name
Teaching_Hospital_CCN
Teaching_Hospital_ID
Teaching_Hospital_Name
Covered_Recipient_Profile_ID
Covered_Recipient_NPI
Covered_Recipient_First_Name
Covered_Recipient_Middle_Name
Covered_Recipient_Last_Name
Covered_Recipient_Name_Suffix
Recipient_Primary_Business_Street_Address_Line1
Recipient_Primary_Business_Street_Address_Line2
Recipient_City
Recipient_State
Recipient_Zip_Code
Recipient_Country
Recipient_Province
Recipient_Postal_Code
Covered_Recipient_Primary_Type_1
Covered_Recipient_Primary_Type_2
Covered_Recipient_Primary_Type_3
Covered_Recipient_Primary_Type_4
Covered_Recipient_Primary_Type_5
Covered_Recipient_Primary_Type_6
Covered_Recipient_Specialty_1
Covered_Recipient_Specialty_2
Covered_Recipient_Specialty_3
Covered_Recipient_Specialty_4
Covered_Recipient_Specialty_5
Covered_Recipient_Specialty_6
Covered_Recipient_License_State_code1
Covered_Recipient_License_State_code2
Covered_Recipient_License_State_code3
Covered_Recipient_License_State_code4
Covered_Recipient_License_State_code5
Principal_Investigator_1_Covered_Recipient_Type
Principal_Investigator_1_Profile_ID
Principal_Investigator_1_NPI
Principal_Investigator_1_First_Name
Principal_Investigator_1_Middle_Name
Principal_Investigator_1_Last_Name
Principal_Investigator_1_Name_Suffix
Principal_Investigator_1_Business_Street_Address_Line1
Principal_Investigator_1_Business_Street_Address_Line2
Principal_Investigator_1_City
Principal_Investigator_1_State
Principal_Investigator_1_Zip_Code
Principal_Investigator_1_Country
Principal_Investigator_1_Province
Principal_Investigator_1_Postal_Code
Principal_Investigator_1_Primary_Type_1
Principal_Investigator_1_Primary_Type_2
Principal_Investigator_1_Primary_Type_3
Principal_Investigator_1_Primary_Type_4
Principal_Investigator_1_Primary_Type_5
Principal_Investigator_1_Primary_Type_6
Principal_Investigator_1_Specialty_1
Principal_Investigator_1_Specialty_2
Principal_Investigator_1_Specialty_3
Principal_Investigator_1_Specialty_4
Principal_Investigator_1_Specialty_5
Principal_Investigator_1_Specialty_6
Principal_Investigator_1_License_State_code1
Principal_Investigator_1_License_State_code2
Principal_Investigator_1_License_State_code3
Principal_Investigator_1_License_State_code4
Principal_Investigator_1_License_State_code5
Principal_Investigator_2_Covered_Recipient_Type
Principal_Investigator_2_Profile_ID
Principal_Investigator_2_NPI
Principal_Investigator_2_First_Name
Principal_Investigator_2_Middle_Name
Principal_Investigator_2_Last_Name
Principal_Investigator_2_Name_Suffix
Principal_Investigator_2_Business_Street_Address_Line1
Principal_Investigator_2_Business_Street_Address_Line2
Principal_Investigator_2_City
Principal_Investigator_2_State
Principal_Investigator_2_Zip_Code
Principal_Investigator_2_Country
Principal_Investigator_2_Province
Principal_Investigator_2_Postal_Code
Principal_Investigator_2_Primary_Type_1
Principal_Investigator_2_Primary_Type_2
Principal_Investigator_2_Primary_Type_3
Principal_Investigator_2_Primary_Type_4
Principal_Investigator_2_Primary_Type_5
Principal_Investigator_2_Primary_Type_6
Principal_Investigator_2_Specialty_1
Principal_Investigator_2_Specialty_2
Principal_Investigator_2_Specialty_3
Principal_Investigator_2_Specialty_4
Principal_Investigator_2_Specialty_5
Principal_Investigator_2_Specialty_6
Principal_Investigator_2_License_State_code1
Principal_Investigator_2_License_State_code2
Principal_Investigator_2_License_State_code3
Principal_Investigator_2_License_State_code4
Principal_Investigator_2_License_State_code5
Principal_Investigator_3_Covered_Recipient_Type
Principal_Investigator_3_Profile_ID
Principal_Investigator_3_NPI
Principal_Investigator_3_First_Name
Principal_Investigator_3_Middle_Name
Principal_Investigator_3_Last_Name
Principal_Investigator_3_Name_Suffix
Principal_Investigator_3_Business_Street_Address_Line1
Principal_Investigator_3_Business_Street_Address_Line2
Principal_Investigator_3_City
Principal_Investigator_3_State
Principal_Investigator_3_Zip_Code
Principal_Investigator_3_Country
Principal_Investigator_3_Province
Principal_Investigator_3_Postal_Code
Principal_Investigator_3_Primary_Type_1
Principal_Investigator_3_Primary_Type_2
Principal_Investigator_3_Primary_Type_3
Principal_Investigator_3_Primary_Type_4
Principal_Investigator_3_Primary_Type_5
Principal_Investigator_3_Primary_Type_6
Principal_Investigator_3_Specialty_1
Principal_Investigator_3_Specialty_2
Principal_Investigator_3_Specialty_3
Principal_Investigator_3_Specialty_4
Principal_Investigator_3_Specialty_5
Principal_Investigator_3_Specialty_6
Principal_Investigator_3_License_State_code1
Principal_Investigator_3_License_State_code2
Principal_Investigator_3_License_State_code3
Principal_Investigator_3_License_State_code4
Principal_Investigator_3_License_State_code5
Principal_Investigator_4_Covered_Recipient_Type
Principal_Investigator_4_Profile_ID
Principal_Investigator_4_NPI
Principal_Investigator_4_First_Name
Principal_Investigator_4_Middle_Name
Principal_Investigator_4_Last_Name
Principal_Investigator_4_Name_Suffix
Principal_Investigator_4_Business_Street_Address_Line1
Principal_Investigator_4_Business_Street_Address_Line2
Principal_Investigator_4_City
Principal_Investigator_4_State
Principal_Investigator_4_Zip_Code
Principal_Investigator_4_Country
Principal_Investigator_4_Province
Principal_Investigator_4_Postal_Code
Principal_Investigator_4_Primary_Type_1
Principal_Investigator_4_Primary_Type_2
Principal_Investigator_4_Primary_Type_3
Principal_Investigator_4_Primary_Type_4
Principal_Investigator_4_Primary_Type_5
Principal_Investigator_4_Primary_Type_6
Principal_Investigator_4_Specialty_1
Principal_Investigator_4_Specialty_2
Principal_Investigator_4_Specialty_3
Principal_Investigator_4_Specialty_4
Principal_Investigator_4_Specialty_5
Principal_Investigator_4_Specialty_6
Principal_Investigator_4_License_State_code1
Principal_Investigator_4_License_State_code2
Principal_Investigator_4_License_State_code3
Principal_Investigator_4_License_State_code4
Principal_Investigator_4_License_State_code5
Principal_Investigator_5_Covered_Recipient_Type
Principal_Investigator_5_Profile_ID
Principal_Investigator_5_NPI
Principal_Investigator_5_First_Name
Principal_Investigator_5_Middle_Name
Principal_Investigator_5_Last_Name
Principal_Investigator_5_Name_Suffix
Principal_Investigator_5_Business_Street_Address_Line1
Principal_Investigator_5_Business_Street_Address_Line2
Principal_Investigator_5_City
Principal_Investigator_5_State
Principal_Investigator_5_Zip_Code
Principal_Investigator_5_Country
Principal_Investigator_5_Province
Principal_Investigator_5_Postal_Code
Principal_Investigator_5_Primary_Type_1
Principal_Investigator_5_Primary_Type_2
Principal_Investigator_5_Primary_Type_3
Principal_Investigator_5_Primary_Type_4
Principal_Investigator_5_Primary_Type_5
Principal_Investigator_5_Primary_Type_6
Principal_Investigator_5_Specialty_1
Principal_Investigator_5_Specialty_2
Principal_Investigator_5_Specialty_3
Principal_Investigator_5_Specialty_4
Principal_Investigator_5_Specialty_5
Principal_Investigator_5_Specialty_6
Principal_Investigator_5_License_State_code1
Principal_Investigator_5_License_State_code2
Principal_Investigator_5_License_State_code3
Principal_Investigator_5_License_State_code4
Principal_Investigator_5_License_State_code5
Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country
Related_Product_Indicator
Covered_or_Noncovered_Indicator_1
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1
Product_Category_or_Therapeutic_Area_1
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1
Associated_Drug_or_Biological_NDC_1
Associated_Device_or_Medical_Supply_PDI_1
Covered_or_Noncovered_Indicator_2
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2
Product_Category_or_Therapeutic_Area_2
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2
Associated_Drug_or_Biological_NDC_2
Associated_Device_or_Medical_Supply_PDI_2
Covered_or_Noncovered_Indicator_3
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3
Product_Category_or_Therapeutic_Area_3
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3
Associated_Drug_or_Biological_NDC_3
Associated_Device_or_Medical_Supply_PDI_3
Covered_or_Noncovered_Indicator_4
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4
Product_Category_or_Therapeutic_Area_4
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4
Associated_Drug_or_Biological_NDC_4
Associated_Device_or_Medical_Supply_PDI_4
Covered_or_Noncovered_Indicator_5
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5
Product_Category_or_Therapeutic_Area_5
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
Associated_Drug_or_Biological_NDC_5
Associated_Device_or_Medical_Supply_PDI_5
Total_Amount_of_Payment_USDollars
Date_of_Payment
Form_of_Payment_or_Transfer_of_Value
Expenditure_Category1
Expenditure_Category2
Expenditure_Category3
Expenditure_Category4
Expenditure_Category5
Expenditure_Category6
Preclinical_Research_Indicator
Delay_in_Publication_Indicator
Name_of_Study
Dispute_Status_for_Publication
Record_ID
Program_Year
Payment_Publication_Date
ClinicalTrials_Gov_Identifier
Research_Information_Link
Context_of_Research

In [6]:
df1[['Change_Type','Noncovered_Recipient_Entity_Name']].describe()

       Change_Type Noncovered_Recipient_Entity_Name
count      1028472                           888712
unique           1                            28211
top            NEW             ClinEdge, LLC - PPDS
freq       1028472                            43688

In [7]:
df1[['Change_Type','Noncovered_Recipient_Entity_Name']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 2 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   Change_Type                       1028472 non-null  object
 1   Noncovered_Recipient_Entity_Name  888712 non-null   object
dtypes: object(2)
memory usage: 15.7+ MB

In [8]:
df1['Noncovered_Recipient_Entity_Name'].describe()

count                   888712
unique                   28211
top       ClinEdge, LLC - PPDS
freq                     43688
Name: Noncovered_Recipient_Entity_Name, dtype: object

In [9]:
df1['Noncovered_Recipient_Entity_Name'].value_counts(dropna=False)

Noncovered_Recipient_Entity_Name
NaN                                                   139760
ClinEdge, LLC - PPDS                                   43688
DYNAMED CLINICAL RESEARCH LP                           18571
VELOCITY CLINICAL RESEARCH INC                         15635
DELRICHT LLC                                           13797
                                                       ...
JOHNS HOPKINS UNIVERSITY EMERGENCY                         1
KENNETH SHAIN                                              1
ARTHRITIS & OSTEO MEDICAL CTR                              1
Anne Arundel Medical Center Oncology and Hematolog         1
Foothills Research Center                                  1
Name: count, Length: 28212, dtype: int64

In [10]:
msk = df1['Noncovered_Recipient_Entity_Name'].notna()
df1.loc[msk, 'Noncovered_Recipient_Entity_Name'] = df1.loc[msk, 'Noncovered_Recipient_Entity_Name'].astype(str)
# Converting all names to lower first to verify. 
df1.loc[msk, 'Noncovered_Recipient_Entity_Name']= df1.loc[msk,'Noncovered_Recipient_Entity_Name'].apply(lambda x: x.lower())
df1['Noncovered_Recipient_Entity_Name'].nunique()

23932

In [11]:
df1['Noncovered_Recipient_Entity_Name'].value_counts(dropna=False)

Noncovered_Recipient_Entity_Name
NaN                                                   139760
clinedge, llc - ppds                                   43688
dynamed clinical research lp                           18835
velocity clinical research inc                         16255
delricht llc                                           13987
                                                       ...
moffitt cancer center-thoracic department                  1
the regents of the university of california / univ         1
heart center research llc research                         1
arthritis center of north georgia                          1
foothills research center                                  1
Name: count, Length: 23933, dtype: int64

In [12]:
# Verification after converting to lower case
df1[['Change_Type','Noncovered_Recipient_Entity_Name']].describe()

       Change_Type Noncovered_Recipient_Entity_Name
count      1028472                           888712
unique           1                            23932
top            NEW             clinedge, llc - ppds
freq       1028472                            43688

In [13]:
df1['Noncovered_Recipient_Entity_Name'].describe()

count                   888712
unique                   23932
top       clinedge, llc - ppds
freq                     43688
Name: Noncovered_Recipient_Entity_Name, dtype: object

In [14]:
df1.Teaching_Hospital_CCN.describe()

count    113385.000000
mean     248510.717458
std      156720.596440
min       10001.000000
25%      100025.000000
50%      230046.000000
75%      390028.000000
max      670025.000000
Name: Teaching_Hospital_CCN, dtype: float64

In [15]:
# Converting to object, as its ID
df1.Teaching_Hospital_CCN=df1.Teaching_Hospital_CCN.astype(object)

In [16]:
df1.Teaching_Hospital_CCN.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1028472 entries, 0 to 1028471
Series name: Teaching_Hospital_CCN
Non-Null Count   Dtype
--------------   -----
113385 non-null  object
dtypes: object(1)
memory usage: 7.8+ MB

In [17]:
df1.Teaching_Hospital_CCN.describe()

count     113385.0
unique       666.0
top       450076.0
freq        5217.0
Name: Teaching_Hospital_CCN, dtype: float64

In [18]:
df1.Teaching_Hospital_CCN.value_counts(dropna=False)

Teaching_Hospital_CCN
NaN         915087
450076.0      5217
230046.0      3138
10033.0       3015
440039.0      2967
             ...
410004.0         1
150002.0         1
150017.0         1
330159.0         1
520136.0         1
Name: count, Length: 667, dtype: int64

In [19]:
df1.Teaching_Hospital_CCN.describe()

count     113385.0
unique       666.0
top       450076.0
freq        5217.0
Name: Teaching_Hospital_CCN, dtype: float64

In [20]:
df1.Teaching_Hospital_ID.describe()

count    113385.000000
mean      13451.368894
std         425.905403
min       12720.000000
25%       13096.000000
50%       13507.000000
75%       13879.000000
max       14070.000000
Name: Teaching_Hospital_ID, dtype: float64

In [21]:
# Converting id to object type
df1.Teaching_Hospital_ID = df1.Teaching_Hospital_ID.astype(object)

In [22]:
df1.Teaching_Hospital_ID.nunique()

666

In [23]:
#df1.Teaching_Hospital_ID.info()

In [24]:
df1[['Teaching_Hospital_ID']].value_counts().dropna(how='None')

Teaching_Hospital_ID
13764.0                 5217
13271.0                 3138
13662.0                 3015
13148.0                 2967
12957.0                 2965
                        ...
13639.0                    1
13821.0                    1
13439.0                    1
13200.0                    1
13062.0                    1
Name: count, Length: 666, dtype: int64

**Verifying ID, CCN and teaching hospital name**

In [25]:
df1[['Teaching_Hospital_ID', 'Teaching_Hospital_CCN']].value_counts(dropna=False)

Teaching_Hospital_ID  Teaching_Hospital_CCN
NaN                   NaN                      915087
13764.0               450076.0                   5217
13271.0               230046.0                   3138
13662.0               10033.0                    3015
13148.0               440039.0                   2967
                                                ...
13603.0               100248.0                      1
13605.0               100213.0                      1
13127.0               150002.0                      1
13143.0               150017.0                      1
13062.0               360234.0                      1
Name: count, Length: 667, dtype: int64

Teaching_Hospital_ID, Teaching_Hospital_CCN unique 666 values, identifiers. Only one can be considered.

In [26]:
df1.Teaching_Hospital_Name.nunique() # Should be 666

1101

In [27]:
df1.Teaching_Hospital_Name.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1028472 entries, 0 to 1028471
Series name: Teaching_Hospital_Name
Non-Null Count   Dtype
--------------   -----
113385 non-null  object
dtypes: object(1)
memory usage: 7.8+ MB

In [28]:
1028471-113385

915086

In [29]:
df1['Teaching_Hospital_Name'].describe()

count                           113385
unique                            1101
top       Ut Md Anderson Cancer Center
freq                              3022
Name: Teaching_Hospital_Name, dtype: object

In [30]:
df1['Teaching_Hospital_Name']

0          Northshore University Healthsystem
1               DELL CHILDRENS MEDICAL CENTER
2                                         NaN
3                   OHSU HOSPITAL AND CLINICS
4                   Maryland General Hospital
                          ...
1028467                                   NaN
1028468                                   NaN
1028469                                   NaN
1028470                                   NaN
1028471                                   NaN
Name: Teaching_Hospital_Name, Length: 1028472, dtype: object

In [31]:
# Filtering out null values

msk = df1['Teaching_Hospital_Name'].notna()
df1.loc[msk, 'Teaching_Hospital_Name'] = df1.loc[msk, 'Teaching_Hospital_Name'].astype(str)

# Converting all names to lower first to verify. 
df1.loc[msk, 'Teaching_Hospital_Name']= df1.loc[msk,'Teaching_Hospital_Name'].apply(lambda x: x.lower())
df1['Teaching_Hospital_Name'].nunique()

679

In [32]:
# Taking id list to check each ID variations
Hospital_id_list=df1.Teaching_Hospital_ID.unique()

# Identifying hospital ID with more than one unique names to standardize them
id_list=[]
for i in Hospital_id_list:
    if df1[df1['Teaching_Hospital_ID']==i]['Teaching_Hospital_Name'].nunique() > 1:
        id_list.append(i)
print('Hospitals ids with multiple names', id_list)

Hospitals ids with multiple names [13486.0, 13135.0, 13245.0, 13070.0, 13273.0, 13584.0, 12743.0, 13413.0, 13231.0, 13467.0, 13855.0, 13526.0, 13260.0]

In [33]:
# Verifying the differences in names for same Teaching_Hospital_IDs.
for i in id_list:
    print("The hospital id", i)
    print(df1[df1['Teaching_Hospital_ID']==i]['Teaching_Hospital_Name'].value_counts())

The hospital id 13486.0
Teaching_Hospital_Name
forsyth memorial hospital  inc    51
forsyth memorial hospital inc     51
Name: count, dtype: int64
The hospital id 13135.0
Teaching_Hospital_Name
community health network  inc.    401
community health network inc.      20
Name: count, dtype: int64
The hospital id 13245.0
Teaching_Hospital_Name
william beaumont hospital- royal oak     70
william beaumont hospital - royal oak    12
Name: count, dtype: int64
The hospital id 13070.0
Teaching_Hospital_Name
univer.of cincinnati med center llc     116
univer. of cincinnati med center llc      7
Name: count, dtype: int64
The hospital id 13273.0
Teaching_Hospital_Name
aurora health care metro inc.     39
aurora health care metro  inc.     5
Name: count, dtype: int64
The hospital id 13584.0
Teaching_Hospital_Name
norton hospitals  inc    117
norton hospitals inc      29
Name: count, dtype: int64
The hospital id 12743.0
Teaching_Hospital_Name
lahey clinic hospital  inc.    9
lahey clinic hospital inc.     2
Name: count, dtype: int64
The hospital id 13413.0
Teaching_Hospital_Name
sinai hospital of baltimore  inc.    57
sinai hospital of baltimore inc.      6
Name: count, dtype: int64
The hospital id 13231.0
Teaching_Hospital_Name
spectrum health hospitals     111
spectrum health  hospitals     20
Name: count, dtype: int64
The hospital id 13467.0
Teaching_Hospital_Name
st. marys medical center inc.     5
st. marys medical center  inc.    3
Name: count, dtype: int64
The hospital id 13855.0
Teaching_Hospital_Name
mission hospital  inc    23
mission hospital inc      2
Name: count, dtype: int64
The hospital id 13526.0
Teaching_Hospital_Name
au medical center  inc    12
au medical center inc      2
Name: count, dtype: int64
The hospital id 13260.0
Teaching_Hospital_Name
st joseph mercy hospital ann arbor     31
st joseph mercy hospital  ann arbor     2
Name: count, dtype: int64

In [34]:
for i in  id_list:
    abcd=df1[df1['Teaching_Hospital_ID']==i]['Teaching_Hospital_Name'].value_counts()
    indexes=df1.loc[df1['Teaching_Hospital_ID']==i].index
    val=abcd.index[abcd.argmax()]
    df1.loc[indexes,'Teaching_Hospital_Name']= val

In [35]:
# Verification
df1[['Teaching_Hospital_Name', 'Teaching_Hospital_ID']].value_counts(dropna=False)

Teaching_Hospital_Name                Teaching_Hospital_ID
NaN                                   NaN                     915087
ut md anderson cancer center          13764.0                   5217
univ of mi hospitals & hlth ctrs      13271.0                   3138
university of alabama hospital        13662.0                   3015
vanderbilt university medical center  13148.0                   2967
                                                               ...
baptist saint anthonys hospital       13050.0                      1
forrest general hospital              13672.0                      1
cambridge health alliance             12750.0                      1
ochsner lsu health shreveport         13854.0                      1
childrens hospital & medical center   13384.0                      1
Name: count, Length: 667, dtype: int64

In [36]:
df1['Teaching_Hospital_Name'].describe()

count                           113385
unique                             666
top       ut md anderson cancer center
freq                              5217
Name: Teaching_Hospital_Name, dtype: object

In [37]:
df1['Teaching_Hospital_Name'].value_counts(dropna=False)

Teaching_Hospital_Name
NaN                                     915087
ut md anderson cancer center              5217
univ of mi hospitals & hlth ctrs          3138
university of alabama hospital            3015
vanderbilt university medical center      2967
                                         ...
roger williams medical center                1
methodist hospitals  inc                     1
lutheran hospital of indiana                 1
upstate univ hosp at comm general            1
ascension se wisconsin hospital  inc         1
Name: count, Length: 667, dtype: int64

* **Teaching_Hospital_CCN, Teaching_Hospital_ID now can be dropped, Teaching_Hospital_Name clean**

In [38]:
# Standardization of recipient columns
df1.Covered_Recipient_Type.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1028472 entries, 0 to 1028471
Series name: Covered_Recipient_Type
Non-Null Count    Dtype
--------------    -----
1028472 non-null  object
dtypes: object(1)
memory usage: 7.8+ MB

In [39]:
df1.Covered_Recipient_Type.describe()

count                          1028472
unique                               5
top       Non-covered Recipient Entity
freq                            888712
Name: Covered_Recipient_Type, dtype: object

In [40]:
df1.Covered_Recipient_Type.value_counts(dropna=False)

Covered_Recipient_Type
Non-covered Recipient Entity                    888712
Covered Recipient Teaching Hospital             113385
Covered Recipient Physician                      25137
Covered Recipient Non-Physician Practitioner      1168
Non-covered Recipient Individual                    70
Name: count, dtype: int64

In [41]:
df1[['Covered_Recipient_Profile_ID','Covered_Recipient_NPI']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Covered_Recipient_Profile_ID  26305 non-null  float64
 1   Covered_Recipient_NPI         26213 non-null  float64
dtypes: float64(2)
memory usage: 15.7 MB

In [42]:
# Converting to object type as they are IDs
df1['Covered_Recipient_Profile_ID']=df1['Covered_Recipient_Profile_ID'].astype(object)
df1['Covered_Recipient_NPI']=df1['Covered_Recipient_NPI'].astype(object)

In [43]:
df1[['Covered_Recipient_Profile_ID', 'Covered_Recipient_NPI', 'Covered_Recipient_First_Name',
    'Covered_Recipient_Middle_Name', 'Covered_Recipient_Last_Name', 'Covered_Recipient_Name_Suffix',
    'Covered_Recipient_Primary_Type_1', 'Covered_Recipient_Primary_Type_2','Covered_Recipient_Primary_Type_3',
    'Covered_Recipient_Primary_Type_4', 'Covered_Recipient_Primary_Type_5','Covered_Recipient_Primary_Type_6'
    ]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Covered_Recipient_Profile_ID      26305 non-null  object
 1   Covered_Recipient_NPI             26213 non-null  object
 2   Covered_Recipient_First_Name      26305 non-null  object
 3   Covered_Recipient_Middle_Name     7134 non-null   object
 4   Covered_Recipient_Last_Name       26305 non-null  object
 5   Covered_Recipient_Name_Suffix     356 non-null    object
 6   Covered_Recipient_Primary_Type_1  26305 non-null  object
 7   Covered_Recipient_Primary_Type_2  0 non-null      float64
 8   Covered_Recipient_Primary_Type_3  0 non-null      float64
 9   Covered_Recipient_Primary_Type_4  0 non-null      float64
 10  Covered_Recipient_Primary_Type_5  0 non-null      float64
 11  Covered_Recipient_Primary_Type_6  0 non-null      float64
dtypes: float64(5), object(7)
memory usage: 94.2+ MB

In [44]:
df1.Covered_Recipient_NPI.nunique()

5646

In [45]:
df1.Covered_Recipient_NPI.unique()

array([nan, 1124040993.0, 1134717622.0, ..., 1427034578.0, 1467483404.0,
       1306822929.0], dtype=object)

In [46]:
df1.Covered_Recipient_NPI.value_counts(dropna=False)

Covered_Recipient_NPI
NaN             1002259
1.679551e+09        295
1.891825e+09        181
1.710270e+09        173
1.881663e+09        136
                 ...
1.619916e+09          1
1.649387e+09          1
1.700860e+09          1
1.023276e+09          1
1.306823e+09          1
Name: count, Length: 5647, dtype: int64

In [47]:
df1.Covered_Recipient_Profile_ID.nunique()

5662

In [48]:
df1.Covered_Recipient_Profile_ID.unique()

array([nan, 452304.0, 11562059.0, ..., 19384.0, 111056.0, 58669.0],
      dtype=object)

In [49]:
df1.Covered_Recipient_Profile_ID.value_counts(dropna=False)

Covered_Recipient_Profile_ID
NaN         1002167
303222.0        295
312981.0        181
77345.0         173
357387.0        136
             ...
363540.0          1
874772.0          1
9081.0            1
122771.0          1
58669.0           1
Name: count, Length: 5663, dtype: int64

In [50]:
# To avoid nan getting converted to string. Recipient first name
msk = df1['Covered_Recipient_First_Name'].notna()
df1.loc[msk, 'Covered_Recipient_First_Name'] = df1.loc[msk, 'Covered_Recipient_First_Name'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Covered_Recipient_First_Name']= df1.loc[msk,'Covered_Recipient_First_Name'].apply(lambda x: x.lower())
df1['Covered_Recipient_First_Name'].nunique()

2201

In [51]:
df1['Covered_Recipient_First_Name'].value_counts(dropna=False)

Covered_Recipient_First_Name
NaN            1002167
david              783
michael            597
john               479
robert             347
                ...
jim                  1
amatul noor          1
parisa               1
ofer                 1
shuo                 1
Name: count, Length: 2202, dtype: int64

* Covered_Recipient_Profile_ID is system generated, Covered_Recipient_NPI is national provider identifier for recipient physician and non physian. Should be same count and interchangeable.

In [52]:
# To avoid nan getting converted to string. Recipient middle name
msk = df1['Covered_Recipient_Middle_Name'].notna()
df1.loc[msk, 'Covered_Recipient_Middle_Name'] = df1.loc[msk, 'Covered_Recipient_Middle_Name'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Covered_Recipient_Middle_Name']= df1.loc[msk,'Covered_Recipient_Middle_Name'].apply(lambda x: x.lower())
df1['Covered_Recipient_Middle_Name'].nunique()

612

In [53]:
df1['Covered_Recipient_Middle_Name'].value_counts(dropna=False)

Covered_Recipient_Middle_Name
NaN          1021338
a                430
m                386
j                346
s                285
              ...
lynch              1
neal               1
laing              1
regan              1
bao shian          1
Name: count, Length: 613, dtype: int64

In [54]:
# To avoid nan getting converted to string. Recipient last name
msk = df1['Covered_Recipient_Last_Name'].notna()
df1.loc[msk, 'Covered_Recipient_Last_Name'] = df1.loc[msk, 'Covered_Recipient_Last_Name'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Covered_Recipient_Last_Name']= df1.loc[msk,'Covered_Recipient_Last_Name'].apply(lambda x: x.lower())
df1['Covered_Recipient_Last_Name'].nunique()

4389

In [55]:
df1['Covered_Recipient_Last_Name'].value_counts(dropna=False)

Covered_Recipient_Last_Name
NaN             1002167
giedd               295
chhabra             183
wilson              183
garcia              156
                 ...
majcher               1
conrad                1
klein-mascia          1
zelen                 1
rudin                 1
Name: count, Length: 4390, dtype: int64

In [56]:
# To avoid nan getting converted to string. Recipient last name
msk = df1['Covered_Recipient_Name_Suffix'].notna()
df1.loc[msk, 'Covered_Recipient_Name_Suffix'] = df1.loc[msk, 'Covered_Recipient_Name_Suffix'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Covered_Recipient_Name_Suffix']= df1.loc[msk,'Covered_Recipient_Name_Suffix'].apply(lambda x: x.lower())
df1['Covered_Recipient_Name_Suffix'].nunique()

17

In [57]:
df1['Covered_Recipient_Name_Suffix'].value_counts(dropna=False)

Covered_Recipient_Name_Suffix
NaN      1028116
jr           201
jr.           40
iii           26
md            19
m.d.          16
dr.           16
i             10
v              8
ii             7
od             3
do             2
mr             2
p              2
iv             1
neal-          1
pa             1
sr             1
Name: count, dtype: int64

In [58]:
df1.Covered_Recipient_Primary_Type_1.nunique()

10

In [59]:
df1.Covered_Recipient_Primary_Type_1.value_counts(dropna=False)

Covered_Recipient_Primary_Type_1
NaN                             1002167
Medical Doctor                    23843
Doctor of Osteopathy                804
Nurse Practitioner                  799
Physician Assistant                 352
Doctor of Optometry                 341
Doctor of Dentistry                  87
Doctor of Podiatric Medicine         56
Clinical Nurse Specialist            12
Chiropractor                          6
Anesthesiologist Assistant            5
Name: count, dtype: int64

In [60]:
df1.Covered_Recipient_Primary_Type_2.value_counts(dropna=False)

Covered_Recipient_Primary_Type_2
NaN    1028472
Name: count, dtype: int64

In [61]:
df1.Covered_Recipient_Primary_Type_3.value_counts(dropna=False)

Covered_Recipient_Primary_Type_3
NaN    1028472
Name: count, dtype: int64

In [62]:
df1.Covered_Recipient_Primary_Type_4.value_counts(dropna=False)

Covered_Recipient_Primary_Type_4
NaN    1028472
Name: count, dtype: int64

In [63]:
df1.Covered_Recipient_Primary_Type_5.value_counts(dropna=False)

Covered_Recipient_Primary_Type_5
NaN    1028472
Name: count, dtype: int64

In [64]:
df1.Covered_Recipient_Primary_Type_6.value_counts(dropna=False)

Covered_Recipient_Primary_Type_6
NaN    1028472
Name: count, dtype: int64

In [65]:
# Reverify afrer all lower case conversion

df1[['Covered_Recipient_Profile_ID', 'Covered_Recipient_NPI', 'Covered_Recipient_First_Name',
    'Covered_Recipient_Middle_Name', 'Covered_Recipient_Last_Name', 'Covered_Recipient_Name_Suffix',
    'Covered_Recipient_Primary_Type_1'
    ]].describe()

,Covered_Recipient_Profile_ID,Covered_Recipient_NPI,Covered_Recipient_First_Name,Covered_Recipient_Middle_Name,Covered_Recipient_Last_Name,Covered_Recipient_Name_Suffix,Covered_Recipient_Primary_Type_1
count,26305.0,2.621300e+04,26305,7134,26305,356,26305
unique,5662.0,5.646000e+03,2201,612,4389,17,10
top,303222.0,1.679551e+09,david,a,giedd,jr,Medical Doctor
freq,295.0,2.950000e+02,783,430,295,201,23843

In [66]:

df1[[ 'Recipient_Primary_Business_Street_Address_Line1',
     'Recipient_Primary_Business_Street_Address_Line2', 'Recipient_City', 'Recipient_State',
     'Recipient_Zip_Code', 'Recipient_Country', 'Recipient_Province', 'Recipient_Postal_Code'
    ]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 8 columns):
 #   Column                                           Non-Null Count    Dtype
---  ------                                           --------------    -----
 0   Recipient_Primary_Business_Street_Address_Line1  1028388 non-null  object
 1   Recipient_Primary_Business_Street_Address_Line2  161948 non-null   object
 2   Recipient_City                                   1028400 non-null  object
 3   Recipient_State                                  1028090 non-null  object
 4   Recipient_Zip_Code                               1028090 non-null  object
 5   Recipient_Country                                1028402 non-null  object
 6   Recipient_Province                               60 non-null       object
 7   Recipient_Postal_Code                            312 non-null      object
dtypes: object(8)
memory usage: 62.8+ MB

In [67]:
df1.Recipient_Primary_Business_Street_Address_Line1.nunique()

35397

In [68]:
df1.Recipient_Primary_Business_Street_Address_Line1.value_counts(dropna=False)

Recipient_Primary_Business_Street_Address_Line1
911 E Hallandale Beach Blvd      43850
7908 N Sam Houston Pkwy W        20091
4621 South Carrollton Ave        13642
807 E Main Street Suite 6 100    13558
108 Myrtle Street Suite 201      10959
                                 ...
805 E 144th Ave                      1
4820 EMPEROR BLVD FL 8               1
401 E PRATT ST STE 1700 FL 17        1
PO BOX 78000DEPT. 78867              1
4530 E Ray Rd                        1
Name: count, Length: 35398, dtype: int64

In [69]:
df1.Recipient_Primary_Business_Street_Address_Line2.nunique()

5911

In [70]:
df1.Recipient_Primary_Business_Street_Address_Line2.value_counts(dropna=False)

Recipient_Primary_Business_Street_Address_Line2
NaN                                  866524
STE 535                                3375
STE 100                                3033
0                                      2957
STE 200                                2584
                                      ...
Suite L                                   1
621 S. New Ballas Rd, Suite 6002B         1
RM S1-620                                 1
Columbia County                           1
STE 508                                   1
Name: count, Length: 5912, dtype: int64

In [71]:
df1.Recipient_City.nunique()

4155

In [72]:
# To avoid nan getting converted to string.
msk = df1['Recipient_City'].notna()
df1.loc[msk, 'Recipient_City'] = df1.loc[msk, 'Recipient_City'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Recipient_City']= df1.loc[msk,'Recipient_City'].apply(lambda x: x.lower())
df1['Recipient_City'].nunique()

2664

In [73]:
df1.Recipient_City.value_counts(dropna=False)

Recipient_City
houston             44290
hallandale beach    43885
new orleans         25754
durham              24028
miami               19850
                    ...
newman                  1
brookfield              1
harker heights          1
gyeonggi do             1
bourbonnais             1
Name: count, Length: 2665, dtype: int64

In [74]:
df1.Recipient_State.nunique()

52

In [75]:
df1.Recipient_State.value_counts(dropna=False)

Recipient_State
FL     169479
TX     138822
CA     100722
NC      60985
NY      42690
AZ      35694
MA      35616
LA      31535
OH      28753
PA      26384
TN      26178
GA      25615
IL      24403
VA      23403
NE      18411
MI      17995
MO      16204
KS      13507
MN      13286
WA      13184
CO      12818
MD      12094
SC      11317
AL      11301
NJ      10553
UT      10469
CT       9106
ID       8931
NV       8800
WI       8031
KY       7915
IN       7753
OK       6686
OR       6513
AR       5247
IA       4028
PR       3826
MS       2660
DC       2217
DE       2196
RI       1684
NH       1635
NM       1610
WV       1227
SD       1225
ND       1209
MT       1208
HI       1154
VT        968
ME        577
NaN       382
AK        258
WY          8
Name: count, dtype: int64

In [76]:
df1[['Recipient_State', 'Recipient_City','Recipient_Zip_Code' ]].nunique()

Recipient_State          52
Recipient_City         2664
Recipient_Zip_Code    10859
dtype: int64

In [77]:
df1[['Recipient_Zip_Code' ]].value_counts(dropna=False)

Recipient_Zip_Code
33009-4427            43689
77064                 24705
27701                 18190
70119                 14216
33016                 14215
                      ...
77030-2303                1
77030-2358                1
77030-2418                1
21218-2829                1
00603                     1
Name: count, Length: 10860, dtype: int64

In [78]:
df1[['Recipient_Zip_Code' ]].nunique()

Recipient_Zip_Code    10859
dtype: int64

In [79]:
# Converting country to lower case
# To avoid nan getting converted to string.
msk = df1['Recipient_Country'].notna()
df1.loc[msk, 'Recipient_Country'] = df1.loc[msk, 'Recipient_Country'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Recipient_Country']= df1.loc[msk,'Recipient_Country'].apply(lambda x: x.lower())
df1['Recipient_Country'].nunique()

9

In [80]:
df1.Recipient_Country.value_counts(dropna=False)

Recipient_Country
united states                           1028090
ireland                                     227
NaN                                          70
canada                                       67
great britain (uk)                            9
france                                        4
israel                                        2
united states minor outlying islands          1
korea (republic of)                           1
aland islands                                 1
Name: count, dtype: int64

In [81]:
# Converting province to lower case
# To avoid nan getting converted to string.
msk = df1['Recipient_Province'].notna()
df1.loc[msk, 'Recipient_Province'] = df1.loc[msk, 'Recipient_Province'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Recipient_Province']= df1.loc[msk,'Recipient_Province'].apply(lambda x: x.lower())
df1['Recipient_Province'].nunique()

6

In [82]:
df1.Recipient_Province.value_counts(dropna=False), df1.Recipient_Province.nunique()

(Recipient_Province
 NaN         1028412
 on               51
 ab                3
 manitoba          3
 md                1
 ontario           1
 indiana           1
 Name: count, dtype: int64,
 6)

In [83]:
# Converting postal code to lower case
# To avoid nan getting converted to string.
msk = df1['Recipient_Postal_Code'].notna()
df1.loc[msk, 'Recipient_Postal_Code'] = df1.loc[msk, 'Recipient_Postal_Code'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Recipient_Postal_Code']= df1.loc[msk,'Recipient_Postal_Code'].apply(lambda x: x.lower())
df1['Recipient_Postal_Code'].nunique()

22

In [84]:
df1.Recipient_Postal_Code.value_counts(dropna=False)

Recipient_Postal_Code
NaN         1028160
d18 px68        205
l8n 4a6          25
n2j 1c4          21
d18 fk72         11
d4                9
m5g 2m9           9
ls2 9lh           6
75013             4
r2k3s8            3
t6g 2c8           3
se1 3qd           2
6971054           2
00018             2
n2j               2
sw7 3rp           1
20817             1
l8l 8e7           1
m9l 3             1
410769            1
l6y 4m3           1
k1h 8l6           1
46278             1
Name: count, dtype: int64

In [85]:
## Reverifying after converting to lower case
df1[[ 'Recipient_Primary_Business_Street_Address_Line1',
     'Recipient_Primary_Business_Street_Address_Line2', 'Recipient_City', 'Recipient_State',
     'Recipient_Zip_Code', 'Recipient_Country', 'Recipient_Province', 'Recipient_Postal_Code'
    ]].describe()

,Recipient_Primary_Business_Street_Address_Line1,Recipient_Primary_Business_Street_Address_Line2,Recipient_City,Recipient_State,Recipient_Zip_Code,Recipient_Country,Recipient_Province,Recipient_Postal_Code
count,1028388,161948,1028400,1028090,1028090,1028402,60,312
unique,35397,5911,2664,52,10859,9,6,22
top,911 E Hallandale Beach Blvd,STE 535,houston,FL,33009-4427,united states,on,d18 px68
freq,43850,3375,44290,169479,43689,1028090,51,205

In [86]:
## Covered recipient primary types

In [87]:
df1[['Covered_Recipient_Primary_Type_1', 'Covered_Recipient_Primary_Type_2', 
    'Covered_Recipient_Primary_Type_3', 'Covered_Recipient_Primary_Type_4',
    'Covered_Recipient_Primary_Type_5', 'Covered_Recipient_Primary_Type_6']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Covered_Recipient_Primary_Type_1  26305 non-null  object
 1   Covered_Recipient_Primary_Type_2  0 non-null      float64
 2   Covered_Recipient_Primary_Type_3  0 non-null      float64
 3   Covered_Recipient_Primary_Type_4  0 non-null      float64
 4   Covered_Recipient_Primary_Type_5  0 non-null      float64
 5   Covered_Recipient_Primary_Type_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [88]:
df1['Covered_Recipient_Primary_Type_1'].describe()

count              26305
unique                10
top       Medical Doctor
freq               23843
Name: Covered_Recipient_Primary_Type_1, dtype: object

In [89]:
df1['Covered_Recipient_Primary_Type_1'].value_counts(dropna=False)

Covered_Recipient_Primary_Type_1
NaN                             1002167
Medical Doctor                    23843
Doctor of Osteopathy                804
Nurse Practitioner                  799
Physician Assistant                 352
Doctor of Optometry                 341
Doctor of Dentistry                  87
Doctor of Podiatric Medicine         56
Clinical Nurse Specialist            12
Chiropractor                          6
Anesthesiologist Assistant            5
Name: count, dtype: int64

Covered Resident specialities

In [90]:
df1[['Covered_Recipient_Specialty_1', 'Covered_Recipient_Specialty_2', 
    'Covered_Recipient_Specialty_3', 'Covered_Recipient_Specialty_4',
    'Covered_Recipient_Specialty_5', 'Covered_Recipient_Specialty_6']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Covered_Recipient_Specialty_1  26305 non-null  object
 1   Covered_Recipient_Specialty_2  0 non-null      float64
 2   Covered_Recipient_Specialty_3  0 non-null      float64
 3   Covered_Recipient_Specialty_4  0 non-null      float64
 4   Covered_Recipient_Specialty_5  0 non-null      float64
 5   Covered_Recipient_Specialty_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [91]:
df1['Covered_Recipient_Specialty_1'].describe()

count                                                 26305
unique                                                  190
top       Allopathic & Osteopathic Physicians|Psychiatry...
freq                                                   2437
Name: Covered_Recipient_Specialty_1, dtype: object

In [92]:
df1.Covered_Recipient_Specialty_1.nunique()

190

In [93]:
df1.Covered_Recipient_Specialty_1.value_counts(dropna=False)

Covered_Recipient_Specialty_1
NaN                                                                                                    1002167
Allopathic & Osteopathic Physicians|Psychiatry & Neurology|Neurology                                      2437
Allopathic & Osteopathic Physicians|Internal Medicine                                                     2333
Allopathic & Osteopathic Physicians|Internal Medicine|Hematology & Oncology                               2016
Allopathic & Osteopathic Physicians|Dermatology                                                           1398
                                                                                                        ...
Allopathic & Osteopathic Physicians|Otolaryngology|Otology & Neurotology                                     1
Allopathic & Osteopathic Physicians|Otolaryngology|Plastic Surgery within the Head & Neck                    1
Allopathic & Osteopathic Physicians|Ophthalmology|Pediatric Ophthalmology and Strabismus Specialist          1
Allopathic & Osteopathic Physicians|Pathology|Clinical Pathology                                             1
Allopathic & Osteopathic Physicians|Pediatrics|Developmental  Behavioral Pediatrics                          1
Name: count, Length: 191, dtype: int64

In [94]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Covered_Recipient_Specialty_1'].notna()
df1.loc[msk, 'Covered_Recipient_Specialty_1'] = df1.loc[msk, 'Covered_Recipient_Specialty_1'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Covered_Recipient_Specialty_1']= df1.loc[msk,'Covered_Recipient_Specialty_1'].apply(lambda x: x.lower())
df1['Covered_Recipient_Specialty_1'].nunique()

190

In [95]:
# verifying after converting to lower case
df1[['Covered_Recipient_Specialty_1']].describe()

                            Covered_Recipient_Specialty_1
count                                               26305
unique                                                190
top     allopathic & osteopathic physicians|psychiatry...
freq                                                 2437

Covered Resident license state code

In [96]:
df1[['Covered_Recipient_License_State_code1', 'Covered_Recipient_License_State_code2', 
    'Covered_Recipient_License_State_code3', 'Covered_Recipient_License_State_code4',
    'Covered_Recipient_License_State_code5' ]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 5 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Covered_Recipient_License_State_code1  26305 non-null  object
 1   Covered_Recipient_License_State_code2  67 non-null     object
 2   Covered_Recipient_License_State_code3  11 non-null     object
 3   Covered_Recipient_License_State_code4  1 non-null      object
 4   Covered_Recipient_License_State_code5  1 non-null      object
dtypes: object(5)
memory usage: 39.2+ MB

In [97]:
df1[['Covered_Recipient_License_State_code1', 'Covered_Recipient_License_State_code2', 
    'Covered_Recipient_License_State_code3', 'Covered_Recipient_License_State_code4',
    'Covered_Recipient_License_State_code5' ]].describe()

,Covered_Recipient_License_State_code1,Covered_Recipient_License_State_code2,Covered_Recipient_License_State_code3,Covered_Recipient_License_State_code4,Covered_Recipient_License_State_code5
count,26305,67,11,1,1
unique,52,18,4,1,1
top,CA,PA,TN,PA,SC
freq,3539,12,5,1,1

In [98]:
df1[['Covered_Recipient_License_State_code1']].nunique()

Covered_Recipient_License_State_code1    52
dtype: int64

In [99]:
df1[['Covered_Recipient_License_State_code1']].value_counts(dropna=False)

Covered_Recipient_License_State_code1
NaN                                      1002167
CA                                          3539
FL                                          2767
TX                                          1803
NY                                          1673
MA                                          1185
PA                                          1112
NC                                          1058
IL                                           986
MI                                           861
OH                                           839
GA                                           692
NJ                                           684
AZ                                           682
MD                                           644
TN                                           608
CO                                           558
MO                                           496
IN                                           430
MN                                           427
KY                                           411
WA                                           400
SC                                           387
VA                                           375
DC                                           370
CT                                           357
PR                                           314
KS                                           275
LA                                           255
AL                                           239
OR                                           212
UT                                           176
OK                                           167
WI                                           157
AR                                           150
NE                                           141
NM                                           117
NV                                           114
ID                                           113
IA                                            81
MS                                            79
RI                                            60
NH                                            51
SD                                            46
DE                                            38
ME                                            37
AK                                            30
ND                                            29
MT                                            27
HI                                            27
WV                                            17
VT                                             8
GU                                             1
Name: count, dtype: int64

In [100]:
df1[['Covered_Recipient_License_State_code2']].nunique()

Covered_Recipient_License_State_code2    18
dtype: int64

In [101]:
df1[['Covered_Recipient_License_State_code2']].value_counts(dropna=False)

Covered_Recipient_License_State_code2
NaN                                      1028405
PA                                            12
GA                                             5
IA                                             5
TX                                             5
SC                                             5
NY                                             4
FL                                             4
MI                                             4
MA                                             4
RI                                             3
IN                                             3
MN                                             2
OH                                             2
LA                                             2
IL                                             2
WA                                             2
WV                                             2
NE                                             1
Name: count, dtype: int64

In [102]:
df1[['Covered_Recipient_License_State_code3']].value_counts(dropna=False)

Covered_Recipient_License_State_code3
NaN                                      1028461
TN                                             5
OH                                             4
KY                                             1
NC                                             1
Name: count, dtype: int64

In [103]:
df1[['Covered_Recipient_License_State_code3']].nunique()

Covered_Recipient_License_State_code3    4
dtype: int64

In [104]:
df1[['Covered_Recipient_License_State_code4']].value_counts(dropna=False)

Covered_Recipient_License_State_code4
NaN                                      1028471
PA                                             1
Name: count, dtype: int64

In [105]:
df1[['Covered_Recipient_License_State_code4']].nunique()

Covered_Recipient_License_State_code4    1
dtype: int64

In [106]:
df1[['Covered_Recipient_License_State_code5']].value_counts(dropna=False)

Covered_Recipient_License_State_code5
NaN                                      1028471
SC                                             1
Name: count, dtype: int64

In [107]:
df1[df1.Covered_Recipient_License_State_code1.notna() & df1.Covered_Recipient_License_State_code2.notna()& 
    df1.Covered_Recipient_License_State_code3.notna()& df1.Covered_Recipient_License_State_code4.notna()|
    df1.Covered_Recipient_License_State_code5.notna()][['Covered_Recipient_License_State_code1',
                                                        'Covered_Recipient_License_State_code2',
                                                       'Covered_Recipient_License_State_code3',
                                                       'Covered_Recipient_License_State_code4',
                                                       'Covered_Recipient_License_State_code5']]

,Covered_Recipient_License_State_code1,Covered_Recipient_License_State_code2,Covered_Recipient_License_State_code3,Covered_Recipient_License_State_code4,Covered_Recipient_License_State_code5
9134,IA,MN,NC,PA,SC

GPO columns

In [108]:
df1[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name',
    'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID',
    'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name', 
    'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State',
    'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 5 columns):
 #   Column                                                            Non-Null Count    Dtype
---  ------                                                            --------------    -----
 0   Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name         1028472 non-null  object
 1   Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID       1028472 non-null  int64
 2   Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name     1028472 non-null  object
 3   Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State    896932 non-null   object
 4   Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country  1028472 non-null  object
dtypes: int64(1), object(4)
memory usage: 39.2+ MB

In [109]:
# Converting ID to object
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID']=df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID'].astype(object)

In [110]:
# To avoid nan getting converted to string. submitting applicable manufacturer GPO name
msk = df1['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'].notna()
df1.loc[msk, 'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'] = df1.loc[msk, 'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'].astype(str)

# Converting all names to lower first to verify.
df1.loc[msk, 'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name']= df1.loc[msk,'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'].apply(lambda x: x.lower())
df1['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'].nunique()

655

In [111]:
df1['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name'].describe(include=all)

count             1028472
unique                655
top       modernatx, inc.
freq               319317
Name: Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name, dtype: object

In [112]:
df1[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name']]

        Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name
0                                          argenx us, inc.
1                                jazz pharmaceuticals inc.
2                                             insmed, inc.
3                                              abbvie inc.
4                    bayer healthcare pharmaceuticals inc.
...                                                    ...
1028467                              glaxosmithkline, llc.
1028468                                    novo nordisk as
1028469                                    novo nordisk as
1028470                           heron therapeutics, inc.
1028471                       alnylam pharmaceuticals inc.

[1028472 rows x 1 columns]

In [113]:
df1[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name']].nunique()

Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name    655
dtype: int64

In [114]:
df1[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name']].value_counts(dropna=False)

Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name
modernatx, inc.                                              319317
novo nordisk as                                               85597
pfizer inc.                                                   58364
genentech, inc.                                               38223
abbvie inc.                                                   31536
                                                              ...
modulated imaging, inc.                                           1
mis implants technologies, inc.                                   1
linkbio corp                                                      1
kulzer, llc                                                       1
zyla life sciences, inc.                                          1
Name: count, Length: 655, dtype: int64

In [115]:
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID'].nunique()

692

In [116]:
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID'].value_counts(dropna=False)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID
100000961851    319317
100000000163     85597
100000000286     37660
100000000204     31536
100000481817     30311
                 ...
100000010592         1
100000011000         1
100000005642         1
100000226810         1
100000010673         1
Name: count, Length: 692, dtype: int64

In [117]:
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].nunique()

701

In [118]:
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name']

0                                ARGENX US, INC.
1                      JAZZ PHARMACEUTICALS INC.
2                                   Insmed, Inc.
3                                    AbbVie Inc.
4          Bayer Healthcare Pharmaceuticals Inc.
                           ...
1028467                    GlaxoSmithKline, LLC.
1028468                          Novo Nordisk AS
1028469                          Novo Nordisk AS
1028470                 Heron Therapeutics, Inc.
1028471             Alnylam Pharmaceuticals Inc.
Name: Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name, Length: 1028472, dtype: object

In [119]:
# To avoid nan getting converted to string. submitting applicable manufacturer GPO name
msk = df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].notna()
df1.loc[msk, 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'] = df1.loc[msk, 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].astype(str)

# Converting all names to lower first to verify.
df1.loc[msk, 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name']= df1.loc[msk,'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].apply(lambda x: x.lower())
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].nunique()

692

In [120]:
# Mapping the ID and names of manufacturin / GPO 
df1[['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID', 'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name']].nunique()

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID      692
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name    692
dtype: int64

In [121]:
df1[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name',
       'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID',
       'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name']].nunique()

Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name        655
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID      692
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name    692
dtype: int64

In [122]:
# Taking id list to check each ID variations
manuf_gpo_id_list=df1.Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID.unique()

# Identifying ID with more than one unique names to standardize them
id_list=[]
for i in manuf_gpo_id_list:
    if df1[df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID']==i]['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].nunique() > 1:
        id_list.append(i)
print('Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name', id_list)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name [100000151638]

In [123]:
df1[df1.Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID==100000151638]['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name']

34633     ascendis pharma inc
37973     ascendis pharma inc
38513     ascendis pharma inc
39969     ascendis pharma inc
390211     vifor pharma, inc.
396707     vifor pharma, inc.
404275     vifor pharma, inc.
410153     vifor pharma, inc.
417169     vifor pharma, inc.
425767     vifor pharma, inc.
433099     vifor pharma, inc.
Name: Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name, dtype: object

### For ID 100000151638 the companies are ascendis and vifor, which are not in our list of analysis, hence we will currently do not worry about tis ID.

In [124]:
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].value_counts(dropna=False)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name
modernatx, inc.                          319317
novo nordisk as                           85597
pfizer inc.                               37660
abbvie inc.                               31536
alnylam pharmaceuticals inc.              30311
                                          ...
olea medical                                  1
kulzer, llc                                   1
applied medical resources corporation         1
ibsa pharma inc.                              1
dentsply llc                                  1
Name: count, Length: 692, dtype: int64

In [125]:
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State'].describe()

count     896932
unique        34
top           MA
freq      423185
Name: Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State, dtype: object

In [126]:
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State'].value_counts(dropna=False)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State
MA     423185
NaN    131540
NJ     110097
CA      88972
NY      73871
IL      46098
PA      33285
DE      28024
IN      15742
WA      14778
MN      12123
TX       9777
OR       7838
MD       7669
NC       7081
FL       4986
CO       2025
MI       1776
CT       1711
VA       1519
OH       1478
TN        926
DC        834
AZ        761
NH        677
WV        429
GA        294
WI        202
UT        179
NV        178
MO        156
PR        114
RI         88
KY         35
SC         24
Name: count, dtype: int64

In [127]:
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country'].describe()

count           1028472
unique               20
top       United States
freq             896932
Name: Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country, dtype: object

In [128]:
df1['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country'].value_counts(dropna=False)

Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country
United States          896932
Denmark                 93859
Great Britain (Uk)       6772
Germany                  6702
Switzerland              6281
Cayman Islands           5469
France                   2423
Japan                    2252
Bermuda                  2178
Canada                   2123
Belgium                  1252
Australia                 596
Ireland                   481
Austria                   408
Israel                    285
Sweden                    183
Italy                     139
Netherlands               125
New Zealand                11
Korea (Republic of)         1
Name: count, dtype: int64

In [129]:
# verifying after lower case conversion

df1[['Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name',
    'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID',
    'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name', 
    'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State',
    'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country']].describe()

,Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country
count,1028472,1028472,1028472,896932,1028472
unique,655,692,692,34,20
top,"modernatx, inc.",100000961851,"modernatx, inc.",MA,United States
freq,319317,319317,319317,423185,896932

Product Indicator

In [130]:
df1[['Related_Product_Indicator', 'Covered_or_Noncovered_Indicator_1',
    'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1', 'Product_Category_or_Therapeutic_Area_1',
    'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1', 'Associated_Drug_or_Biological_NDC_1',
    'Associated_Device_or_Medical_Supply_PDI_1', 'Covered_or_Noncovered_Indicator_2']].describe()

,Related_Product_Indicator,Covered_or_Noncovered_Indicator_1,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1,Product_Category_or_Therapeutic_Area_1,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1,Associated_Drug_or_Biological_NDC_1,Associated_Device_or_Medical_Supply_PDI_1,Covered_or_Noncovered_Indicator_2
count,1028472,893264,489314,489734,481012,398547,59677,24735
unique,2,2,4,757,1906,746,878,2
top,Yes,Covered,Drug,Infections and Infectious Diseases,Moderna Covid-19 Vaccine,80777-273-99,04035479118266,Covered
freq,893264,474072,232206,86849,86841,86841,3480,17902

In [131]:
df1[['Related_Product_Indicator', 'Covered_or_Noncovered_Indicator_1',
    'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1', 'Product_Category_or_Therapeutic_Area_1',
    'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1', 'Associated_Drug_or_Biological_NDC_1',
    'Associated_Device_or_Medical_Supply_PDI_1']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 7 columns):
 #   Column                                                     Non-Null Count    Dtype
---  ------                                                     --------------    -----
 0   Related_Product_Indicator                                  1028472 non-null  object
 1   Covered_or_Noncovered_Indicator_1                          893264 non-null   object
 2   Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1  489314 non-null   object
 3   Product_Category_or_Therapeutic_Area_1                     489734 non-null   object
 4   Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1   481012 non-null   object
 5   Associated_Drug_or_Biological_NDC_1                        398547 non-null   object
 6   Associated_Device_or_Medical_Supply_PDI_1                  59677 non-null    object
dtypes: object(7)
memory usage: 54.9+ MB

In [132]:
df1['Related_Product_Indicator'].value_counts(dropna=False)

Related_Product_Indicator
Yes    893264
No     135208
Name: count, dtype: int64

In [133]:
df1['Covered_or_Noncovered_Indicator_1'].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_1
Covered        474072
Non-Covered    419192
NaN            135208
Name: count, dtype: int64

In [134]:
df1['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1'].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1
NaN               539158
Drug              232206
Biological        177653
Device             79010
Medical Supply       445
Name: count, dtype: int64

In [135]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Product_Category_or_Therapeutic_Area_1'].notna()
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_1'] = df1.loc[msk, 'Product_Category_or_Therapeutic_Area_1'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_1']= df1.loc[msk,'Product_Category_or_Therapeutic_Area_1'].apply(lambda x: x.lower())
df1['Product_Category_or_Therapeutic_Area_1'].nunique()

700

In [136]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].describe()

count                       481012
unique                        1906
top       Moderna Covid-19 Vaccine
freq                         86841
Name: Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1, dtype: object

In [137]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].notna()
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'] = df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1']= df1.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].apply(lambda x: x.lower())
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].nunique()

1861

In [138]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1
NaN                               547460
moderna covid-19 vaccine           86841
ozempic                            28972
wegovy                             28258
rybelsus                           18939
                                   ...
icotec blackarmor spine system         1
juggerloc                              1
lc bead 100-300                        1
affirm prone biopsy system             1
stealth autoguide system               1
Name: count, Length: 1862, dtype: int64

In [139]:
df1['Associated_Drug_or_Biological_NDC_1'].describe()

count           398547
unique             746
top       80777-273-99
freq             86841
Name: Associated_Drug_or_Biological_NDC_1, dtype: object

In [140]:
df1['Associated_Drug_or_Biological_NDC_1'].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_1
NaN             629925
80777-273-99     86841
0169-4132-12     28972
0169-4525-14     28258
0169-4303-13     18939
                 ...
44206-452-02         1
61958-0401-1         1
53329-945-29         1
67919-020-10         1
24208-377-01         1
Name: count, Length: 747, dtype: int64

In [141]:
df1['Associated_Device_or_Medical_Supply_PDI_1'].describe()

count              59677
unique               878
top       04035479118266
freq                3480
Name: Associated_Device_or_Medical_Supply_PDI_1, dtype: object

In [142]:
df1['Associated_Device_or_Medical_Supply_PDI_1'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1028472 entries, 0 to 1028471
Series name: Associated_Device_or_Medical_Supply_PDI_1
Non-Null Count  Dtype
--------------  -----
59677 non-null  object
dtypes: object(1)
memory usage: 7.8+ MB

In [143]:
df1['Associated_Device_or_Medical_Supply_PDI_1'].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_1
NaN               968795
04035479118266      3480
00850291007000      3261
05425025750504      2492
00855547005267      2372
                   ...
03596010603272         1
08022057013644         1
10886982250452         1
00850031897014         1
00763000293659         1
Name: count, Length: 879, dtype: int64

In [144]:
# reverify after lower case conversion

df1[['Related_Product_Indicator', 'Covered_or_Noncovered_Indicator_1',
    'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1', 'Product_Category_or_Therapeutic_Area_1',
    'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1', 'Associated_Drug_or_Biological_NDC_1',
    'Associated_Device_or_Medical_Supply_PDI_1']].describe()

,Related_Product_Indicator,Covered_or_Noncovered_Indicator_1,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1,Product_Category_or_Therapeutic_Area_1,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1,Associated_Drug_or_Biological_NDC_1,Associated_Device_or_Medical_Supply_PDI_1
count,1028472,893264,489314,489734,481012,398547,59677
unique,2,2,4,700,1861,746,878
top,Yes,Covered,Drug,infections and infectious diseases,moderna covid-19 vaccine,80777-273-99,04035479118266
freq,893264,474072,232206,86849,86841,86841,3480

In [145]:
df1[['Covered_or_Noncovered_Indicator_2','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2',
    'Product_Category_or_Therapeutic_Area_2', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2',
    'Associated_Drug_or_Biological_NDC_2', 'Associated_Device_or_Medical_Supply_PDI_2']].describe()

,Covered_or_Noncovered_Indicator_2,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2,Product_Category_or_Therapeutic_Area_2,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2,Associated_Drug_or_Biological_NDC_2,Associated_Device_or_Medical_Supply_PDI_2
count,24735,18188,18172,17995,9376,7824
unique,2,4,151,278,88,162
top,Covered,Device,Cardiology/Vascular Diseases,Susvimo,50242-078-12,00643169711761
freq,17902,8592,4147,1592,1592,1337

In [146]:
df1[['Covered_or_Noncovered_Indicator_2','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2',
    'Product_Category_or_Therapeutic_Area_2', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2',
    'Associated_Drug_or_Biological_NDC_2', 'Associated_Device_or_Medical_Supply_PDI_2']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Covered_or_Noncovered_Indicator_2                          24735 non-null  object
 1   Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2  18188 non-null  object
 2   Product_Category_or_Therapeutic_Area_2                     18172 non-null  object
 3   Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2   17995 non-null  object
 4   Associated_Drug_or_Biological_NDC_2                        9376 non-null   object
 5   Associated_Device_or_Medical_Supply_PDI_2                  7824 non-null   object
dtypes: object(6)
memory usage: 47.1+ MB

In [147]:
df1['Covered_or_Noncovered_Indicator_2'].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_2
NaN            1003737
Covered          17902
Non-Covered       6833
Name: count, dtype: int64

In [148]:
df1['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2'].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2
NaN               1010284
Device               8592
Drug                 5938
Biological           3656
Medical Supply          2
Name: count, dtype: int64

In [149]:
df1[['Product_Category_or_Therapeutic_Area_2']].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_2
NaN                                       1010300
Cardiology/Vascular Diseases                 4147
BioOncology                                  3481
Immunology and Ophthalmology                 1592
Pacemakers                                   1337
                                           ...
Kryptor instrument consumables                  1
ROBOTICS                                        1
Kyphoplasty                                     1
MICROCATHETERSTENTRIEVER                        1
Expandable Cage                                 1
Name: count, Length: 152, dtype: int64

In [150]:
df1['Product_Category_or_Therapeutic_Area_2']=df1['Product_Category_or_Therapeutic_Area_2'].astype(object)

msk = df1['Product_Category_or_Therapeutic_Area_2'].notna()
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_2'] = df1.loc[msk, 'Product_Category_or_Therapeutic_Area_2'].astype(str)
# Converting all names to lower first to verify. 
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_2']= df1.loc[msk,'Product_Category_or_Therapeutic_Area_2'].apply(lambda x: x.lower())
df1['Product_Category_or_Therapeutic_Area_2'].nunique()

144

In [151]:
df1[['Product_Category_or_Therapeutic_Area_2']].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_2
NaN                                       1010300
cardiology/vascular diseases                 4147
biooncology                                  3481
oncology                                     1903
immunology and ophthalmology                 1592
                                           ...
orthopedics                                     1
robotics                                        1
spine hardware systems                          1
bone conduction implant kit                     1
kryptor instrument consumables                  1
Name: count, Length: 145, dtype: int64

In [152]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2
NaN                            1010477
Susvimo                           1592
MICRA                             1337
Sentus                             900
Solia                              874
                                ...
PIQRAY                               1
AcrySof IQ PanOptix UV IOL           1
Integra Wound Matrix (Thin)          1
SURGIMEND                            1
T3                                   1
Name: count, Length: 279, dtype: int64

In [153]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].notna()
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'] = df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2']= df1.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].apply(lambda x: x.lower())
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].nunique()

275

In [154]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2
NaN                                               1010477
susvimo                                              1592
micra                                                1337
sentus                                                900
solia                                                 874
                                                   ...
inlyta                                                  1
sublime 014 rx pta balloon dilatation catheter          1
sublime microcatheter, 014, 65cm, straight              1
healix advance dyna+tape permatape dynacord             1
t3                                                      1
Name: count, Length: 276, dtype: int64

In [155]:
df1['Associated_Drug_or_Biological_NDC_2'].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_2
NaN             1019096
50242-078-12       1592
50242-917-01        755
0006-3026-02        663
50242-070-01        572
                 ...
0069-0550-38          1
0069-0145-01          1
0049-3440-19          1
0006-5007-01          1
0078-0701-84          1
Name: count, Length: 89, dtype: int64

In [156]:
df1['Associated_Device_or_Medical_Supply_PDI_2'].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_2
NaN               1020648
00643169711761       1337
04035479148942        900
04035479118266        874
04035479156794        802
                   ...
00887868245022          1
00888867039865          1
10381780357391          1
08022057013576          1
00844868046868          1
Name: count, Length: 163, dtype: int64

In [157]:
# Reverify after converion to lower case
df1[['Covered_or_Noncovered_Indicator_2','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2',
    'Product_Category_or_Therapeutic_Area_2', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2',
    'Associated_Drug_or_Biological_NDC_2', 'Associated_Device_or_Medical_Supply_PDI_2']].describe()

,Covered_or_Noncovered_Indicator_2,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2,Product_Category_or_Therapeutic_Area_2,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2,Associated_Drug_or_Biological_NDC_2,Associated_Device_or_Medical_Supply_PDI_2
count,24735,18188,18172,17995,9376,7824
unique,2,4,144,275,88,162
top,Covered,Device,cardiology/vascular diseases,susvimo,50242-078-12,00643169711761
freq,17902,8592,4147,1592,1592,1337

In [158]:
df1[['Covered_or_Noncovered_Indicator_3','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3',
    'Product_Category_or_Therapeutic_Area_3', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3',
    'Associated_Drug_or_Biological_NDC_3', 'Associated_Device_or_Medical_Supply_PDI_3']].describe()

,Covered_or_Noncovered_Indicator_3,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3,Product_Category_or_Therapeutic_Area_3,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3,Associated_Drug_or_Biological_NDC_3,Associated_Device_or_Medical_Supply_PDI_3
count,10147,9302,9301,9213,2871,6138
unique,2,4,77,124,37,70
top,Covered,Device,Cardiology/Vascular Diseases,SELECTSECURE,65757-654-42,00643169535848
freq,9159,6335,3785,1337,454,1337

In [159]:
df1[['Covered_or_Noncovered_Indicator_3','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3',
    'Product_Category_or_Therapeutic_Area_3', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3',
    'Associated_Drug_or_Biological_NDC_3', 'Associated_Device_or_Medical_Supply_PDI_3']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Covered_or_Noncovered_Indicator_3                          10147 non-null  object
 1   Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3  9302 non-null   object
 2   Product_Category_or_Therapeutic_Area_3                     9301 non-null   object
 3   Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3   9213 non-null   object
 4   Associated_Drug_or_Biological_NDC_3                        2871 non-null   object
 5   Associated_Device_or_Medical_Supply_PDI_3                  6138 non-null   object
dtypes: object(6)
memory usage: 47.1+ MB

In [160]:
df1['Covered_or_Noncovered_Indicator_3'].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_3
NaN            1018325
Covered           9159
Non-Covered        988
Name: count, dtype: int64

In [161]:
df1['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3'].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3
NaN               1019170
Device               6335
Biological           1664
Drug                 1299
Medical Supply          4
Name: count, dtype: int64

In [162]:
df1['Product_Category_or_Therapeutic_Area_3'].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_3
NaN                                        1019171
Cardiology/Vascular Diseases                  3785
BioOncology                                   1640
Leads                                         1337
CNS                                            478
                                            ...
Endoscope and Supplies                           1
Thoracolumbosacral Pedicle Screw System          1
CRANIOMAXILLOFACIAL                              1
Antiepileptic                                    1
KNEES                                            1
Name: count, Length: 78, dtype: int64

In [163]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Product_Category_or_Therapeutic_Area_3'].notna()
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_3'] = df1.loc[msk, 'Product_Category_or_Therapeutic_Area_3'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_3']= df1.loc[msk,'Product_Category_or_Therapeutic_Area_3'].apply(lambda x: x.lower())
df1['Product_Category_or_Therapeutic_Area_3'].nunique()

77

In [164]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3
NaN                                                    1019259
SELECTSECURE                                              1337
Sentus                                                    1109
Plexa ProMRI                                              1107
Rivacor 7 DR-T                                            1021
                                                        ...
PATIENT-FITTED TMJ RECONSTRUCTIVE PROSTHESIS SYSTEM          1
Lacosamide                                                   1
SHOULDER IMPLANTS CORKSCREWS PEEK ANCHORS                    1
Nucynta                                                      1
TRIATHLON                                                    1
Name: count, Length: 125, dtype: int64

In [165]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].notna()
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'] = df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3']= df1.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].apply(lambda x: x.lower())
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].nunique()

122

In [166]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3
NaN                                                    1019259
selectsecure                                              1337
sentus                                                    1109
plexa promri                                              1107
rivacor 7 dr-t                                            1021
                                                        ...
patient-fitted tmj reconstructive prosthesis system          1
lacosamide                                                   1
shoulder implants corkscrews peek anchors                    1
nucynta                                                      1
triathlon                                                    1
Name: count, Length: 123, dtype: int64

In [167]:
df1['Associated_Drug_or_Biological_NDC_3'].describe()

count             2871
unique              37
top       65757-654-42
freq               454
Name: Associated_Drug_or_Biological_NDC_3, dtype: object

In [168]:
df1['Associated_Drug_or_Biological_NDC_3'].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_3
NaN             1025601
65757-654-42        454
50242-917-01        409
66887-001-05        395
50242-159-01        343
50242-070-01        257
50242-087-01        229
50242-717-01        164
50242-053-06        133
50242-105-01        103
50242-096-01         68
0074-0579-28         68
0006-5331-01         45
62856-712-30         39
50242-090-02         30
65757-403-03         19
50242-091-30         16
50242-145-01         15
0069-8141-20         14
50242-245-01         12
70255-010-02         10
70363-011-30          7
0054-0390-41          6
65757-653-42          5
0069-0809-01          5
50242-132-01          5
0409-1638-02          3
0069-0197-30          3
70255-025-01          3
0078-1007-68          2
0054-0235-25          2
69842-935-10          1
0069-1305-10          1
69865-210-02          1
0054-0283-25          1
0069-0145-01          1
0049-0114-28          1
0008-1179-01          1
Name: count, dtype: int64

In [169]:
df1['Associated_Device_or_Medical_Supply_PDI_3'].describe()

count               6138
unique                70
top       00643169535848
freq                1337
Name: Associated_Device_or_Medical_Supply_PDI_3, dtype: object

In [170]:
df1['Associated_Device_or_Medical_Supply_PDI_3'].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_3
NaN               1022334
00643169535848       1337
04035479148942       1109
04035479140014       1107
04035479156794       1021
                   ...
07613327626582          1
05391525786377          1
05391525785165          1
10887587032726          1
07613327041620          1
Name: count, Length: 71, dtype: int64

In [171]:
# Reverify after lower case conversion

df1[['Covered_or_Noncovered_Indicator_3','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3',
    'Product_Category_or_Therapeutic_Area_3', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3',
    'Associated_Drug_or_Biological_NDC_3', 'Associated_Device_or_Medical_Supply_PDI_3']].describe()

,Covered_or_Noncovered_Indicator_3,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3,Product_Category_or_Therapeutic_Area_3,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3,Associated_Drug_or_Biological_NDC_3,Associated_Device_or_Medical_Supply_PDI_3
count,10147,9302,9301,9213,2871,6138
unique,2,4,77,122,37,70
top,Covered,Device,cardiology/vascular diseases,selectsecure,65757-654-42,00643169535848
freq,9159,6335,3785,1337,454,1337

In [172]:
df1[['Covered_or_Noncovered_Indicator_4','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Product_Category_or_Therapeutic_Area_4', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Associated_Drug_or_Biological_NDC_4', 'Associated_Device_or_Medical_Supply_PDI_4']].describe(include=object)

,Covered_or_Noncovered_Indicator_4,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4,Product_Category_or_Therapeutic_Area_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Associated_Drug_or_Biological_NDC_4
count,7671,7376,7375,7360,1408
unique,2,4,45,73,14
top,Covered,Device,Cardiology/Vascular Diseases,CAPSURE SENSE,65757-651-42
freq,7355,5949,3785,1337,454

In [173]:
df1['Associated_Device_or_Medical_Supply_PDI_4']=df1['Associated_Device_or_Medical_Supply_PDI_4'].astype(object)

In [174]:
df1['Covered_or_Noncovered_Indicator_4'].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_4
NaN            1020801
Covered           7355
Non-Covered        316
Name: count, dtype: int64

In [175]:
df1['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4'].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4
NaN               1021096
Device               5949
Biological            885
Drug                  538
Medical Supply          4
Name: count, dtype: int64

In [176]:
  df1['Product_Category_or_Therapeutic_Area_4'].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_4
NaN                                                                1021097
Cardiology/Vascular Diseases                                          3785
Leads                                                                 1337
BioOncology                                                            701
CNS                                                                    478
OPHTHALMOLOGY                                                          391
Aortic Stent Grafts                                                    179
BioOncology/Immunology                                                 177
ONCOLOGY                                                                63
Sports Surgical                                                         52
Stents                                                                  46
Ortho-Hip                                                               38
Ortho-Knee                                                              21
CARDIAC SURGERY                                                         20
Orthopedics                                                             10
HIPS                                                                     8
Wound Care                                                               6
TRAUMA & EXTREMITIES                                                     6
Device                                                                   6
Sports_Surgical                                                          6
Shoulder - Instruments - Anchor Specific Instruments - FiberTak          4
Spine/Spine Surgery                                                      4
Dialysis Catheters                                                       3
Thoracolumbosacral Pedicle Screw System                                  3
Endoscope and Accessories                                                3
Shoulder - Suture - FiberWire - #2 FiberWire                             3
ULTRASOUND                                                               2
Wound Closure                                                            2
Ortho-Shoulder                                                           2
Imaging & Resection - Equipment - Video - Camera Systems                 2
Vascular Surgery                                                         2
Shoulder - Instruments - Anchor Specific Instruments                     1
MEDICAL SUPPLIES                                                         1
MIS Screws                                                               1
Cardiology                                                               1
Antiepileptic                                                            1
INFECTIOUS DISEASES                                                      1
JOINT REPLACEMENT HIPS, KNEES                                            1
Percutaneous Catheter                                                    1
Vascular Microcatheter                                                   1
Spine Hardware Systems                                                   1
CRANIOMAXILLOFACIAL                                                      1
INFLAMMATION                                                             1
Surgical Prep                                                            1
Diagnostic medical imaging software                                      1
Orthopedic                                                               1
Name: count, dtype: int64

In [177]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Product_Category_or_Therapeutic_Area_4'].notna()
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_4'] = df1.loc[msk, 'Product_Category_or_Therapeutic_Area_4'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_4']= df1.loc[msk,'Product_Category_or_Therapeutic_Area_4'].apply(lambda x: x.lower())
df1['Product_Category_or_Therapeutic_Area_4'].nunique()

45

In [178]:
  df1['Product_Category_or_Therapeutic_Area_4'].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_4
NaN                                                                1021097
cardiology/vascular diseases                                          3785
leads                                                                 1337
biooncology                                                            701
cns                                                                    478
ophthalmology                                                          391
aortic stent grafts                                                    179
biooncology/immunology                                                 177
oncology                                                                63
sports surgical                                                         52
stents                                                                  46
ortho-hip                                                               38
ortho-knee                                                              21
cardiac surgery                                                         20
orthopedics                                                             10
hips                                                                     8
wound care                                                               6
trauma & extremities                                                     6
device                                                                   6
sports_surgical                                                          6
shoulder - instruments - anchor specific instruments - fibertak          4
spine/spine surgery                                                      4
dialysis catheters                                                       3
thoracolumbosacral pedicle screw system                                  3
endoscope and accessories                                                3
shoulder - suture - fiberwire - #2 fiberwire                             3
ultrasound                                                               2
wound closure                                                            2
ortho-shoulder                                                           2
imaging & resection - equipment - video - camera systems                 2
vascular surgery                                                         2
shoulder - instruments - anchor specific instruments                     1
medical supplies                                                         1
mis screws                                                               1
cardiology                                                               1
antiepileptic                                                            1
infectious diseases                                                      1
joint replacement hips, knees                                            1
percutaneous catheter                                                    1
vascular microcatheter                                                   1
spine hardware systems                                                   1
craniomaxillofacial                                                      1
inflammation                                                             1
surgical prep                                                            1
diagnostic medical imaging software                                      1
orthopedic                                                               1
Name: count, dtype: int64

In [179]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4
NaN                                                     1021112
CAPSURE SENSE                                              1337
Rivacor 7 DR-T                                              925
Sentus                                                      865
Plexa ProMRI                                                812
                                                         ...
Levetiracetam                                                 1
Sublime Microcatheter, 014, 65cm, Angle                       1
Sublime Radial Access 018 RX PTA Dilatation Catheter          1
SHOULDER INSTRUMENTS ANCHOR SPECIFIC INSTRUMENTS              1
X3                                                            1
Name: count, Length: 74, dtype: int64

In [180]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].notna()
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'] = df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4']= df1.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].apply(lambda x: x.lower())
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].nunique()

73

In [181]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4
NaN                                                     1021112
capsure sense                                              1337
rivacor 7 dr-t                                              925
sentus                                                      865
plexa promri                                                812
                                                         ...
levetiracetam                                                 1
sublime microcatheter, 014, 65cm, angle                       1
sublime radial access 018 rx pta dilatation catheter          1
shoulder instruments anchor specific instruments              1
x3                                                            1
Name: count, Length: 74, dtype: int64

In [182]:
df1['Associated_Drug_or_Biological_NDC_4'].describe()

count             1408
unique              14
top       65757-651-42
freq               454
Name: Associated_Drug_or_Biological_NDC_4, dtype: object

In [183]:
df1['Associated_Drug_or_Biological_NDC_4'].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_4
NaN             1027064
65757-651-42        454
50242-917-01        275
50242-091-30        236
50242-053-06        177
50242-105-01        173
62856-712-30         45
65757-404-03         19
50242-090-02         12
65757-654-42          5
50242-145-01          5
70255-025-01          4
0069-0319-01          1
0049-3170-30          1
17518-060-04          1
Name: count, dtype: int64

In [184]:
df1['Associated_Device_or_Medical_Supply_PDI_4'].describe()

count     5.941000e+03
unique    5.300000e+01
top       6.431696e+11
freq      1.337000e+03
Name: Associated_Device_or_Medical_Supply_PDI_4, dtype: float64

In [185]:
df1['Associated_Device_or_Medical_Supply_PDI_4'].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_4
NaN                 1022531
643169590519.0         1337
4035479156794.0         925
4035479148942.0         865
4035479140014.0         812
4035479118266.0         786
4035479156701.0         397
818806020029.0          353
643169439979.0          179
613994798497.0           46
10886705024117.0         24
8022057012913.0          20
818806020678.0           20
10818806020019.0         18
10603295077503.0         14
10603295250777.0         12
10886705008605.0         10
10886705020393.0          9
10886705026043.0          9
10886705030873.0          8
10603295060147.0          8
10603295016779.0          8
10603295149941.0          8
10886705009183.0          7
20886705030016.0          6
7332551971793.0           6
846832060795.0            4
4546540153210.0           4
20884521009858.0          3
18257200140992.0          3
888867041264.0            3
18257200122462.0          3
18257200114832.0          3
10886705022311.0          2
843152103003.0            2
10705031203525.0          2
888867351189.0            2
10886705027972.0          2
10886705027002.0          2
840682146883.0            2
7613327039979.0           2
887517701084.0            2
887517400444.0            2
846832067824.0            1
4546540608291.0           1
10381780031604.0          1
840420120298.0            1
4546540073952.0           1
850031897021.0            1
812339030562.0            1
5391525786377.0           1
10846835009439.0          1
7613327626650.0           1
7613327025743.0           1
Name: count, dtype: int64

In [186]:
# reverify after lower case conversion

df1[['Covered_or_Noncovered_Indicator_4','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Product_Category_or_Therapeutic_Area_4', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4',
    'Associated_Drug_or_Biological_NDC_4', 'Associated_Device_or_Medical_Supply_PDI_4']].describe(include=object)

,Covered_or_Noncovered_Indicator_4,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4,Product_Category_or_Therapeutic_Area_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Associated_Drug_or_Biological_NDC_4,Associated_Device_or_Medical_Supply_PDI_4
count,7671,7376,7375,7360,1408,5.941000e+03
unique,2,4,45,73,14,5.300000e+01
top,Covered,Device,cardiology/vascular diseases,capsure sense,65757-651-42,6.431696e+11
freq,7355,5949,3785,1337,454,1.337000e+03

In [187]:
df1[['Covered_or_Noncovered_Indicator_5','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5',
    'Product_Category_or_Therapeutic_Area_5', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5',
    'Associated_Drug_or_Biological_NDC_5', 'Associated_Device_or_Medical_Supply_PDI_5']].describe(include=object)

,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5
count,6258,6226,6226,6226,502
unique,2,3,22,38,9
top,Covered,Device,Cardiology/Vascular Diseases,COBALT DR MRI SURESCAN,50242-917-01
freq,6226,5724,3785,1337,248

In [188]:
df1['Associated_Device_or_Medical_Supply_PDI_5']=df1['Associated_Device_or_Medical_Supply_PDI_5'].astype(object)

In [189]:
df1['Covered_or_Noncovered_Indicator_5'].value_counts(dropna=False)

Covered_or_Noncovered_Indicator_5
NaN            1022214
Covered           6226
Non-Covered         32
Name: count, dtype: int64

In [190]:
df1['Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5'].value_counts(dropna=False)

Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5
NaN           1022246
Device           5724
Biological        442
Drug               60
Name: count, dtype: int64

In [191]:
df1['Product_Category_or_Therapeutic_Area_5'].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_5
NaN                                                                       1022246
Cardiology/Vascular Diseases                                                 3785
Implantable Cardioverter Defibrillators (ICDs)                               1337
BioOncology                                                                   489
OPHTHALMOLOGY                                                                 391
Aortic Stent Grafts                                                           179
CNS                                                                             9
HIPS                                                                            6
Shoulder - Instruments - Cannulas - Passport                                    4
ONCOLOGY                                                                        4
Spine/Spine Surgery                                                             4
Dialysis Catheters                                                              3
Vascular Surgery                                                                2
Shoulder - Suture - FiberWire - Specialty                                       2
Distal Extremities - Implants - Soft Tissue - IB Ligament Augmentation          2
TRAUMA & EXTREMITIES                                                            2
Percutaneous Catheter                                                           1
Vascular Microcatheter                                                          1
Shoulder - Suture - FiberWire - #5 FiberWire                                    1
Appliance, Fixation, Spinal Intervertebral Body                                 1
Spine Hardware Systems                                                          1
Negative Pressure Systems & Dressings                                           1
KNEES                                                                           1
Name: count, dtype: int64

In [192]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Product_Category_or_Therapeutic_Area_5'].notna()
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_5'] = df1.loc[msk, 'Product_Category_or_Therapeutic_Area_5'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Product_Category_or_Therapeutic_Area_5']= df1.loc[msk,'Product_Category_or_Therapeutic_Area_5'].apply(lambda x: x.lower())
df1['Product_Category_or_Therapeutic_Area_5'].nunique()

22

In [193]:
df1['Product_Category_or_Therapeutic_Area_5'].value_counts(dropna=False)

Product_Category_or_Therapeutic_Area_5
NaN                                                                       1022246
cardiology/vascular diseases                                                 3785
implantable cardioverter defibrillators (icds)                               1337
biooncology                                                                   489
ophthalmology                                                                 391
aortic stent grafts                                                           179
cns                                                                             9
hips                                                                            6
shoulder - instruments - cannulas - passport                                    4
oncology                                                                        4
spine/spine surgery                                                             4
dialysis catheters                                                              3
vascular surgery                                                                2
shoulder - suture - fiberwire - specialty                                       2
distal extremities - implants - soft tissue - ib ligament augmentation          2
trauma & extremities                                                            2
percutaneous catheter                                                           1
vascular microcatheter                                                          1
shoulder - suture - fiberwire - #5 fiberwire                                    1
appliance, fixation, spinal intervertebral body                                 1
spine hardware systems                                                          1
negative pressure systems & dressings                                           1
knees                                                                           1
Name: count, dtype: int64

In [194]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
NaN                                                                 1022246
COBALT DR MRI SURESCAN                                                 1337
Acticor 7 VR-T DX                                                      1283
Solia                                                                   860
Plexa ProMRI                                                            740
Rivacor 7 DR-T                                                          726
RXSIGHT LIGHT ADJUSTABLE LENS (RXLAL)                                   354
Tecentriq                                                               248
VALIANT CAPTIVIA                                                        179
Polivy                                                                  177
Sentus                                                                  176
Xeloda                                                                   47
RXSIGHT LIGHT DELIVERY DEVICE (LDD)                                      22
RXSIGHT INJECTOR CARTRIDGE                                               14
Avastin                                                                  12
LYBALVI                                                                   6
Phesgo                                                                    5
TRIDENT                                                                   5
LORBRENA                                                                  4
Arthrex                                                                   4
ARISTADA INITIO                                                           3
ARGYLE                                                                    3
DISTAL EXTREMITIES IMPLANTS SOFT TISSUE IB LIGAMENT AUGMENTATION          2
COALESCE                                                                  2
SHOULDER SUTURE FIBERWIRE SPECIALTY                                       2
IOPS                                                                      2
Regatta                                                                   1
COHERE                                                                    1
CoRoent                                                                   1
PREVENA                                                                   1
Sublime Microcatheter, 014, 65cm, Straight                                1
TRITANIUM                                                                 1
AEQUALIS PERFORM                                                          1
Sublime 014 Rx PTA Balloon Dilatation Catheter                            1
SHOULDER SUTURE FIBERWIRE #5 FIBERWIRE                                    1
NewPort                                                                   1
AEQUALIS PERFORM+                                                         1
RXSIGHT CONTACT LENS                                                      1
TRIATHLON                                                                 1
Name: count, dtype: int64

In [195]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].notna()
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'] = df1.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5']= df1.loc[msk,'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].apply(lambda x: x.lower())
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].nunique()

38

In [196]:
df1['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5'].value_counts(dropna=False)

Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
NaN                                                                 1022246
cobalt dr mri surescan                                                 1337
acticor 7 vr-t dx                                                      1283
solia                                                                   860
plexa promri                                                            740
rivacor 7 dr-t                                                          726
rxsight light adjustable lens (rxlal)                                   354
tecentriq                                                               248
valiant captivia                                                        179
polivy                                                                  177
sentus                                                                  176
xeloda                                                                   47
rxsight light delivery device (ldd)                                      22
rxsight injector cartridge                                               14
avastin                                                                  12
lybalvi                                                                   6
phesgo                                                                    5
trident                                                                   5
lorbrena                                                                  4
arthrex                                                                   4
aristada initio                                                           3
argyle                                                                    3
distal extremities implants soft tissue ib ligament augmentation          2
coalesce                                                                  2
shoulder suture fiberwire specialty                                       2
iops                                                                      2
regatta                                                                   1
cohere                                                                    1
coroent                                                                   1
prevena                                                                   1
sublime microcatheter, 014, 65cm, straight                                1
tritanium                                                                 1
aequalis perform                                                          1
sublime 014 rx pta balloon dilatation catheter                            1
shoulder suture fiberwire #5 fiberwire                                    1
newport                                                                   1
aequalis perform+                                                         1
rxsight contact lens                                                      1
triathlon                                                                 1
Name: count, dtype: int64

In [197]:
df1['Associated_Drug_or_Biological_NDC_5'].describe()

count              502
unique               9
top       50242-917-01
freq               248
Name: Associated_Drug_or_Biological_NDC_5, dtype: object

In [198]:
df1['Associated_Drug_or_Biological_NDC_5'].value_counts(dropna=False)

Associated_Drug_or_Biological_NDC_5
NaN             1027970
50242-917-01        248
50242-105-01        177
0004-1101-50         47
50242-061-01         12
65757-651-42          5
50242-245-01          5
0069-0227-01          4
65757-500-03          3
65757-652-42          1
Name: count, dtype: int64

In [199]:
df1['Associated_Device_or_Medical_Supply_PDI_5'].describe()

count     5.719000e+03
unique    2.700000e+01
top       7.630002e+11
freq      1.337000e+03
Name: Associated_Device_or_Medical_Supply_PDI_5, dtype: float64

In [200]:
df1['Associated_Device_or_Medical_Supply_PDI_5']=df1['Associated_Device_or_Medical_Supply_PDI_5'].astype(object)

In [201]:
df1['Associated_Device_or_Medical_Supply_PDI_5'].value_counts(dropna=False)

Associated_Device_or_Medical_Supply_PDI_5
NaN                 1022753
763000178390.0         1337
4035479156701.0        1283
4035479118266.0         860
4035479140014.0         740
4035479156794.0         726
818806020678.0          354
643169347083.0          179
4035479148942.0         176
818806020029.0           22
10818806020019.0         14
4546540073952.0           5
888867040595.0            4
10884521004610.0          3
843152102037.0            2
887517056382.0            2
10889981231293.0          1
887517394125.0            1
849554000032.0            1
887517982742.0            1
3700386937330.0           1
7613327039979.0           1
818806020531.0            1
812339030555.0            1
5391525783680.0           1
10889983163066.0          1
846832061457.0            1
7613327041620.0           1
Name: count, dtype: int64

In [202]:
# reverify

df1[['Covered_or_Noncovered_Indicator_5','Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5',
    'Product_Category_or_Therapeutic_Area_5', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5',
    'Associated_Drug_or_Biological_NDC_5', 'Associated_Device_or_Medical_Supply_PDI_5']].describe(include=object)

,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5,Associated_Device_or_Medical_Supply_PDI_5
count,6258,6226,6226,6226,502,5.719000e+03
unique,2,3,22,38,9,2.700000e+01
top,Covered,Device,cardiology/vascular diseases,cobalt dr mri surescan,50242-917-01,7.630002e+11
freq,6226,5724,3785,1337,248,1.337000e+03

Payment data

In [203]:
df1[['Total_Amount_of_Payment_USDollars', 'Date_of_Payment', 'Form_of_Payment_or_Transfer_of_Value',
   'Expenditure_Category1','Expenditure_Category2','Expenditure_Category3',
    'Expenditure_Category4','Expenditure_Category5']].describe(include=object)

,Date_of_Payment,Form_of_Payment_or_Transfer_of_Value,Expenditure_Category1,Expenditure_Category2,Expenditure_Category3,Expenditure_Category4,Expenditure_Category5
count,1028472,1028472,22096,30,11,11,10
unique,365,3,6,4,2,2,2
top,01/12/2023,Cash or cash equivalent,Patient Care,Other,Patient Care,Non-patient Care,Overhead
freq,34978,871985,13299,9,9,9,9

In [204]:
df1[['Total_Amount_of_Payment_USDollars', 'Date_of_Payment', 'Form_of_Payment_or_Transfer_of_Value',
   'Expenditure_Category1','Expenditure_Category2','Expenditure_Category3',
    'Expenditure_Category4','Expenditure_Category5']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 8 columns):
 #   Column                                Non-Null Count    Dtype
---  ------                                --------------    -----
 0   Total_Amount_of_Payment_USDollars     1028472 non-null  float64
 1   Date_of_Payment                       1028472 non-null  object
 2   Form_of_Payment_or_Transfer_of_Value  1028472 non-null  object
 3   Expenditure_Category1                 22096 non-null    object
 4   Expenditure_Category2                 30 non-null       object
 5   Expenditure_Category3                 11 non-null       object
 6   Expenditure_Category4                 11 non-null       object
 7   Expenditure_Category5                 10 non-null       object
dtypes: float64(1), object(7)
memory usage: 62.8+ MB

In [205]:
df1[['Total_Amount_of_Payment_USDollars']].describe()

       Total_Amount_of_Payment_USDollars
count                       1.028472e+06
mean                        7.896237e+03
std                         7.067015e+04
min                         1.000000e-02
25%                         7.602000e+01
50%                         7.424400e+02
75%                         2.675330e+03
max                         1.360749e+07

In [206]:
df1[['Total_Amount_of_Payment_USDollars']].mean()

Total_Amount_of_Payment_USDollars    7896.237375
dtype: float64

In [207]:
df1['Total_Amount_of_Payment_USDollars'].value_counts(dropna=False)

Total_Amount_of_Payment_USDollars
30.00       12880
19.24       12675
18.23        9958
55.00        8332
20.25        8113
            ...
17496.01        1
304.71          1
14154.24        1
897.94          1
21389.04        1
Name: count, Length: 182851, dtype: int64

In [208]:
df1['Date_of_Payment'].describe()

count        1028472
unique           365
top       01/12/2023
freq           34978
Name: Date_of_Payment, dtype: object

In [209]:
# Converting to date 
df1['Date_of_Payment']= pd.to_datetime(df1['Date_of_Payment'])

In [210]:
# Converting to date 
df1['Date_of_Payment'].describe()

count                          1028472
mean     2023-07-05 12:01:33.921079040
min                2023-01-01 00:00:00
25%                2023-04-03 00:00:00
50%                2023-06-27 00:00:00
75%                2023-10-18 00:00:00
max                2023-12-31 00:00:00
Name: Date_of_Payment, dtype: object

In [211]:
df1['Form_of_Payment_or_Transfer_of_Value'].value_counts(dropna=False)

Form_of_Payment_or_Transfer_of_Value
Cash or cash equivalent       871985
In-kind items and services    156484
Stock                              3
Name: count, dtype: int64

Expenditure category

In [212]:
df1['Expenditure_Category1'].value_counts(dropna=False)

Expenditure_Category1
NaN                                        1006376
Patient Care                                 13299
Non-patient Care                              3765
Professional Salary Support                   2644
Other                                         2237
Overhead                                       106
Medical Research Writing or Publication         45
Name: count, dtype: int64

In [213]:
df1['Expenditure_Category2'].value_counts(dropna=False)

Expenditure_Category2
NaN                                        1028442
Other                                            9
Medical Research Writing or Publication          9
Overhead                                         8
Patient Care                                     4
Name: count, dtype: int64

In [214]:
df1['Expenditure_Category3'].value_counts(dropna=False)

Expenditure_Category3
NaN                 1028461
Patient Care              9
Non-patient Care          2
Name: count, dtype: int64

In [215]:
df1['Expenditure_Category4'].value_counts(dropna=False)

Expenditure_Category4
NaN                 1028461
Non-patient Care          9
Overhead                  2
Name: count, dtype: int64

In [216]:
df1['Expenditure_Category5'].value_counts(dropna=False)

Expenditure_Category5
NaN         1028462
Overhead          9
Other             1
Name: count, dtype: int64

In [217]:
df1['Expenditure_Category6'].value_counts(dropna=False)

Expenditure_Category6
NaN                            1028462
Other                                9
Professional Salary Support          1
Name: count, dtype: int64

Research data

In [218]:
df1[['Preclinical_Research_Indicator', 'Delay_in_Publication_Indicator', 
     'Name_of_Study', 'Dispute_Status_for_Publication','Payment_Publication_Date', 
    'ClinicalTrials_Gov_Identifier', 
     'Research_Information_Link', 'Context_of_Research']].describe(include=object)

,Preclinical_Research_Indicator,Delay_in_Publication_Indicator,Name_of_Study,Dispute_Status_for_Publication,Payment_Publication_Date,ClinicalTrials_Gov_Identifier,Research_Information_Link,Context_of_Research
count,1028472,1028472,1023118,1028472,1028472,490620,25725,119495
unique,2,1,16814,2,1,2109,355,4740
top,No,No,"A Phase 3, Randomized, Observer-blind, Active-...",No,06/28/2024,NCT05566639,https://clinicaltrials.gov/ct2/show/NCT0498720...,Payments or transfers of value related to rese...
freq,1016935,1028472,130147,1028277,1028472,130147,1914,21260

In [219]:
df1[['Preclinical_Research_Indicator', 'Delay_in_Publication_Indicator',
     'Name_of_Study', 'Dispute_Status_for_Publication', 
     'Payment_Publication_Date', 'ClinicalTrials_Gov_Identifier',
    'Research_Information_Link', 'Context_of_Research']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 8 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   Preclinical_Research_Indicator  1028472 non-null  object
 1   Delay_in_Publication_Indicator  1028472 non-null  object
 2   Name_of_Study                   1023118 non-null  object
 3   Dispute_Status_for_Publication  1028472 non-null  object
 4   Payment_Publication_Date        1028472 non-null  object
 5   ClinicalTrials_Gov_Identifier   490620 non-null   object
 6   Research_Information_Link       25725 non-null    object
 7   Context_of_Research             119495 non-null   object
dtypes: object(8)
memory usage: 62.8+ MB

In [220]:
df1['Preclinical_Research_Indicator'].value_counts(dropna=False)

Preclinical_Research_Indicator
No     1016935
Yes      11537
Name: count, dtype: int64

In [221]:
df1['Delay_in_Publication_Indicator'].value_counts(dropna=False)

Delay_in_Publication_Indicator
No    1028472
Name: count, dtype: int64

In [222]:
df1['Dispute_Status_for_Publication'].value_counts(dropna=False)

Dispute_Status_for_Publication
No     1028277
Yes        195
Name: count, dtype: int64

In [223]:
df1['Payment_Publication_Date'].value_counts(dropna=False)

Payment_Publication_Date
06/28/2024    1028472
Name: count, dtype: int64

In [224]:
df1['ClinicalTrials_Gov_Identifier'].value_counts(dropna=False)

ClinicalTrials_Gov_Identifier
NaN            537852
NCT05566639    130147
NCT05815498     87793
NCT06060457     22295
NCT05827068      9619
                ...
NCT05039523         1
NCT05382933         1
NCT05382931         1
NCT04810078         1
NCT05376839         1
Name: count, Length: 2110, dtype: int64

In [225]:
df1['Research_Information_Link'].value_counts(dropna=False)

Research_Information_Link
NaN                                                                                                                   1002747
https://clinicaltrials.gov/ct2/show/NCT04987203?intr=RCC&spons=Aveo+Pharmaceuticals&cntry=US&phase=2&draw=2&rank=1       1914
https://clinicaltrials.gov/ct2/show/NCT03975647                                                                          1394
https://clinicaltrials.gov/ct2/show/NCT04677569                                                                          1387
https://clinicaltrials.gov/ct2/show/NCT03646123                                                                          1206
                                                                                                                       ...
https://clinicaltrials.gov/ct2/show/NCT04148937                                                                             1
https://clinicaltrials.gov/study/NCT06085482                                                                                1
https://clinicaltrials.gov/study/NCT04408625                                                                                1
https://clinicaltrials.gov/ct2/show/NCT03740919                                                                             1
https://clinicaltrials.gov/ct2/show/NCT05292040                                                                             1
Name: count, Length: 356, dtype: int64

In [226]:
df1['Research_Information_Link'].describe()

count                                                 25725
unique                                                  355
top       https://clinicaltrials.gov/ct2/show/NCT0498720...
freq                                                   1914
Name: Research_Information_Link, dtype: object

In [227]:
# To avoid nan getting converted to string. 

msk = df1['Name_of_Study'].notna()
df1.loc[msk, 'Name_of_Study'] = df1.loc[msk, 'Name_of_Study'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Name_of_Study']= df1.loc[msk,'Name_of_Study'].apply(lambda x: x.lower())
df1['Name_of_Study'].nunique()

16718

In [228]:
df1['Name_of_Study'].describe()

count                                               1023118
unique                                                16718
top       a phase 3, randomized, observer-blind, active-...
freq                                                 130147
Name: Name_of_Study, dtype: object

In [229]:
df1['Name_of_Study'].isna().sum()

5354

In [230]:
df1['Name_of_Study'].value_counts(dropna=False)

Name_of_Study
a phase 3, randomized, observer-blind, active-controlled study to evaluate the safety and efficacy of mrna-1010 candidate seasonal influenza vaccine in adults 50 years and older                                                                                                            130147
a randomized, observer-blind, active-controlled phase 3 study to investigate the safety, immunogenicity, and relative vaccine efficacy of mrna-1283.222 administered as a booster dose compared with mrna-1273.222 in participants aged 12 years and older for the prevention of covid-19     87793
a phase 3, randomized, observer-blind study to evaluate safety, tolerability, and immunogenicity of mrna-1345, an mrna vaccine targeting respiratory syncytial virus, when coadministered with a high-dose, quadrivalent seasonal influenza vaccine in adults 65 years of age                 22295
zilebesiran as add-on therapy in patients with hypertension not adequately controlled by a standard of care antihypertensive medication (kardia-2)                                                                                                                                            15756
ex9924-4473                                                                                                                                                                                                                                                                                   13357
                                                                                                                                                                                                                                                                                              ...
post market clinical follow up study for profemur                                                                                                                                                                                                                                                 1
a retrospective analysis of outcomes, resource utilization, patterns of use and predictors of response and toxicity among patients receiving commercial car t-cell therapy for aggressive large b-cell lymphoma                                                                                   1
ttax01-cr003-120-120-004 -study visit 12  (21 jun 2023)                                                                                                                                                                                                                                           1
phase i trial of adjuvant mk-3475 after induction chemotherapy and hemithoracic radiation therapy for unresectable malignant pleural mesothelioma                                                                                                                                                 1
ttax01-cr003-101-101-012 -long term observation study visit 24  (30 mar 2023)                                                                                                                                                                                                                     1
Name: count, Length: 16719, dtype: int64

In [231]:
df1['Context_of_Research'].describe()

count                                                119495
unique                                                 4740
top       Payments or transfers of value related to rese...
freq                                                  21260
Name: Context_of_Research, dtype: object

In [232]:
# To avoid nan getting converted to string. Recipient speciality
msk = df1['Context_of_Research'].notna()
df1.loc[msk, 'Context_of_Research'] = df1.loc[msk, 'Context_of_Research'].astype(str)

# Converting all City names to lower first to verify.
df1.loc[msk, 'Context_of_Research']= df1.loc[msk,'Context_of_Research'].apply(lambda x: x.lower())
df1['Context_of_Research'].nunique()

4733

In [233]:
df1['Context_of_Research'].value_counts(dropna=False)

Context_of_Research
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                   908977
payments or transfers of value related to research are provided to a studys respective site and associated, per cms requirements, with a principal investigator. the amount of this record may be associated with a payment, or it may be associated with other transfers of value related to research, including, but not limited to, service costs, supplies, equipment and rentals, investigator meeting costs, and study drug.     21260
hcp did not receive direct payment from gsk. hcp was listed as the primary investigator in accordance with the sunshine act requirements.                                                                                                                                                                                                                                                                                              15205
the amount reported represents either an aggregate of cash payments -e.g. clinical study services reimbursements for expenses or pass-through costs- or an aggregate of in-kind value -e.g. supplies equipment- provided by lilly or by a third party vendor                                                                                                                                                                           11566
study drug                                                                                                                                                                                                                                                                                                                                                                                                                              3344
                                                                                                                                                                                                                                                                                                                                                                                                                                       ...
payee was dr. denard                                                                                                                                                                                                                                                                                                                                                                                                                       1
;in-us-276-5456;2766388;ebs_research;132655001;12428569                                                                                                                                                                                                                                                                                                                                                                                    1
3201002442                                                                                                                                                                                                                                                                                                                                                                                                                                 1
;immu-132-06;3494663;gtf-r;201649466;10861274                                                                                                                                                                                                                                                                                                                                                                                              1
;kt-us-472-0118;2751740;sap;201557751;10219816                                                                                                                                                                                                                                                                                                                                                                                             1
Name: count, Length: 4734, dtype: int64

In [234]:
df1[['Record_ID', 'Program_Year']].describe()

          Record_ID  Program_Year
count  1.028472e+06     1028472.0
mean   1.028921e+09        2023.0
std    2.214341e+07           0.0
min    9.658282e+08        2023.0
25%    1.008024e+09        2023.0
50%    1.040348e+09        2023.0
75%    1.042248e+09        2023.0
max    1.060932e+09        2023.0

In [235]:
df1[['Record_ID']]=df1[['Record_ID']].astype(object)

In [236]:
df1[['Record_ID']].describe(include=object)

         Record_ID
count      1028472
unique     1028472
top     1060226505
freq             1

In [237]:
# Reverify after lower case conversion

df1[['Preclinical_Research_Indicator', 'Delay_in_Publication_Indicator', 
     'Name_of_Study', 'Dispute_Status_for_Publication','Payment_Publication_Date', 
    'ClinicalTrials_Gov_Identifier', 
     'Research_Information_Link', 'Context_of_Research']].describe(include=object)

,Preclinical_Research_Indicator,Delay_in_Publication_Indicator,Name_of_Study,Dispute_Status_for_Publication,Payment_Publication_Date,ClinicalTrials_Gov_Identifier,Research_Information_Link,Context_of_Research
count,1028472,1028472,1023118,1028472,1028472,490620,25725,119495
unique,2,1,16718,2,1,2109,355,4733
top,No,No,"a phase 3, randomized, observer-blind, active-...",No,06/28/2024,NCT05566639,https://clinicaltrials.gov/ct2/show/NCT0498720...,payments or transfers of value related to rese...
freq,1016935,1028472,130147,1028277,1028472,130147,1914,21260

Covered recipients investigators

In [238]:
df1[['Principal_Investigator_1_Covered_Recipient_Type','Principal_Investigator_1_Profile_ID',
    'Principal_Investigator_1_NPI', 'Principal_Investigator_1_First_Name',
    'Principal_Investigator_1_Middle_Name', 'Principal_Investigator_1_Last_Name',
    'Principal_Investigator_1_Name_Suffix', 'Principal_Investigator_1_Business_Street_Address_Line1',
    'Principal_Investigator_1_Business_Street_Address_Line2', 'Principal_Investigator_1_City',
    'Principal_Investigator_1_State','Principal_Investigator_1_Zip_Code',
    'Principal_Investigator_1_Country','Principal_Investigator_1_Province',
     'Principal_Investigator_1_Postal_Code']].describe(include=object)

,Principal_Investigator_1_Covered_Recipient_Type,Principal_Investigator_1_First_Name,Principal_Investigator_1_Middle_Name,Principal_Investigator_1_Last_Name,Principal_Investigator_1_Name_Suffix,Principal_Investigator_1_Business_Street_Address_Line1,Principal_Investigator_1_Business_Street_Address_Line2,Principal_Investigator_1_City,Principal_Investigator_1_State,Principal_Investigator_1_Zip_Code,Principal_Investigator_1_Country,Principal_Investigator_1_Province,Principal_Investigator_1_Postal_Code
count,997360,997356,173178,997354,9632,997360,285034,997360,997356,997356,997360,3,4
unique,2,8518,3293,20015,19,28160,7460,3891,52,12834,4,2,3
top,Covered Recipient Physician,DAVID,A,PATEL,MD,1801 PONCE DE LEON BLVD,SUITE 200,MIAMI,FL,77030,United States,MD,20817
freq,995214,26110,11962,7452,4815,6764,14064,22227,128866,6877,997356,2,2

In [239]:
df1[['Principal_Investigator_1_Covered_Recipient_Type','Principal_Investigator_1_Profile_ID',
    'Principal_Investigator_1_NPI', 'Principal_Investigator_1_First_Name',
    'Principal_Investigator_1_Middle_Name', 'Principal_Investigator_1_Last_Name',
    'Principal_Investigator_1_Name_Suffix', 'Principal_Investigator_1_Business_Street_Address_Line1',
    'Principal_Investigator_1_Business_Street_Address_Line2', 'Principal_Investigator_1_City',
    'Principal_Investigator_1_State','Principal_Investigator_1_Zip_Code',
    'Principal_Investigator_1_Country','Principal_Investigator_1_Province',
     'Principal_Investigator_1_Postal_Code']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 15 columns):
 #   Column                                                  Non-Null Count   Dtype
---  ------                                                  --------------   -----
 0   Principal_Investigator_1_Covered_Recipient_Type         997360 non-null  object
 1   Principal_Investigator_1_Profile_ID                     997360 non-null  float64
 2   Principal_Investigator_1_NPI                            997262 non-null  float64
 3   Principal_Investigator_1_First_Name                     997356 non-null  object
 4   Principal_Investigator_1_Middle_Name                    173178 non-null  object
 5   Principal_Investigator_1_Last_Name                      997354 non-null  object
 6   Principal_Investigator_1_Name_Suffix                    9632 non-null    object
 7   Principal_Investigator_1_Business_Street_Address_Line1  997360 non-null  object
 8   Principal_Investigator_1_Business_Street_Address_Line2  285034 non-null  object
 9   Principal_Investigator_1_City                           997360 non-null  object
 10  Principal_Investigator_1_State                          997356 non-null  object
 11  Principal_Investigator_1_Zip_Code                       997356 non-null  object
 12  Principal_Investigator_1_Country                        997360 non-null  object
 13  Principal_Investigator_1_Province                       3 non-null       object
 14  Principal_Investigator_1_Postal_Code                    4 non-null       object
dtypes: float64(2), object(13)
memory usage: 117.7+ MB

In [240]:
df1['Principal_Investigator_1_Covered_Recipient_Type'].value_counts(dropna=False)

Principal_Investigator_1_Covered_Recipient_Type
Covered Recipient Physician                     995214
NaN                                              31112
Covered Recipient Non-Physician Practitioner      2146
Name: count, dtype: int64

In [241]:
df1['Principal_Investigator_1_Profile_ID']=df1['Principal_Investigator_1_NPI'].astype(object)

In [242]:
df1['Principal_Investigator_1_Profile_ID'].value_counts(dropna=False)

Principal_Investigator_1_Profile_ID
NaN             31210
1.679657e+09     6852
1.659305e+09     6836
1.235251e+09     6601
1.013998e+09     6467
                ...
1.457473e+09        1
1.215359e+09        1
1.669462e+09        1
1.699751e+09        1
1.649349e+09        1
Name: count, Length: 29968, dtype: int64

In [243]:
df1['Principal_Investigator_1_NPI'].value_counts(dropna=False)

Principal_Investigator_1_NPI
NaN             31210
1.679657e+09     6852
1.659305e+09     6836
1.235251e+09     6601
1.013998e+09     6467
                ...
1.457473e+09        1
1.215359e+09        1
1.669462e+09        1
1.699751e+09        1
1.649349e+09        1
Name: count, Length: 29968, dtype: int64

In [3]:
df1[['Principal_Investigator_1_First_Name']].describe()

       Principal_Investigator_1_First_Name
count                               997356
unique                                8518
top                                  DAVID
freq                                 26110

In [4]:
# Lower case conversion

msk = df1['Principal_Investigator_1_First_Name'].notna()
df1.loc[msk, 'Principal_Investigator_1_First_Name'] = df1.loc[msk, 'Principal_Investigator_1_First_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_1_First_Name']= df1.loc[msk,'Principal_Investigator_1_First_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_1_First_Name'].nunique()

7406

In [5]:
df1[['Principal_Investigator_1_First_Name']].value_counts(dropna=False)

Principal_Investigator_1_First_Name
NaN                                    31116
david                                  26836
john                                   26345
robert                                 21174
michael                                21168
                                       ...
tosca                                      1
gitonga                                    1
gisoo                                      1
tova                                       1
alfio                                      1
Name: count, Length: 7407, dtype: int64

In [247]:
# Lower case conversion

msk = df1['Principal_Investigator_1_Middle_Name'].notna()
df1.loc[msk, 'Principal_Investigator_1_Middle_Name'] = df1.loc[msk, 'Principal_Investigator_1_Middle_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_1_Middle_Name']= df1.loc[msk,'Principal_Investigator_1_Middle_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_1_Middle_Name'].nunique()

3052

In [248]:
df1[['Principal_Investigator_1_Middle_Name']].value_counts(dropna=False)

Principal_Investigator_1_Middle_Name
NaN                                     855294
a                                        11962
m                                         9313
j                                         7334
d.                                        6523
                                         ...
amin                                         1
kilian                                       1
sanat                                        1
kie-lo                                       1
derek                                        1
Name: count, Length: 3053, dtype: int64

In [249]:
df1[['Principal_Investigator_1_Middle_Name']].describe()

       Principal_Investigator_1_Middle_Name
count                                173178
unique                                 3052
top                                       a
freq                                  11962

In [250]:
# Lower case conversion

msk = df1['Principal_Investigator_1_Last_Name'].notna()
df1.loc[msk, 'Principal_Investigator_1_Last_Name'] = df1.loc[msk, 'Principal_Investigator_1_Last_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_1_Last_Name']= df1.loc[msk,'Principal_Investigator_1_Last_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_1_Last_Name'].nunique()

18261

In [251]:
df1[['Principal_Investigator_1_Last_Name']].value_counts(dropna=False)

Principal_Investigator_1_Last_Name
NaN                                   31118
patel                                  7535
martin                                 6908
surowitz                               6852
sesin                                  6836
                                      ...
mwangi                                    1
muzny                                     1
stilp                                     1
cavendish                                 1
flagg                                     1
Name: count, Length: 18262, dtype: int64

In [252]:
df1['Principal_Investigator_1_Name_Suffix'].describe()

count     9632
unique      19
top         MD
freq      4815
Name: Principal_Investigator_1_Name_Suffix, dtype: object

In [253]:
df1['Principal_Investigator_1_Name_Suffix'].value_counts(dropna=False)

Principal_Investigator_1_Name_Suffix
NaN    1018840
MD        4815
JR.       1401
III       1071
JR         897
II         487
IV         217
V          155
DR.         94
DO          86
I           86
SR.         75
Jr          60
SR          54
Jr.         45
P           42
OD          22
Sr          15
Sr.          9
M.D          1
Name: count, dtype: int64

In [254]:
df1['Principal_Investigator_1_Business_Street_Address_Line1'].describe()

count                      997360
unique                      28160
top       1801 PONCE DE LEON BLVD
freq                         6764
Name: Principal_Investigator_1_Business_Street_Address_Line1, dtype: object

In [255]:
df1['Principal_Investigator_1_Business_Street_Address_Line1'].value_counts(dropna=False)

Principal_Investigator_1_Business_Street_Address_Line1
NaN                                    31112
1801 PONCE DE LEON BLVD                 6764
1094 MILITARY TRL                       6689
16300 College Blvd                      6460
710 LAWRENCE ST                         6182
                                       ...
20201 Crawford Ave                         1
300 KEISLER DR STE 204                     1
393 BLOSSOM HILL RD                        1
601 DR MARTIN LUTHER KING JR AVE NE        1
8600 Old Georgetown Rd                     1
Name: count, Length: 28161, dtype: int64

In [256]:
df1['Principal_Investigator_1_Business_Street_Address_Line2'].describe()

count        285034
unique         7460
top       SUITE 200
freq          14064
Name: Principal_Investigator_1_Business_Street_Address_Line2, dtype: object

In [257]:
df1['Principal_Investigator_1_Business_Street_Address_Line2'].value_counts(dropna=False)

Principal_Investigator_1_Business_Street_Address_Line2
NaN                                743438
SUITE 200                           14064
SUITE A                              9607
SUITE 100                            8578
SUITE O- 244                         5609
                                    ...
MAILBOX 20                              1
4501 X Street                           1
Suite  300                              1
Charak Clinical Research Center         1
DEPT HEMATOLOGY/ONCOLOGY                1
Name: count, Length: 7461, dtype: int64

In [258]:
df1['Principal_Investigator_1_City'].describe()

count     997360
unique      3891
top        MIAMI
freq       22227
Name: Principal_Investigator_1_City, dtype: object

In [259]:
# Lower case conversion

msk = df1['Principal_Investigator_1_City'].notna()
df1.loc[msk, 'Principal_Investigator_1_City'] = df1.loc[msk, 'Principal_Investigator_1_City'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_1_City']= df1.loc[msk,'Principal_Investigator_1_City'].apply(lambda x: x.lower())
df1['Principal_Investigator_1_City'].nunique()

2671

In [260]:
df1['Principal_Investigator_1_City'].value_counts(dropna=False)

Principal_Investigator_1_City
NaN              31112
miami            25023
houston          22396
dallas           19252
new york         17748
                 ...
american fork        1
logansport           1
elmsford             1
turlock              1
clifton park         1
Name: count, Length: 2672, dtype: int64

In [261]:
df1['Principal_Investigator_1_State'].value_counts(dropna=False)

Principal_Investigator_1_State
FL     128866
TX     125058
CA     112355
NY      42554
OH      36291
GA      35225
NC      34842
NaN     31116
PA      30530
TN      26000
AZ      24485
CO      24245
SC      23401
VA      23292
MA      22357
MO      21220
IL      20989
LA      19629
MI      19221
NE      17213
KS      16086
MD      15252
UT      13579
OK      13182
MN      13158
AL      12719
WA      11390
IN      10876
NJ      10278
NV       9939
OR       8444
ID       8074
CT       7445
KY       7000
PR       6704
MS       6659
WI       6315
AR       5515
RI       4511
IA       3856
DC       3582
NM       2361
SD       2337
NH       1788
MT       1424
WV       1357
ND       1340
ME       1291
HI       1135
VT        994
DE        786
AK        188
WY         18
Name: count, dtype: int64

In [262]:
df1['Principal_Investigator_1_Zip_Code'].value_counts(dropna=False)

Principal_Investigator_1_Zip_Code
NaN           31116
77030          6877
33134-4418     6698
33458-7021     6638
66219          6506
              ...
73069-6232        1
07901-3570        1
83702-7307        1
37909-2604        1
78215-1639        1
Name: count, Length: 12835, dtype: int64

In [263]:
df1['Principal_Investigator_1_Country'].value_counts(dropna=False)

Principal_Investigator_1_Country
United States                           997356
NaN                                      31112
United States Minor Outlying Islands         2
Germany                                      1
Canada                                       1
Name: count, dtype: int64

In [264]:
df1['Principal_Investigator_1_Province'].value_counts(dropna=False)

Principal_Investigator_1_Province
NaN    1028469
MD           2
NS           1
Name: count, dtype: int64

In [265]:
df1['Principal_Investigator_1_Postal_Code'].value_counts(dropna=False)

Principal_Investigator_1_Postal_Code
NaN           1028468
20817               2
21287-0005          1
B3H                 1
Name: count, dtype: int64

In [266]:
# reverify 

df1[['Principal_Investigator_1_Covered_Recipient_Type','Principal_Investigator_1_Profile_ID',
    'Principal_Investigator_1_NPI', 'Principal_Investigator_1_First_Name',
    'Principal_Investigator_1_Middle_Name', 'Principal_Investigator_1_Last_Name',
    'Principal_Investigator_1_Name_Suffix', 'Principal_Investigator_1_Business_Street_Address_Line1',
    'Principal_Investigator_1_Business_Street_Address_Line2', 'Principal_Investigator_1_City',
    'Principal_Investigator_1_State','Principal_Investigator_1_Zip_Code',
    'Principal_Investigator_1_Country','Principal_Investigator_1_Province',
     'Principal_Investigator_1_Postal_Code']].describe(include=object)

,Principal_Investigator_1_Covered_Recipient_Type,Principal_Investigator_1_Profile_ID,Principal_Investigator_1_First_Name,Principal_Investigator_1_Middle_Name,Principal_Investigator_1_Last_Name,Principal_Investigator_1_Name_Suffix,Principal_Investigator_1_Business_Street_Address_Line1,Principal_Investigator_1_Business_Street_Address_Line2,Principal_Investigator_1_City,Principal_Investigator_1_State,Principal_Investigator_1_Zip_Code,Principal_Investigator_1_Country,Principal_Investigator_1_Province,Principal_Investigator_1_Postal_Code
count,997360,9.972620e+05,997356,173178,997354,9632,997360,285034,997360,997356,997356,997360,3,4
unique,2,2.996700e+04,7406,3052,18261,19,28160,7460,2671,52,12834,4,2,3
top,Covered Recipient Physician,1.679657e+09,david,a,patel,MD,1801 PONCE DE LEON BLVD,SUITE 200,miami,FL,77030,United States,MD,20817
freq,995214,6.852000e+03,26836,11962,7535,4815,6764,14064,25023,128866,6877,997356,2,2

In [267]:
df1['Principal_Investigator_1_Primary_Type_1'].value_counts(dropna=False)

Principal_Investigator_1_Primary_Type_1
Medical Doctor                            920558
Doctor of Osteopathy                       68617
NaN                                        31112
Doctor of Optometry                         3344
Doctor of Podiatric Medicine                2370
Nurse Practitioner                          1261
Physician Assistant                          864
Doctor of Dentistry                          198
Chiropractor                                 127
Clinical Nurse Specialist                     18
Certified Registered Nurse Anesthetist         3
Name: count, dtype: int64

In [268]:
df1[['Principal_Investigator_1_Primary_Type_1',
     'Principal_Investigator_1_Primary_Type_2', 'Principal_Investigator_1_Primary_Type_3',
     'Principal_Investigator_1_Primary_Type_4', 'Principal_Investigator_1_Primary_Type_5',
     'Principal_Investigator_1_Primary_Type_6']].describe(include=object)

       Principal_Investigator_1_Primary_Type_1
count                                   997360
unique                                      10
top                             Medical Doctor
freq                                    920558

In [269]:
df1['Principal_Investigator_1_Primary_Type_1'].value_counts(dropna=False)

Principal_Investigator_1_Primary_Type_1
Medical Doctor                            920558
Doctor of Osteopathy                       68617
NaN                                        31112
Doctor of Optometry                         3344
Doctor of Podiatric Medicine                2370
Nurse Practitioner                          1261
Physician Assistant                          864
Doctor of Dentistry                          198
Chiropractor                                 127
Clinical Nurse Specialist                     18
Certified Registered Nurse Anesthetist         3
Name: count, dtype: int64

In [270]:
df1[['Principal_Investigator_1_Specialty_1', 'Principal_Investigator_1_Specialty_2', 
     'Principal_Investigator_1_Specialty_3', 'Principal_Investigator_1_Specialty_4',
     'Principal_Investigator_1_Specialty_5', 'Principal_Investigator_1_Specialty_6',
    ]].describe(include=object)

                     Principal_Investigator_1_Specialty_1
count                                              997360
unique                                                234
top     Allopathic & Osteopathic Physicians|Family Med...
freq                                               165525

In [271]:
df1[['Principal_Investigator_1_Specialty_1', 'Principal_Investigator_1_Specialty_2', 
     'Principal_Investigator_1_Specialty_3', 'Principal_Investigator_1_Specialty_4',
     'Principal_Investigator_1_Specialty_5', 'Principal_Investigator_1_Specialty_6',
    ]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Principal_Investigator_1_Specialty_1  997360 non-null  object
 1   Principal_Investigator_1_Specialty_2  0 non-null       float64
 2   Principal_Investigator_1_Specialty_3  0 non-null       float64
 3   Principal_Investigator_1_Specialty_4  0 non-null       float64
 4   Principal_Investigator_1_Specialty_5  0 non-null       float64
 5   Principal_Investigator_1_Specialty_6  0 non-null       float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [272]:
df1['Principal_Investigator_1_Specialty_1'].value_counts(dropna=False)

Principal_Investigator_1_Specialty_1
Allopathic & Osteopathic Physicians|Family Medicine                                                      165525
Allopathic & Osteopathic Physicians|Internal Medicine                                                    148454
Allopathic & Osteopathic Physicians|Internal Medicine|Hematology & Oncology                               79843
Allopathic & Osteopathic Physicians|Internal Medicine|Medical Oncology                                    45746
Allopathic & Osteopathic Physicians|Internal Medicine|Endocrinology, Diabetes & Metabolism                42659
                                                                                                          ...
Allopathic & Osteopathic Physicians|Emergency Medicine|Undersea and Hyperbaric Medicine                       1
Allopathic & Osteopathic Physicians|Medical Genetics|Medical Biochemical Genetics                             1
Physician Assistants & Advanced Practice Nursing Providers|Nurse Practitioner|Obstetrics & Gynecology         1
Physician Assistants & Advanced Practice Nursing Providers|Advanced Practice Midwife                          1
Allopathic & Osteopathic Physicians|Psychiatry & Neurology|Sports Medicine                                    1
Name: count, Length: 235, dtype: int64

In [273]:
df1['Principal_Investigator_1_Specialty_1'].isnull().sum()

31112

In [274]:
# Principal investigators

In [275]:
df1[['Principal_Investigator_1_License_State_code1', 'Principal_Investigator_1_License_State_code2',
    'Principal_Investigator_1_License_State_code3', 'Principal_Investigator_1_License_State_code4',
    'Principal_Investigator_1_License_State_code5']].describe()

,Principal_Investigator_1_License_State_code1,Principal_Investigator_1_License_State_code2,Principal_Investigator_1_License_State_code3,Principal_Investigator_1_License_State_code4,Principal_Investigator_1_License_State_code5
count,997360,10697,2599,556,84
unique,54,50,41,24,11
top,FL,TX,TX,TX,GA
freq,141452,1487,510,199,56

In [276]:
df1[['Principal_Investigator_1_License_State_code1', 'Principal_Investigator_1_License_State_code2',
    'Principal_Investigator_1_License_State_code3', 'Principal_Investigator_1_License_State_code4',
    'Principal_Investigator_1_License_State_code5']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 5 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   Principal_Investigator_1_License_State_code1  997360 non-null  object
 1   Principal_Investigator_1_License_State_code2  10697 non-null   object
 2   Principal_Investigator_1_License_State_code3  2599 non-null    object
 3   Principal_Investigator_1_License_State_code4  556 non-null     object
 4   Principal_Investigator_1_License_State_code5  84 non-null      object
dtypes: object(5)
memory usage: 39.2+ MB

In [277]:
df1['Principal_Investigator_1_License_State_code1'].value_counts(dropna=False)

Principal_Investigator_1_License_State_code1
FL     141452
CA     127447
TX     106628
NY      38889
NC      37282
AZ      32175
NaN     31112
GA      30762
OH      28843
IL      28355
PA      25070
MA      24534
LA      23003
MI      21470
CO      20873
TN      20078
SC      20004
KS      18043
VA      17987
MO      16041
AL      16010
NE      15159
IN      14013
OK      13757
MN      13200
MD      13090
UT      12592
NJ      12480
KY      11327
ID      10849
CT      10758
WA       8350
AR       7976
IA       6693
MS       6418
DC       5814
OR       5621
NM       5503
NV       4183
WI       4047
RI       3897
PR       3618
HI       2225
AK       2022
MT       1788
ND       1530
NH       1343
DE       1079
WV       1021
VT        832
ME        656
SD        552
WY         11
GU          5
FM          5
Name: count, dtype: int64

In [278]:
df1['Principal_Investigator_1_License_State_code2'].value_counts(dropna=False)

Principal_Investigator_1_License_State_code2
NaN    1017775
TX        1487
OH         789
NY         700
VA         631
WI         630
TN         563
PA         549
MI         543
MN         424
NC         391
MD         360
UT         318
MO         298
MA         282
OR         269
WA         250
IL         182
KY         175
GA         151
NJ         145
SC         129
MT         122
CA         117
KS         109
NV          97
SD          95
IA          86
RI          82
AZ          63
NM          59
MS          54
WY          52
FL          50
NE          47
IN          46
NH          44
LA          42
CO          42
OK          41
WV          37
ID          33
VT          29
CT          19
DC          16
ME          15
ND          15
VI          11
HI           3
AR           3
DE           2
Name: count, dtype: int64

In [279]:
df1['Principal_Investigator_1_License_State_code3'].value_counts(dropna=False)

Principal_Investigator_1_License_State_code3
NaN    1025873
TX         510
PA         338
OH         309
TN         179
WA         161
NC         154
MN         100
UT          80
WI          70
KS          69
VA          69
CO          57
WV          56
LA          45
NY          45
FL          43
MO          33
SC          31
IN          24
NV          24
MD          20
NJ          19
IL          17
NE          17
KY          16
OR          14
VT          13
RI          11
SD           9
ME           9
ID           8
OK           8
NM           8
MI           8
NH           7
MA           7
GA           5
MT           3
WY           1
CA           1
MS           1
Name: count, dtype: int64

In [280]:
df1['Principal_Investigator_1_License_State_code4'].value_counts(dropna=False)

Principal_Investigator_1_License_State_code4
NaN    1027916
TX         199
WI          69
CT          56
WA          43
SC          25
NV          21
WY          19
VA          17
NH          17
IN          12
NJ          11
NY          10
WV          10
PA          10
MO           9
TN           6
MD           5
OH           4
MI           4
MS           3
UT           2
RI           2
NC           1
FL           1
Name: count, dtype: int64

In [281]:
df1['Principal_Investigator_1_License_State_code5'].value_counts(dropna=False)

Principal_Investigator_1_License_State_code5
NaN    1028388
GA          56
TX           7
NM           5
VA           3
UT           3
NY           3
WA           2
PA           2
NE           1
SD           1
MI           1
Name: count, dtype: int64

In [282]:
df1[['Principal_Investigator_2_Covered_Recipient_Type','Principal_Investigator_2_Profile_ID',
    'Principal_Investigator_2_NPI', 'Principal_Investigator_2_First_Name',
    'Principal_Investigator_2_Middle_Name', 'Principal_Investigator_2_Last_Name',
    'Principal_Investigator_2_Name_Suffix', 'Principal_Investigator_2_Business_Street_Address_Line1',
    'Principal_Investigator_2_Business_Street_Address_Line2', 'Principal_Investigator_2_City',
    'Principal_Investigator_2_State','Principal_Investigator_2_Zip_Code',
    'Principal_Investigator_2_Country','Principal_Investigator_2_Province',
     'Principal_Investigator_2_Postal_Code']].describe(include=object)

,Principal_Investigator_2_Covered_Recipient_Type,Principal_Investigator_2_First_Name,Principal_Investigator_2_Middle_Name,Principal_Investigator_2_Last_Name,Principal_Investigator_2_Name_Suffix,Principal_Investigator_2_Business_Street_Address_Line1,Principal_Investigator_2_Business_Street_Address_Line2,Principal_Investigator_2_City,Principal_Investigator_2_State,Principal_Investigator_2_Zip_Code,Principal_Investigator_2_Country
count,2172,2172,263,2172,21,2172,844,2172,2172,2172,2172
unique,2,402,69,509,3,500,118,287,48,415,1
top,Covered Recipient Physician,SAMEER,N,KHANDHAR,IV,51 N 39TH ST,PHI 2C,PHILADELPHIA,PA,19104-2640,United States
freq,2168,363,33,363,13,363,363,369,421,363,2172

In [283]:
df1[['Principal_Investigator_2_Covered_Recipient_Type','Principal_Investigator_2_Profile_ID',
    'Principal_Investigator_2_NPI', 'Principal_Investigator_2_First_Name',
    'Principal_Investigator_2_Middle_Name', 'Principal_Investigator_2_Last_Name',
    'Principal_Investigator_2_Name_Suffix', 'Principal_Investigator_2_Business_Street_Address_Line1',
    'Principal_Investigator_2_Business_Street_Address_Line2', 'Principal_Investigator_2_City',
    'Principal_Investigator_2_State','Principal_Investigator_2_Zip_Code',
    'Principal_Investigator_2_Country','Principal_Investigator_2_Province',
     'Principal_Investigator_2_Postal_Code']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 15 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Principal_Investigator_2_Covered_Recipient_Type         2172 non-null   object
 1   Principal_Investigator_2_Profile_ID                     2172 non-null   float64
 2   Principal_Investigator_2_NPI                            2169 non-null   float64
 3   Principal_Investigator_2_First_Name                     2172 non-null   object
 4   Principal_Investigator_2_Middle_Name                    263 non-null    object
 5   Principal_Investigator_2_Last_Name                      2172 non-null   object
 6   Principal_Investigator_2_Name_Suffix                    21 non-null     object
 7   Principal_Investigator_2_Business_Street_Address_Line1  2172 non-null   object
 8   Principal_Investigator_2_Business_Street_Address_Line2  844 non-null    object
 9   Principal_Investigator_2_City                           2172 non-null   object
 10  Principal_Investigator_2_State                          2172 non-null   object
 11  Principal_Investigator_2_Zip_Code                       2172 non-null   object
 12  Principal_Investigator_2_Country                        2172 non-null   object
 13  Principal_Investigator_2_Province                       0 non-null      float64
 14  Principal_Investigator_2_Postal_Code                    0 non-null      float64
dtypes: float64(4), object(11)
memory usage: 117.7+ MB

In [284]:
df1['Principal_Investigator_2_Covered_Recipient_Type'].value_counts(dropna=False)

Principal_Investigator_2_Covered_Recipient_Type
NaN                                             1026300
Covered Recipient Physician                        2168
Covered Recipient Non-Physician Practitioner          4
Name: count, dtype: int64

In [285]:
df1['Principal_Investigator_2_Profile_ID'].value_counts(dropna=False)

Principal_Investigator_2_Profile_ID
NaN          1026300
24935.0          363
1161312.0         80
11507.0           58
559634.0          42
              ...
210573.0           1
311260.0           1
653476.0           1
224829.0           1
1280473.0          1
Name: count, Length: 533, dtype: int64

In [286]:
df1['Principal_Investigator_2_Profile_ID']=df1['Principal_Investigator_2_Profile_ID'].astype(object)

In [287]:
df1['Principal_Investigator_2_Profile_ID'].describe()

count      2172.0
unique      532.0
top       24935.0
freq        363.0
Name: Principal_Investigator_2_Profile_ID, dtype: float64

In [288]:
df1['Principal_Investigator_2_NPI']=df1['Principal_Investigator_2_NPI'].astype(object)

In [289]:
df1['Principal_Investigator_2_NPI'].describe()

count     2.169000e+03
unique    5.300000e+02
top       1.558534e+09
freq      3.630000e+02
Name: Principal_Investigator_2_NPI, dtype: float64

In [290]:
df1['Principal_Investigator_2_NPI'].value_counts(dropna=False)

Principal_Investigator_2_NPI
NaN             1026303
1.558534e+09        363
1.023270e+09         80
1.265423e+09         58
1.902948e+09         42
                 ...
1.245314e+09          1
1.427190e+09          1
1.326238e+09          1
1.639312e+09          1
1.437343e+09          1
Name: count, Length: 531, dtype: int64

In [291]:
# Lower case conversion

msk = df1['Principal_Investigator_2_First_Name'].notna()
df1.loc[msk, 'Principal_Investigator_2_First_Name'] = df1.loc[msk, 'Principal_Investigator_2_First_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_2_First_Name']= df1.loc[msk,'Principal_Investigator_2_First_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_2_First_Name'].nunique()

374

In [292]:
df1['Principal_Investigator_2_First_Name'].value_counts(dropna=False)

Principal_Investigator_2_First_Name
NaN        1026300
sameer         363
amit            80
neal            58
hugh            48
            ...
sareena          1
vivian           1
ricardo          1
yang             1
naim             1
Name: count, Length: 375, dtype: int64

In [293]:
# Lower case conversion

msk = df1['Principal_Investigator_2_Middle_Name'].notna()
df1.loc[msk, 'Principal_Investigator_2_Middle_Name'] = df1.loc[msk, 'Principal_Investigator_2_Middle_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_2_Middle_Name']= df1.loc[msk,'Principal_Investigator_2_Middle_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_2_Middle_Name'].nunique()

68

In [294]:
df1[ 'Principal_Investigator_2_Middle_Name'].value_counts(dropna=False)

Principal_Investigator_2_Middle_Name
NaN         1028209
n                33
s                24
a                20
j                15
             ...
yue               1
michelle          1
garrett           1
shunnun           1
hasan             1
Name: count, Length: 69, dtype: int64

In [295]:
# Lower case conversion

msk = df1['Principal_Investigator_2_Last_Name'].notna()
df1.loc[msk, 'Principal_Investigator_2_Last_Name'] = df1.loc[msk, 'Principal_Investigator_2_Last_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_2_Last_Name']= df1.loc[msk,'Principal_Investigator_2_Last_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_2_Last_Name'].nunique()

498

In [296]:
df1['Principal_Investigator_2_Last_Name'].value_counts(dropna=False)

Principal_Investigator_2_Last_Name
NaN           1026300
khandhar          363
vora               80
shore              58
poindexter         42
               ...
gbolahan            1
kalra               1
mannis              1
flinn               1
khoury              1
Name: count, Length: 499, dtype: int64

In [297]:
df1['Principal_Investigator_2_Name_Suffix'].value_counts(dropna=False)

Principal_Investigator_2_Name_Suffix
NaN    1028451
IV          13
OD           7
JR           1
Name: count, dtype: int64

In [298]:
df1['Principal_Investigator_2_Business_Street_Address_Line1'].value_counts(dropna=False)

Principal_Investigator_2_Business_Street_Address_Line1
NaN                         1026300
51 N 39TH ST                    363
789 HOWARD AVE                   80
823 82ND PKWY                    58
9430 BROADWAY ST STE 120         42
                             ...
3151 Bellevue Ave                 1
220 Concourse Blvd                1
7912 E 31st Ct Ste 220            1
768 AVERY BLVD N                  1
301 N 8TH ST                      1
Name: count, Length: 501, dtype: int64

In [299]:
df1['Principal_Investigator_2_Business_Street_Address_Line2'].value_counts(dropna=False)

Principal_Investigator_2_Business_Street_Address_Line2
NaN                            1027628
PHI 2C                             363
--                                  48
SUITE 140                           34
SUITE 305                           31
                                ...
STE D                                1
SUITE 625                            1
STE 302                              1
920 E 28th Street Suite 100          1
STE 700                              1
Name: count, Length: 119, dtype: int64

In [300]:
df1['Principal_Investigator_2_City'].value_counts(dropna=False)

Principal_Investigator_2_City
NaN             1026300
PHILADELPHIA        369
NEW HAVEN            80
MYRTLE BEACH         58
PEARLAND             42
                 ...
HENDERSON             1
Niles                 1
Richmond              1
Covington             1
GILBERT               1
Name: count, Length: 288, dtype: int64

In [301]:
# Lower case conversion

msk = df1['Principal_Investigator_2_City'].notna()
df1.loc[msk, 'Principal_Investigator_2_City'] = df1.loc[msk, 'Principal_Investigator_2_City'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_2_City']= df1.loc[msk,'Principal_Investigator_2_City'].apply(lambda x: x.lower())
df1['Principal_Investigator_2_City'].nunique()

231

In [302]:
df1['Principal_Investigator_2_State'].value_counts(dropna=False)

Principal_Investigator_2_State
NaN    1026300
PA         421
TX         225
FL         161
CA         126
OH         123
NY         111
CT          92
GA          92
MA          75
SC          65
TN          62
IL          48
MD          47
MN          41
NJ          39
IN          38
WA          36
MI          35
AL          29
AZ          29
OK          27
OR          24
NC          21
VA          21
KS          20
CO          18
MO          16
NE          16
MT          15
WI          13
NH          12
DC          11
SD          11
RI          11
UT           8
LA           8
KY           7
NV           6
IA           2
PR           2
VT           1
HI           1
ID           1
MS           1
ME           1
ND           1
DE           1
AK           1
Name: count, dtype: int64

In [303]:
df1['Principal_Investigator_2_Zip_Code'].value_counts(dropna=False)

Principal_Investigator_2_Zip_Code
NaN           1026300
19104-2640        363
06519-1304         80
29572              58
77584-8075         42
               ...
63141               1
33136-2107          1
23507               1
01655               1
46219               1
Name: count, Length: 416, dtype: int64

In [304]:
df1['Principal_Investigator_2_Country'].value_counts(dropna=False)

Principal_Investigator_2_Country
NaN              1026300
United States       2172
Name: count, dtype: int64

In [305]:
df1['Principal_Investigator_2_Province'].value_counts(dropna=False)

Principal_Investigator_2_Province
NaN    1028472
Name: count, dtype: int64

In [306]:
df1['Principal_Investigator_2_Postal_Code'].value_counts(dropna=False)

Principal_Investigator_2_Postal_Code
NaN    1028472
Name: count, dtype: int64

In [307]:
# reverify after lower case conversion

df1[['Principal_Investigator_2_Covered_Recipient_Type','Principal_Investigator_2_Profile_ID',
    'Principal_Investigator_2_NPI', 'Principal_Investigator_2_First_Name',
    'Principal_Investigator_2_Middle_Name', 'Principal_Investigator_2_Last_Name',
    'Principal_Investigator_2_Name_Suffix', 'Principal_Investigator_2_Business_Street_Address_Line1',
    'Principal_Investigator_2_Business_Street_Address_Line2', 'Principal_Investigator_2_City',
    'Principal_Investigator_2_State','Principal_Investigator_2_Zip_Code',
    'Principal_Investigator_2_Country','Principal_Investigator_2_Province',
     'Principal_Investigator_2_Postal_Code']].describe(include=object)

,Principal_Investigator_2_Covered_Recipient_Type,Principal_Investigator_2_Profile_ID,Principal_Investigator_2_NPI,Principal_Investigator_2_First_Name,Principal_Investigator_2_Middle_Name,Principal_Investigator_2_Last_Name,Principal_Investigator_2_Name_Suffix,Principal_Investigator_2_Business_Street_Address_Line1,Principal_Investigator_2_Business_Street_Address_Line2,Principal_Investigator_2_City,Principal_Investigator_2_State,Principal_Investigator_2_Zip_Code,Principal_Investigator_2_Country
count,2172,2172.0,2.169000e+03,2172,263,2172,21,2172,844,2172,2172,2172,2172
unique,2,532.0,5.300000e+02,374,68,498,3,500,118,231,48,415,1
top,Covered Recipient Physician,24935.0,1.558534e+09,sameer,n,khandhar,IV,51 N 39TH ST,PHI 2C,philadelphia,PA,19104-2640,United States
freq,2168,363.0,3.630000e+02,363,33,363,13,363,363,385,421,363,2172

In [308]:

df1[['Principal_Investigator_2_Primary_Type_1',
     'Principal_Investigator_2_Primary_Type_2', 'Principal_Investigator_2_Primary_Type_3',
     'Principal_Investigator_2_Primary_Type_4', 'Principal_Investigator_2_Primary_Type_5',
     'Principal_Investigator_2_Primary_Type_6']].describe(include=object)

       Principal_Investigator_2_Primary_Type_1
count                                     2172
unique                                       5
top                             Medical Doctor
freq                                      2097

In [309]:

df1[['Principal_Investigator_2_Primary_Type_1',
     'Principal_Investigator_2_Primary_Type_2', 'Principal_Investigator_2_Primary_Type_3',
     'Principal_Investigator_2_Primary_Type_4', 'Principal_Investigator_2_Primary_Type_5',
     'Principal_Investigator_2_Primary_Type_6']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Principal_Investigator_2_Primary_Type_1  2172 non-null   object
 1   Principal_Investigator_2_Primary_Type_2  0 non-null      float64
 2   Principal_Investigator_2_Primary_Type_3  0 non-null      float64
 3   Principal_Investigator_2_Primary_Type_4  0 non-null      float64
 4   Principal_Investigator_2_Primary_Type_5  0 non-null      float64
 5   Principal_Investigator_2_Primary_Type_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [310]:
df1['Principal_Investigator_2_Primary_Type_1'].value_counts(dropna=False)

Principal_Investigator_2_Primary_Type_1
NaN                     1026300
Medical Doctor             2097
Doctor of Osteopathy         63
Doctor of Optometry           7
Nurse Practitioner            4
Doctor of Dentistry           1
Name: count, dtype: int64

In [311]:

df1[['Principal_Investigator_2_Specialty_1', 'Principal_Investigator_2_Specialty_2', 
     'Principal_Investigator_2_Specialty_3', 'Principal_Investigator_2_Specialty_4',
     'Principal_Investigator_2_Specialty_5', 'Principal_Investigator_2_Specialty_6',
    ]].describe(include=object)

                     Principal_Investigator_2_Specialty_1
count                                                2172
unique                                                 66
top     Allopathic & Osteopathic Physicians|Internal M...
freq                                                  543

In [312]:

df1[['Principal_Investigator_2_Specialty_1', 'Principal_Investigator_2_Specialty_2', 
     'Principal_Investigator_2_Specialty_3', 'Principal_Investigator_2_Specialty_4',
     'Principal_Investigator_2_Specialty_5', 'Principal_Investigator_2_Specialty_6',
    ]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Principal_Investigator_2_Specialty_1  2172 non-null   object
 1   Principal_Investigator_2_Specialty_2  0 non-null      float64
 2   Principal_Investigator_2_Specialty_3  0 non-null      float64
 3   Principal_Investigator_2_Specialty_4  0 non-null      float64
 4   Principal_Investigator_2_Specialty_5  0 non-null      float64
 5   Principal_Investigator_2_Specialty_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [313]:
df1['Principal_Investigator_2_Specialty_1'].describe()

count                                                  2172
unique                                                   66
top       Allopathic & Osteopathic Physicians|Internal M...
freq                                                    543
Name: Principal_Investigator_2_Specialty_1, dtype: object

In [314]:
df1['Principal_Investigator_2_Specialty_1'].value_counts(dropna=False)

Principal_Investigator_2_Specialty_1
NaN                                                                                       1026300
Allopathic & Osteopathic Physicians|Internal Medicine|Interventional Cardiology               543
Allopathic & Osteopathic Physicians|Internal Medicine|Cardiovascular Disease                  267
Allopathic & Osteopathic Physicians|Internal Medicine|Hematology & Oncology                   189
Allopathic & Osteopathic Physicians|Thoracic Surgery (Cardiothoracic Vascular Surgery)        116
                                                                                           ...
Allopathic & Osteopathic Physicians|Orthopaedic Surgery|Hand Surgery                            1
Allopathic & Osteopathic Physicians|Pediatrics|Pediatric Endocrinology                          1
Allopathic & Osteopathic Physicians|Radiology|Radiation Oncology                                1
Allopathic & Osteopathic Physicians|Pediatrics|Pediatric Pulmonology                            1
Allopathic & Osteopathic Physicians|Nuclear Medicine                                            1
Name: count, Length: 67, dtype: int64

In [315]:

df1[['Principal_Investigator_2_License_State_code1', 'Principal_Investigator_2_License_State_code2',
    'Principal_Investigator_2_License_State_code3', 
     'Principal_Investigator_2_License_State_code4']].describe()

,Principal_Investigator_2_License_State_code1,Principal_Investigator_2_License_State_code2,Principal_Investigator_2_License_State_code3,Principal_Investigator_2_License_State_code4
count,2172,127,33,5
unique,46,21,9,3
top,NJ,NY,TN,SC
freq,407,27,12,2

In [316]:
df1['Principal_Investigator_2_License_State_code5'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Principal_Investigator_2_License_State_code5, dtype: float64

In [317]:
df1['Principal_Investigator_2_License_State_code1'].value_counts(dropna=False)

Principal_Investigator_2_License_State_code1
NaN    1026300
NJ         407
FL         196
TX         158
CA         135
CT         112
OH          90
MA          89
GA          85
IL          77
NY          65
SC          65
AZ          60
MN          48
MD          47
IN          45
LA          38
TN          36
AL          36
KS          34
MO          33
PA          31
NC          31
KY          25
WA          24
MI          24
CO          22
DC          18
OK          18
VA          16
IA          15
NE          12
WI          12
UT          12
OR          12
SD          10
RI           8
DE           5
NV           5
NH           5
HI           3
PR           2
ID           2
MS           1
ME           1
AR           1
AK           1
Name: count, dtype: int64

In [318]:
df1['Principal_Investigator_2_License_State_code2'].value_counts(dropna=False)

Principal_Investigator_2_License_State_code2
NaN    1028345
NY          27
OH          13
TX          11
WA          11
MI          11
MN           8
SC           5
NJ           5
PA           5
FL           4
RI           4
NC           3
OR           3
WI           3
VA           3
CA           2
IL           2
MA           2
LA           2
GA           2
MO           1
Name: count, dtype: int64

In [319]:
df1['Principal_Investigator_2_License_State_code3'].value_counts(dropna=False)

Principal_Investigator_2_License_State_code3
NaN    1028439
TN          12
PA           8
OH           3
NJ           2
WI           2
NY           2
NM           2
NC           1
TX           1
Name: count, dtype: int64

In [320]:
df1['Principal_Investigator_2_License_State_code4'].value_counts(dropna=False)

Principal_Investigator_2_License_State_code4
NaN    1028467
SC           2
TX           2
WV           1
Name: count, dtype: int64

In [321]:
df1[['Principal_Investigator_3_Covered_Recipient_Type','Principal_Investigator_3_Profile_ID',
    'Principal_Investigator_3_NPI', 'Principal_Investigator_3_First_Name',
    'Principal_Investigator_3_Middle_Name', 'Principal_Investigator_3_Last_Name',
    'Principal_Investigator_3_Name_Suffix', 'Principal_Investigator_3_Business_Street_Address_Line1',
    'Principal_Investigator_3_Business_Street_Address_Line2', 'Principal_Investigator_3_City',
    'Principal_Investigator_3_State','Principal_Investigator_3_Zip_Code',
    'Principal_Investigator_3_Country','Principal_Investigator_3_Province',
     'Principal_Investigator_3_Postal_Code']].describe(include=object)

,Principal_Investigator_3_Covered_Recipient_Type,Principal_Investigator_3_First_Name,Principal_Investigator_3_Middle_Name,Principal_Investigator_3_Last_Name,Principal_Investigator_3_Name_Suffix,Principal_Investigator_3_Business_Street_Address_Line1,Principal_Investigator_3_Business_Street_Address_Line2,Principal_Investigator_3_City,Principal_Investigator_3_State,Principal_Investigator_3_Zip_Code,Principal_Investigator_3_Country
count,251,251,35,251,1,251,61,251,251,251,251
unique,2,75,16,82,1,85,15,74,28,83,1
top,Covered Recipient Physician,David,C,Fiorella,II,HSC T12 Rm 080,Suite 3200,Stony Brook,NY,11794,United States
freq,249,33,18,33,1,33,18,33,38,33,251

In [322]:
df1[['Principal_Investigator_3_Covered_Recipient_Type','Principal_Investigator_3_Profile_ID',
    'Principal_Investigator_3_NPI', 'Principal_Investigator_3_First_Name',
    'Principal_Investigator_3_Middle_Name', 'Principal_Investigator_3_Last_Name',
    'Principal_Investigator_3_Name_Suffix', 'Principal_Investigator_3_Business_Street_Address_Line1',
    'Principal_Investigator_3_Business_Street_Address_Line2', 'Principal_Investigator_3_City',
    'Principal_Investigator_3_State','Principal_Investigator_3_Zip_Code',
    'Principal_Investigator_3_Country','Principal_Investigator_3_Province',
     'Principal_Investigator_3_Postal_Code']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 15 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Principal_Investigator_3_Covered_Recipient_Type         251 non-null    object
 1   Principal_Investigator_3_Profile_ID                     251 non-null    float64
 2   Principal_Investigator_3_NPI                            251 non-null    float64
 3   Principal_Investigator_3_First_Name                     251 non-null    object
 4   Principal_Investigator_3_Middle_Name                    35 non-null     object
 5   Principal_Investigator_3_Last_Name                      251 non-null    object
 6   Principal_Investigator_3_Name_Suffix                    1 non-null      object
 7   Principal_Investigator_3_Business_Street_Address_Line1  251 non-null    object
 8   Principal_Investigator_3_Business_Street_Address_Line2  61 non-null     object
 9   Principal_Investigator_3_City                           251 non-null    object
 10  Principal_Investigator_3_State                          251 non-null    object
 11  Principal_Investigator_3_Zip_Code                       251 non-null    object
 12  Principal_Investigator_3_Country                        251 non-null    object
 13  Principal_Investigator_3_Province                       0 non-null      float64
 14  Principal_Investigator_3_Postal_Code                    0 non-null      float64
dtypes: float64(4), object(11)
memory usage: 117.7+ MB

In [323]:
df1[['Principal_Investigator_3_Covered_Recipient_Type']].value_counts(dropna=False)

Principal_Investigator_3_Covered_Recipient_Type
NaN                                                1028221
Covered Recipient Physician                            249
Covered Recipient Non-Physician Practitioner             2
Name: count, dtype: int64

In [324]:
df1['Principal_Investigator_3_Profile_ID']=df1['Principal_Investigator_3_Profile_ID'].astype(object)

In [325]:
df1['Principal_Investigator_3_Profile_ID'].value_counts(dropna=False)

Principal_Investigator_3_Profile_ID
NaN          1028221
247322.0          33
336124.0          18
265293.0          18
305809.0          12
              ...
242650.0           1
167264.0           1
5275.0             1
1214613.0          1
716637.0           1
Name: count, Length: 86, dtype: int64

In [326]:
df1['Principal_Investigator_3_Profile_ID']=df1['Principal_Investigator_3_Profile_ID'].astype(object)

In [327]:
df1['Principal_Investigator_3_NPI'].value_counts(dropna=False)

Principal_Investigator_3_NPI
NaN             1028221
1.467416e+09         33
1.417132e+09         18
1.851362e+09         18
1.730178e+09         12
                 ...
1.356395e+09          1
1.699746e+09          1
1.114931e+09          1
1.902821e+09          1
1.407152e+09          1
Name: count, Length: 86, dtype: int64

In [328]:
# Lower case conversion

msk = df1['Principal_Investigator_3_First_Name'].notna()
df1.loc[msk, 'Principal_Investigator_3_First_Name'] = df1.loc[msk, 'Principal_Investigator_3_First_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_3_First_Name']= df1.loc[msk,'Principal_Investigator_3_First_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_3_First_Name'].nunique()

72

In [329]:
df1['Principal_Investigator_3_First_Name'].value_counts(dropna=False)

Principal_Investigator_3_First_Name
NaN        1028221
david           34
john            21
nainesh         18
bruce           12
            ...
nikhil           1
ricardo          1
armen            1
gregg            1
daniele          1
Name: count, Length: 73, dtype: int64

In [330]:
# Lower case conversion

msk = df1['Principal_Investigator_3_Middle_Name'].notna()
df1.loc[msk, 'Principal_Investigator_3_Middle_Name'] = df1.loc[msk, 'Principal_Investigator_3_Middle_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_3_Middle_Name']= df1.loc[msk,'Principal_Investigator_3_Middle_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_3_Middle_Name'].nunique()

16

In [331]:
df1['Principal_Investigator_3_Middle_Name'].value_counts(dropna=False)

Principal_Investigator_3_Middle_Name
NaN        1028437
c               18
jovelle          2
h                2
z                1
duc              1
adam             1
m                1
p                1
pravin           1
daniel           1
j                1
labib            1
marc             1
b                1
vaiden           1
j.               1
Name: count, dtype: int64

In [332]:
# Lower case conversion

msk = df1['Principal_Investigator_3_Last_Name'].notna()
df1.loc[msk, 'Principal_Investigator_3_Last_Name'] = df1.loc[msk, 'Principal_Investigator_3_Last_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_3_Last_Name']= df1.loc[msk,'Principal_Investigator_3_Last_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_3_Last_Name'].nunique()

81

In [333]:
df1['Principal_Investigator_3_Last_Name'].value_counts(dropna=False)

Principal_Investigator_3_Last_Name
NaN            1028221
fiorella            33
patel               20
riddick             18
thorla              12
                ...
munshi               1
hanel                1
wright               1
khachatryan          1
marin                1
Name: count, Length: 82, dtype: int64

In [334]:
# Lower case conversion

msk = df1['Principal_Investigator_3_Name_Suffix'].notna()
df1.loc[msk, 'Principal_Investigator_3_Name_Suffix'] = df1.loc[msk, 'Principal_Investigator_3_Name_Suffix'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_3_Name_Suffix']= df1.loc[msk,'Principal_Investigator_3_Name_Suffix'].apply(lambda x: x.lower())
df1['Principal_Investigator_3_Name_Suffix'].nunique()

1

In [335]:
df1['Principal_Investigator_3_Name_Suffix'].value_counts(dropna=False)

Principal_Investigator_3_Name_Suffix
NaN    1028471
ii           1
Name: count, dtype: int64

In [336]:
df1['Principal_Investigator_3_Business_Street_Address_Line1'].value_counts(dropna=False)

Principal_Investigator_3_Business_Street_Address_Line1
NaN                             1028221
HSC T12 Rm 080                       33
4412 Sheppard Pl                     18
1255 S Cedar Crest Blvd              18
10154 JEFFERSON HWY                  12
                                 ...
800 PRUDENTIAL DRIVE                  1
3000 Medical Park Dr Ste 250          1
3584 W 9000 S STE 405                 1
133 Brookline Ave                     1
PO Box 8                              1
Name: count, Length: 86, dtype: int64

In [337]:
df1['Principal_Investigator_3_Business_Street_Address_Line2'].value_counts(dropna=False)

Principal_Investigator_3_Business_Street_Address_Line2
NaN                         1028411
Suite 3200                       18
STE 501                          11
--                               10
DEPT OBGYN UHN-70 OHSU            3
PAVILION 1, ROOM 172              3
Suite 308                         3
112                               3
SUITE 350                         2
BUILDING 10, ROOM B3B69F          2
Suite 204                         1
APT. 23H                          1
Suite 300                         1
WP-522                            1
TOWER B 11TH FLOOR                1
Ste 400                           1
Name: count, dtype: int64

In [338]:
# Lower case conversion

msk = df1['Principal_Investigator_3_City'].notna()
df1.loc[msk, 'Principal_Investigator_3_City'] = df1.loc[msk, 'Principal_Investigator_3_City'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_3_City']= df1.loc[msk,'Principal_Investigator_3_City'].apply(lambda x: x.lower())
df1['Principal_Investigator_3_City'].nunique()

67

In [339]:
df1['Principal_Investigator_3_City'].value_counts(dropna=False)

Principal_Investigator_3_City
NaN             1028221
stony brook          33
allentown            18
nashville            18
dallas               13
                 ...
hattiesburg           1
jacksonville          1
tampa                 1
west jordan           1
thornton              1
Name: count, Length: 68, dtype: int64

In [340]:
df1['Principal_Investigator_3_State'].value_counts(dropna=False)

Principal_Investigator_3_State
NaN    1028221
NY          38
TX          33
FL          24
TN          19
PA          18
CA          14
OH          12
LA          12
WA          11
MA          11
IL           8
MD           7
MO           6
MN           6
AL           5
NC           5
GA           3
OR           3
AZ           3
CO           3
MI           2
VA           2
MS           1
UT           1
OK           1
SC           1
KY           1
DC           1
Name: count, dtype: int64

In [341]:
df1['Principal_Investigator_3_Zip_Code'].value_counts(dropna=False)

Principal_Investigator_3_Zip_Code
NaN           1028221
11794              33
18103              18
37205              18
70809-2725         12
               ...
39401               1
32207               1
33613               1
84088               1
27702               1
Name: count, Length: 84, dtype: int64

In [342]:
df1['Principal_Investigator_3_Country'].value_counts(dropna=False)

Principal_Investigator_3_Country
NaN              1028221
United States        251
Name: count, dtype: int64

In [343]:
df1['Principal_Investigator_3_Province'].value_counts(dropna=False)

Principal_Investigator_3_Province
NaN    1028472
Name: count, dtype: int64

In [344]:
df1['Principal_Investigator_3_Postal_Code'].value_counts(dropna=False)

Principal_Investigator_3_Postal_Code
NaN    1028472
Name: count, dtype: int64

In [345]:
# reverify


df1[['Principal_Investigator_3_Covered_Recipient_Type','Principal_Investigator_3_Profile_ID',
    'Principal_Investigator_3_NPI', 'Principal_Investigator_3_First_Name',
    'Principal_Investigator_3_Middle_Name', 'Principal_Investigator_3_Last_Name',
    'Principal_Investigator_3_Name_Suffix', 'Principal_Investigator_3_Business_Street_Address_Line1',
    'Principal_Investigator_3_Business_Street_Address_Line2', 'Principal_Investigator_3_City',
    'Principal_Investigator_3_State','Principal_Investigator_3_Zip_Code',
    'Principal_Investigator_3_Country','Principal_Investigator_3_Province',
     'Principal_Investigator_3_Postal_Code']].describe(include=object)

,Principal_Investigator_3_Covered_Recipient_Type,Principal_Investigator_3_Profile_ID,Principal_Investigator_3_First_Name,Principal_Investigator_3_Middle_Name,Principal_Investigator_3_Last_Name,Principal_Investigator_3_Name_Suffix,Principal_Investigator_3_Business_Street_Address_Line1,Principal_Investigator_3_Business_Street_Address_Line2,Principal_Investigator_3_City,Principal_Investigator_3_State,Principal_Investigator_3_Zip_Code,Principal_Investigator_3_Country
count,251,251.0,251,35,251,1,251,61,251,251,251,251
unique,2,85.0,72,16,81,1,85,15,67,28,83,1
top,Covered Recipient Physician,247322.0,david,c,fiorella,ii,HSC T12 Rm 080,Suite 3200,stony brook,NY,11794,United States
freq,249,33.0,34,18,33,1,33,18,33,38,33,251

In [346]:
df1[['Principal_Investigator_3_Primary_Type_1',
     'Principal_Investigator_3_Primary_Type_2', 'Principal_Investigator_3_Primary_Type_3',
     'Principal_Investigator_3_Primary_Type_4', 'Principal_Investigator_3_Primary_Type_5',
     'Principal_Investigator_3_Primary_Type_6']].describe(include=object)

       Principal_Investigator_3_Primary_Type_1
count                                      251
unique                                       4
top                             Medical Doctor
freq                                       243

In [347]:
df1[['Principal_Investigator_3_Primary_Type_1',
     'Principal_Investigator_3_Primary_Type_2', 'Principal_Investigator_3_Primary_Type_3',
     'Principal_Investigator_3_Primary_Type_4', 'Principal_Investigator_3_Primary_Type_5',
     'Principal_Investigator_3_Primary_Type_6']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Principal_Investigator_3_Primary_Type_1  251 non-null    object
 1   Principal_Investigator_3_Primary_Type_2  0 non-null      float64
 2   Principal_Investigator_3_Primary_Type_3  0 non-null      float64
 3   Principal_Investigator_3_Primary_Type_4  0 non-null      float64
 4   Principal_Investigator_3_Primary_Type_5  0 non-null      float64
 5   Principal_Investigator_3_Primary_Type_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [348]:
df1['Principal_Investigator_3_Primary_Type_1'].value_counts(dropna=False)

Principal_Investigator_3_Primary_Type_1
NaN                             1028221
Medical Doctor                      243
Doctor of Osteopathy                  5
Nurse Practitioner                    2
Doctor of Podiatric Medicine          1
Name: count, dtype: int64

In [349]:
df1[['Principal_Investigator_3_Specialty_1', 'Principal_Investigator_3_Specialty_2', 
     'Principal_Investigator_3_Specialty_3', 'Principal_Investigator_3_Specialty_4',
     'Principal_Investigator_3_Specialty_5', 'Principal_Investigator_3_Specialty_6',
    ]].describe(include=object)

                     Principal_Investigator_3_Specialty_1
count                                                 251
unique                                                 30
top     Allopathic & Osteopathic Physicians|Radiology|...
freq                                                   33

In [350]:
df1[['Principal_Investigator_3_Specialty_1', 'Principal_Investigator_3_Specialty_2', 
     'Principal_Investigator_3_Specialty_3', 'Principal_Investigator_3_Specialty_4',
     'Principal_Investigator_3_Specialty_5', 'Principal_Investigator_3_Specialty_6',
    ]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Principal_Investigator_3_Specialty_1  251 non-null    object
 1   Principal_Investigator_3_Specialty_2  0 non-null      float64
 2   Principal_Investigator_3_Specialty_3  0 non-null      float64
 3   Principal_Investigator_3_Specialty_4  0 non-null      float64
 4   Principal_Investigator_3_Specialty_5  0 non-null      float64
 5   Principal_Investigator_3_Specialty_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [351]:
df1[['Principal_Investigator_3_Specialty_1']].describe()

                     Principal_Investigator_3_Specialty_1
count                                                 251
unique                                                 30
top     Allopathic & Osteopathic Physicians|Radiology|...
freq                                                   33

In [352]:
df1[['Principal_Investigator_3_Specialty_1']].value_counts(dropna=False)

Principal_Investigator_3_Specialty_1
NaN                                                                                         1028221
Allopathic & Osteopathic Physicians|Radiology|Neuroradiology                                     33
Allopathic & Osteopathic Physicians|Internal Medicine|Cardiovascular Disease                     29
Allopathic & Osteopathic Physicians|Internal Medicine|Interventional Cardiology                  29
Allopathic & Osteopathic Physicians|Internal Medicine|Nephrology                                 27
Allopathic & Osteopathic Physicians|Internal Medicine|Hematology & Oncology                      23
Allopathic & Osteopathic Physicians|Radiology|Diagnostic Radiology                               19
Allopathic & Osteopathic Physicians|Dermatology                                                  15
Allopathic & Osteopathic Physicians|Radiology|Pediatric Radiology                                11
Allopathic & Osteopathic Physicians|Psychiatry & Neurology|Neurology                              7
Allopathic & Osteopathic Physicians|Orthopaedic Surgery|Orthopaedic Surgery of the Spine          7
Allopathic & Osteopathic Physicians|Orthopaedic Surgery                                           5
Allopathic & Osteopathic Physicians|Anesthesiology                                                5
Allopathic & Osteopathic Physicians|Internal Medicine|Medical Oncology                            5
Allopathic & Osteopathic Physicians|Psychiatry & Neurology|Addiction Medicine                     4
Allopathic & Osteopathic Physicians|Neurological Surgery                                          4
Allopathic & Osteopathic Physicians|Pediatrics                                                    4
Allopathic & Osteopathic Physicians|Obstetrics & Gynecology                                       4
Allopathic & Osteopathic Physicians|Pediatrics|Pediatric Nephrology                               3
Allopathic & Osteopathic Physicians|Preventive Medicine|Aerospace Medicine                        3
Physician Assistants & Advanced Practice Nursing Providers|Nurse Practitioner|Acute Care          2
Allopathic & Osteopathic Physicians|Surgery                                                       2
Allopathic & Osteopathic Physicians|Internal Medicine                                             2
Allopathic & Osteopathic Physicians|Internal Medicine|Hematology                                  1
Podiatric Medicine & Surgery Service Providers|Podiatrist|Foot & Ankle Surgery                    1
Allopathic & Osteopathic Physicians|Ophthalmology                                                 1
Allopathic & Osteopathic Physicians|Internal Medicine|Rheumatology                                1
Allopathic & Osteopathic Physicians|Pediatrics|Pediatric Hematology-Oncology                      1
Allopathic & Osteopathic Physicians|Pediatrics|Pediatric Gastroenterology                         1
Allopathic & Osteopathic Physicians|Orthopaedic Surgery|Sports Medicine                           1
Allopathic & Osteopathic Physicians|Orthopaedic Surgery|Orthopaedic Trauma                        1
Name: count, dtype: int64

In [353]:
df1[['Principal_Investigator_3_License_State_code1', 'Principal_Investigator_3_License_State_code2',
    'Principal_Investigator_3_License_State_code3', 'Principal_Investigator_3_License_State_code4',
   ]].describe()

,Principal_Investigator_3_License_State_code1,Principal_Investigator_3_License_State_code2,Principal_Investigator_3_License_State_code3,Principal_Investigator_3_License_State_code4
count,251,66,2,2
unique,26,6,1,1
top,AZ,NY,RI,TX
freq,36,30,2,2

In [354]:
df1[['Principal_Investigator_3_License_State_code1', 'Principal_Investigator_3_License_State_code2',
    'Principal_Investigator_3_License_State_code3', 'Principal_Investigator_3_License_State_code4',
    'Principal_Investigator_3_License_State_code5']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 5 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Principal_Investigator_3_License_State_code1  251 non-null    object
 1   Principal_Investigator_3_License_State_code2  66 non-null     object
 2   Principal_Investigator_3_License_State_code3  2 non-null      object
 3   Principal_Investigator_3_License_State_code4  2 non-null      object
 4   Principal_Investigator_3_License_State_code5  0 non-null      float64
dtypes: float64(1), object(4)
memory usage: 39.2+ MB

In [355]:
df1[ 'Principal_Investigator_3_License_State_code5'].value_counts(dropna=False)

Principal_Investigator_3_License_State_code5
NaN    1028472
Name: count, dtype: int64

In [356]:
df1['Principal_Investigator_3_License_State_code1'].value_counts(dropna=False)

Principal_Investigator_3_License_State_code1
NaN    1028221
AZ          36
FL          29
PA          29
TX          26
TN          18
CA          18
KY          13
LA          12
MA          12
IL           8
MD           7
MO           6
CO           6
GA           5
AL           5
NY           4
NC           4
OR           3
VA           2
DC           2
SC           1
MN           1
NJ           1
MS           1
MI           1
WA           1
Name: count, dtype: int64

In [357]:
df1['Principal_Investigator_3_License_State_code2'].value_counts(dropna=False)

Principal_Investigator_3_License_State_code2
NaN    1028406
NY          30
OH          13
WA           9
MN           6
FL           5
TX           3
Name: count, dtype: int64

In [358]:
df1['Principal_Investigator_3_License_State_code3'].value_counts(dropna=False)

Principal_Investigator_3_License_State_code3
NaN    1028470
RI           2
Name: count, dtype: int64

In [359]:
df1['Principal_Investigator_3_License_State_code4'].value_counts(dropna=False)

Principal_Investigator_3_License_State_code4
NaN    1028470
TX           2
Name: count, dtype: int64

In [360]:
df1[['Principal_Investigator_4_Covered_Recipient_Type','Principal_Investigator_4_Profile_ID',
    'Principal_Investigator_4_NPI', 'Principal_Investigator_4_First_Name',
    'Principal_Investigator_4_Middle_Name', 'Principal_Investigator_4_Last_Name',
    'Principal_Investigator_4_Name_Suffix', 'Principal_Investigator_4_Business_Street_Address_Line1',
    'Principal_Investigator_4_Business_Street_Address_Line2', 'Principal_Investigator_4_City',
    'Principal_Investigator_4_State','Principal_Investigator_4_Zip_Code',
    'Principal_Investigator_4_Country','Principal_Investigator_4_Province',
     'Principal_Investigator_4_Postal_Code']].describe(include=object)

,Principal_Investigator_4_Covered_Recipient_Type,Principal_Investigator_4_First_Name,Principal_Investigator_4_Middle_Name,Principal_Investigator_4_Last_Name,Principal_Investigator_4_Name_Suffix,Principal_Investigator_4_Business_Street_Address_Line1,Principal_Investigator_4_Business_Street_Address_Line2,Principal_Investigator_4_City,Principal_Investigator_4_State,Principal_Investigator_4_Zip_Code,Principal_Investigator_4_Country
count,94,94,34,94,18,94,9,94,94,94,94
unique,1,33,5,34,1,34,4,32,20,34,1
top,Covered Recipient Physician,HAL,S,WASSERMAN,MD,100 Reserve Rd,--,Danbury,CT,06810,United States
freq,94,18,30,18,18,18,3,18,25,18,94

In [361]:
df1[['Principal_Investigator_4_Covered_Recipient_Type','Principal_Investigator_4_Profile_ID',
    'Principal_Investigator_4_NPI', 'Principal_Investigator_4_First_Name',
    'Principal_Investigator_4_Middle_Name', 'Principal_Investigator_4_Last_Name',
    'Principal_Investigator_4_Name_Suffix', 'Principal_Investigator_4_Business_Street_Address_Line1',
    'Principal_Investigator_4_Business_Street_Address_Line2', 'Principal_Investigator_4_City',
    'Principal_Investigator_4_State','Principal_Investigator_4_Zip_Code',
    'Principal_Investigator_4_Country','Principal_Investigator_4_Province',
     'Principal_Investigator_4_Postal_Code']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 15 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Principal_Investigator_4_Covered_Recipient_Type         94 non-null     object
 1   Principal_Investigator_4_Profile_ID                     94 non-null     float64
 2   Principal_Investigator_4_NPI                            94 non-null     float64
 3   Principal_Investigator_4_First_Name                     94 non-null     object
 4   Principal_Investigator_4_Middle_Name                    34 non-null     object
 5   Principal_Investigator_4_Last_Name                      94 non-null     object
 6   Principal_Investigator_4_Name_Suffix                    18 non-null     object
 7   Principal_Investigator_4_Business_Street_Address_Line1  94 non-null     object
 8   Principal_Investigator_4_Business_Street_Address_Line2  9 non-null      object
 9   Principal_Investigator_4_City                           94 non-null     object
 10  Principal_Investigator_4_State                          94 non-null     object
 11  Principal_Investigator_4_Zip_Code                       94 non-null     object
 12  Principal_Investigator_4_Country                        94 non-null     object
 13  Principal_Investigator_4_Province                       0 non-null      float64
 14  Principal_Investigator_4_Postal_Code                    0 non-null      float64
dtypes: float64(4), object(11)
memory usage: 117.7+ MB

In [362]:
df1['Principal_Investigator_4_Covered_Recipient_Type'].value_counts(dropna=False)

Principal_Investigator_4_Covered_Recipient_Type
NaN                            1028378
Covered Recipient Physician         94
Name: count, dtype: int64

In [363]:
df1['Principal_Investigator_4_Profile_ID']=df1['Principal_Investigator_4_Profile_ID'].astype(object)

In [364]:
df1['Principal_Investigator_4_Profile_ID'].describe()

count       94.0
unique      34.0
top       6611.0
freq        18.0
Name: Principal_Investigator_4_Profile_ID, dtype: float64

In [365]:
df1['Principal_Investigator_4_Profile_ID'].value_counts(dropna=False)

Principal_Investigator_4_Profile_ID
NaN           1028378
6611.0             18
1141896.0          11
262262.0           11
11565533.0         11
353473.0            6
552297.0            4
191836.0            3
22369.0             3
614863.0            2
916545.0            1
295252.0            1
1183755.0           1
661865.0            1
306200.0            1
515190.0            1
30229.0             1
290669.0            1
987232.0            1
110359.0            1
1399272.0           1
51160.0             1
713931.0            1
635572.0            1
68860.0             1
189527.0            1
191169.0            1
699232.0            1
380039.0            1
343154.0            1
290086.0            1
4219435.0           1
70352.0             1
482891.0            1
268447.0            1
Name: count, dtype: int64

In [366]:
df1['Principal_Investigator_4_NPI']=df1['Principal_Investigator_4_NPI'].astype(object)

In [367]:
df1['Principal_Investigator_4_NPI'].value_counts(dropna=False)

Principal_Investigator_4_NPI
NaN             1028378
1154358356.0         18
1346253598.0         11
1790714400.0         11
1366735672.0         11
1770875817.0          6
1649243742.0          4
1215975172.0          3
1487710893.0          3
1841218070.0          2
1437259215.0          1
1508065681.0          1
1821049255.0          1
1487692869.0          1
1750542056.0          1
1326205303.0          1
1659596179.0          1
1417940750.0          1
1912260340.0          1
1427059682.0          1
1306145859.0          1
1124237912.0          1
1275759581.0          1
1568623072.0          1
1528006731.0          1
1174726384.0          1
1205818457.0          1
1780835769.0          1
1609061837.0          1
1568664480.0          1
1396888947.0          1
1891038204.0          1
1558338053.0          1
1194787176.0          1
1902842412.0          1
Name: count, dtype: int64

In [368]:
df1['Principal_Investigator_4_NPI'].describe()

count     9.400000e+01
unique    3.400000e+01
top       1.154358e+09
freq      1.800000e+01
Name: Principal_Investigator_4_NPI, dtype: float64

In [369]:
# Lower case conversion

msk = df1['Principal_Investigator_4_First_Name'].notna()
df1.loc[msk, 'Principal_Investigator_4_First_Name'] = df1.loc[msk, 'Principal_Investigator_4_First_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_4_First_Name']= df1.loc[msk,'Principal_Investigator_4_First_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_4_First_Name'].nunique()

33

In [370]:
df1['Principal_Investigator_4_First_Name'].value_counts(dropna=False)

Principal_Investigator_4_First_Name
NaN          1028378
hal               18
beth              11
amir              11
bart              11
monzurul           6
june               4
matthew            3
ashvin             3
john               2
joel               2
suman              1
sharad             1
sita               1
jay                1
brett              1
sareena            1
pierce             1
jeff               1
armonde            1
alexander          1
jad                1
raymond            1
raghu              1
hyun               1
vivek              1
harvey             1
david              1
suzanne            1
dana               1
sonia              1
dirk               1
anthony            1
jesus              1
Name: count, dtype: int64

In [371]:
# Lower case conversion

msk = df1['Principal_Investigator_4_Middle_Name'].notna()
df1.loc[msk, 'Principal_Investigator_4_Middle_Name'] = df1.loc[msk, 'Principal_Investigator_4_Middle_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_4_Middle_Name']= df1.loc[msk,'Principal_Investigator_4_Middle_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_4_Middle_Name'].nunique()

5

In [372]:
df1['Principal_Investigator_4_Middle_Name'].value_counts(dropna=False)

Principal_Investigator_4_Middle_Name
NaN         1028438
s                30
jun               1
meredith          1
reim              1
e                 1
Name: count, dtype: int64

In [373]:
# Lower case conversion

msk = df1['Principal_Investigator_4_Last_Name'].notna()
df1.loc[msk, 'Principal_Investigator_4_Last_Name'] = df1.loc[msk, 'Principal_Investigator_4_Last_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_4_Last_Name']= df1.loc[msk,'Principal_Investigator_4_Last_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_4_Last_Name'].nunique()

34

In [374]:
df1['Principal_Investigator_4_Last_Name'].value_counts(dropna=False)

Principal_Investigator_4_Last_Name
NaN            1028378
wasserman           18
kline fath          11
lotfi               11
chapman             11
chowdhury            6
yao                  4
patel                3
resnick              3
steinberg            2
kambhampati          1
sathyan              1
yanamadala           1
courtright           1
braly                1
singh                1
sharman              1
nunley               1
baghdanian           1
williams             1
hu                   1
khalil               1
thertulien           1
varier               1
bae                  1
subbiah              1
montijo              1
thomas               1
andorsky             1
fanning              1
chase                1
christian            1
proffer              1
kwon                 1
berdeja              1
Name: count, dtype: int64

In [375]:
# Lower case conversion

msk = df1['Principal_Investigator_4_Name_Suffix'].notna()
df1.loc[msk, 'Principal_Investigator_4_Name_Suffix'] = df1.loc[msk, 'Principal_Investigator_4_Name_Suffix'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_4_Name_Suffix']= df1.loc[msk,'Principal_Investigator_4_Name_Suffix'].apply(lambda x: x.lower())
df1['Principal_Investigator_4_Name_Suffix'].nunique()

1

In [376]:
df1['Principal_Investigator_4_Name_Suffix'].value_counts(dropna=False)

Principal_Investigator_4_Name_Suffix
NaN    1028454
md          18
Name: count, dtype: int64

In [377]:
df1['Principal_Investigator_4_Covered_Recipient_Type'].value_counts(dropna=False)

Principal_Investigator_4_Covered_Recipient_Type
NaN                            1028378
Covered Recipient Physician         94
Name: count, dtype: int64

In [378]:
df1['Principal_Investigator_4_Business_Street_Address_Line1'].value_counts(dropna=False)

Principal_Investigator_4_Business_Street_Address_Line1
NaN                                            1028378
100 Reserve Rd                                      18
3333 BURNET AVE ML 5031                             11
3300 MAIN ST                                        11
3257 CAMINO DE LOS COCHES STE 305                   11
850 Straits Turnpike                                 6
8876 GULF FWY STE 215                                4
6050 Cattleridge Blvd                                3
VANDERBILT DEPARTMENT OF UROLOGIC SURGERY            3
1250 E MARSHALL ST                                   2
2316 E Meyer Blvd                                    1
35 Jolley Drive, Suite 203                           1
3625 E. Martin Luther King Jr. Blvd, Ste. 3          1
7777 Forest Ln Ste D400                              1
9800 Broadway Ext                                    1
2600 Tuscarawas St W Ste 420                         1
520 Country Club Pkwy                                1
1500 Line Ave                                        1
1500 San Pablo St Fl 2                               1
5050 N Clinton St                                    1
399 S Malpais Ln Ste 108                             1
26025 Lahser Rd                                      1
125 Queens Rd Ste 600                                1
315 Martin Luther King Jr Way 315-M3-I               1
2811 Wilshire Blvd                                   1
1515 HOLCOMBE BLVD #87                               1
403 Community Dr.                                    1
2208 S 17th St                                       1
7951 E Maplewood Ave Ste 300                         1
65 INTERNATIONAL DR                                  1
200 UCLA MEDICAL PLZ STE 220                         1
8915 W GOLF RD                                       1
600 Gresham Dr.                                      1
2001 Randolph Rd                                     1
250 25th Ave N Ste 412                               1
Name: count, dtype: int64

In [379]:
df1['Principal_Investigator_4_Business_Street_Address_Line2'].value_counts(dropna=False)

Principal_Investigator_4_Business_Street_Address_Line2
NaN                            1028463
--                                   3
A-1302 MEDICAL CENTER NORTH          3
DEPARTMENT OF PSYCHIATRY             2
Suite 204                            1
Name: count, dtype: int64

In [380]:
# Lower case conversion

msk = df1['Principal_Investigator_4_City'].notna()
df1.loc[msk, 'Principal_Investigator_4_City'] = df1.loc[msk, 'Principal_Investigator_4_City'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_4_City']= df1.loc[msk,'Principal_Investigator_4_City'].apply(lambda x: x.lower())
df1['Principal_Investigator_4_City'].nunique()

30

In [381]:
df1['Principal_Investigator_4_City'].value_counts(dropna=False)

Principal_Investigator_4_City
NaN                  1028378
danbury                   18
carlsbad                  11
cincinnati                11
springfield               11
middlebury                 6
houston                    5
nashville                  4
sarasota                   3
los angeles                2
richmond                   2
charlotte                  2
oklahoma city              1
fort wayne                 1
dallas                     1
bloomfield                 1
lynwood                    1
canton                     1
eugene                     1
santa monica               1
kansas city                1
southfield                 1
flagstaff                  1
tacoma                     1
jupiter                    1
wilmington                 1
greenwood village          1
greenville                 1
niles                      1
norfolk                    1
shreveport                 1
Name: count, dtype: int64

In [382]:
df1['Principal_Investigator_4_State'].value_counts(dropna=False)

Principal_Investigator_4_State
NaN    1028378
CT          25
CA          15
OH          12
MA          11
TX           6
TN           4
FL           4
NC           3
VA           3
MI           1
OK           1
OR           1
IN           1
MO           1
CO           1
AZ           1
WA           1
SC           1
IL           1
LA           1
Name: count, dtype: int64

In [383]:
df1['Principal_Investigator_4_Zip_Code'].value_counts(dropna=False)

Principal_Investigator_4_Zip_Code
NaN           1028378
06810              18
45229-3026         11
01107              11
92009-8974         11
06762               6
77017-6550          4
34232               3
37232-0001          3
23298-5051          2
64132               1
06002               1
90262               1
75230               1
73114               1
44708               1
97401               1
71101               1
90033               1
46825               1
86001               1
48033               1
28204               1
98405               1
90403               1
77030               1
33458               1
28401               1
80111               1
29615               1
90095               1
60714               1
23507               1
28207               1
37203               1
Name: count, dtype: int64

In [384]:
df1['Principal_Investigator_4_Country'].value_counts(dropna=False)

Principal_Investigator_4_Country
NaN              1028378
United States         94
Name: count, dtype: int64

In [385]:
df1['Principal_Investigator_4_Province'].value_counts(dropna=False)

Principal_Investigator_4_Province
NaN    1028472
Name: count, dtype: int64

In [386]:
df1['Principal_Investigator_4_Postal_Code'].value_counts(dropna=False)

Principal_Investigator_4_Postal_Code
NaN    1028472
Name: count, dtype: int64

In [387]:
# reverify

df1[['Principal_Investigator_4_Covered_Recipient_Type','Principal_Investigator_4_Profile_ID',
    'Principal_Investigator_4_NPI', 'Principal_Investigator_4_First_Name',
    'Principal_Investigator_4_Middle_Name', 'Principal_Investigator_4_Last_Name',
    'Principal_Investigator_4_Name_Suffix', 'Principal_Investigator_4_Business_Street_Address_Line1',
    'Principal_Investigator_4_Business_Street_Address_Line2', 'Principal_Investigator_4_City',
    'Principal_Investigator_4_State','Principal_Investigator_4_Zip_Code',
    'Principal_Investigator_4_Country','Principal_Investigator_4_Province',
     'Principal_Investigator_4_Postal_Code']].describe(include=object)

,Principal_Investigator_4_Covered_Recipient_Type,Principal_Investigator_4_Profile_ID,Principal_Investigator_4_NPI,Principal_Investigator_4_First_Name,Principal_Investigator_4_Middle_Name,Principal_Investigator_4_Last_Name,Principal_Investigator_4_Name_Suffix,Principal_Investigator_4_Business_Street_Address_Line1,Principal_Investigator_4_Business_Street_Address_Line2,Principal_Investigator_4_City,Principal_Investigator_4_State,Principal_Investigator_4_Zip_Code,Principal_Investigator_4_Country
count,94,94.0,9.400000e+01,94,34,94,18,94,9,94,94,94,94
unique,1,34.0,3.400000e+01,33,5,34,1,34,4,30,20,34,1
top,Covered Recipient Physician,6611.0,1.154358e+09,hal,s,wasserman,md,100 Reserve Rd,--,danbury,CT,06810,United States
freq,94,18.0,1.800000e+01,18,30,18,18,18,3,18,25,18,94

In [388]:
df1[['Principal_Investigator_4_Primary_Type_1',
     'Principal_Investigator_4_Primary_Type_2', 'Principal_Investigator_4_Primary_Type_3',
     'Principal_Investigator_4_Primary_Type_4', 'Principal_Investigator_4_Primary_Type_5',
     'Principal_Investigator_4_Primary_Type_3']].describe(include=object)

       Principal_Investigator_4_Primary_Type_1
count                                       94
unique                                       2
top                             Medical Doctor
freq                                        91

In [389]:
df1[['Principal_Investigator_4_Primary_Type_1',
     'Principal_Investigator_4_Primary_Type_2', 'Principal_Investigator_4_Primary_Type_3',
     'Principal_Investigator_4_Primary_Type_4', 'Principal_Investigator_4_Primary_Type_5',
     'Principal_Investigator_4_Primary_Type_6']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Principal_Investigator_4_Primary_Type_1  94 non-null     object
 1   Principal_Investigator_4_Primary_Type_2  0 non-null      float64
 2   Principal_Investigator_4_Primary_Type_3  0 non-null      float64
 3   Principal_Investigator_4_Primary_Type_4  0 non-null      float64
 4   Principal_Investigator_4_Primary_Type_5  0 non-null      float64
 5   Principal_Investigator_4_Primary_Type_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [390]:
df1[['Principal_Investigator_4_Primary_Type_1']].value_counts(dropna=False)

Principal_Investigator_4_Primary_Type_1
NaN                                        1028378
Medical Doctor                                  91
Doctor of Osteopathy                             3
Name: count, dtype: int64

In [391]:
df1[['Principal_Investigator_4_Specialty_1', 'Principal_Investigator_4_Specialty_2', 
     'Principal_Investigator_4_Specialty_3', 'Principal_Investigator_4_Specialty_4',
     'Principal_Investigator_4_Specialty_5', 'Principal_Investigator_4_Specialty_6',
    ]].describe(include=object)

                     Principal_Investigator_4_Specialty_1
count                                                  94
unique                                                 18
top     Allopathic & Osteopathic Physicians|Internal M...
freq                                                   29

In [392]:
df1[['Principal_Investigator_4_Specialty_1', 'Principal_Investigator_4_Specialty_2', 
     'Principal_Investigator_4_Specialty_3', 'Principal_Investigator_4_Specialty_4',
     'Principal_Investigator_4_Specialty_5', 'Principal_Investigator_4_Specialty_6',
    ]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Principal_Investigator_4_Specialty_1  94 non-null     object
 1   Principal_Investigator_4_Specialty_2  0 non-null      float64
 2   Principal_Investigator_4_Specialty_3  0 non-null      float64
 3   Principal_Investigator_4_Specialty_4  0 non-null      float64
 4   Principal_Investigator_4_Specialty_5  0 non-null      float64
 5   Principal_Investigator_4_Specialty_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [393]:
df1[['Principal_Investigator_4_Specialty_1']].value_counts(dropna=False)

Principal_Investigator_4_Specialty_1
NaN                                                                                         1028378
Allopathic & Osteopathic Physicians|Internal Medicine|Interventional Cardiology                  29
Allopathic & Osteopathic Physicians|Radiology|Pediatric Radiology                                11
Allopathic & Osteopathic Physicians|General Practice                                             11
Allopathic & Osteopathic Physicians|Orthopaedic Surgery                                           7
Allopathic & Osteopathic Physicians|Internal Medicine|Hematology & Oncology                       6
Allopathic & Osteopathic Physicians|Internal Medicine|Nephrology                                  6
Allopathic & Osteopathic Physicians|Internal Medicine                                             6
Allopathic & Osteopathic Physicians|Orthopaedic Surgery|Orthopaedic Surgery of the Spine          4
Allopathic & Osteopathic Physicians|Urology                                                       3
Allopathic & Osteopathic Physicians|Psychiatry & Neurology|Psychiatry                             2
Allopathic & Osteopathic Physicians|Obstetrics & Gynecology|Gynecologic Oncology                  2
Allopathic & Osteopathic Physicians|Internal Medicine|Medical Oncology                            1
Allopathic & Osteopathic Physicians|Internal Medicine|Rheumatology                                1
Allopathic & Osteopathic Physicians|Neurological Surgery                                          1
Allopathic & Osteopathic Physicians|Pediatrics|Pediatric Gastroenterology                         1
Allopathic & Osteopathic Physicians|Pediatrics|Pediatric Hematology-Oncology                      1
Allopathic & Osteopathic Physicians|Radiology|Diagnostic Radiology                                1
Allopathic & Osteopathic Physicians|Internal Medicine|Hematology                                  1
Name: count, dtype: int64

In [394]:
df1[['Principal_Investigator_4_License_State_code1', 'Principal_Investigator_4_License_State_code2',
    'Principal_Investigator_4_License_State_code3', 'Principal_Investigator_4_License_State_code4',
    'Principal_Investigator_4_License_State_code5']].describe(include=object)

,Principal_Investigator_4_License_State_code1,Principal_Investigator_4_License_State_code2,Principal_Investigator_4_License_State_code3
count,94,16,11
unique,20,3,1
top,CT,OH,TN
freq,25,11,11

In [395]:
df1[['Principal_Investigator_4_License_State_code1', 'Principal_Investigator_4_License_State_code2',
    'Principal_Investigator_4_License_State_code3', 'Principal_Investigator_4_License_State_code4',
    'Principal_Investigator_4_License_State_code5']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 5 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Principal_Investigator_4_License_State_code1  94 non-null     object
 1   Principal_Investigator_4_License_State_code2  16 non-null     object
 2   Principal_Investigator_4_License_State_code3  11 non-null     object
 3   Principal_Investigator_4_License_State_code4  0 non-null      float64
 4   Principal_Investigator_4_License_State_code5  0 non-null      float64
dtypes: float64(2), object(3)
memory usage: 39.2+ MB

In [396]:
df1[['Principal_Investigator_4_License_State_code1', 'Principal_Investigator_4_License_State_code2',
    'Principal_Investigator_4_License_State_code3']].describe()

,Principal_Investigator_4_License_State_code1,Principal_Investigator_4_License_State_code2,Principal_Investigator_4_License_State_code3
count,94,16,11
unique,20,3,1
top,CT,OH,TN
freq,25,11,11

In [397]:
df1[['Principal_Investigator_5_Covered_Recipient_Type','Principal_Investigator_5_Profile_ID',
    'Principal_Investigator_5_NPI', 'Principal_Investigator_5_First_Name',
    'Principal_Investigator_5_Middle_Name', 'Principal_Investigator_5_Last_Name',
    'Principal_Investigator_5_Name_Suffix', 'Principal_Investigator_5_Business_Street_Address_Line1',
     'Principal_Investigator_5_City','Principal_Investigator_5_Business_Street_Address_Line2',
    'Principal_Investigator_5_State','Principal_Investigator_5_Zip_Code',
    'Principal_Investigator_5_Country','Principal_Investigator_5_Province',
     'Principal_Investigator_5_Postal_Code']].describe(include=object)

,Principal_Investigator_5_Covered_Recipient_Type,Principal_Investigator_5_First_Name,Principal_Investigator_5_Middle_Name,Principal_Investigator_5_Last_Name,Principal_Investigator_5_Name_Suffix,Principal_Investigator_5_Business_Street_Address_Line1,Principal_Investigator_5_City,Principal_Investigator_5_Business_Street_Address_Line2,Principal_Investigator_5_State,Principal_Investigator_5_Country
count,43,43,4,43,18,43,43,2,43,43
unique,1,21,4,21,1,20,20,1,14,1
top,Covered Recipient Physician,MICHAEL,Brian,BUTLER,MD,150 Rands Ave,Huntsville,--,AL,United States
freq,43,18,1,18,18,18,18,2,18,43

In [398]:
df1[['Principal_Investigator_5_Covered_Recipient_Type','Principal_Investigator_5_Profile_ID',
    'Principal_Investigator_5_NPI', 'Principal_Investigator_5_First_Name',
    'Principal_Investigator_5_Middle_Name', 'Principal_Investigator_5_Last_Name',
    'Principal_Investigator_5_Name_Suffix', 'Principal_Investigator_5_Business_Street_Address_Line1',
     'Principal_Investigator_5_City','Principal_Investigator_5_Business_Street_Address_Line2',
    'Principal_Investigator_5_State','Principal_Investigator_5_Zip_Code',
    'Principal_Investigator_5_Country','Principal_Investigator_5_Province',
     'Principal_Investigator_5_Postal_Code']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 15 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Principal_Investigator_5_Covered_Recipient_Type         43 non-null     object
 1   Principal_Investigator_5_Profile_ID                     43 non-null     float64
 2   Principal_Investigator_5_NPI                            43 non-null     float64
 3   Principal_Investigator_5_First_Name                     43 non-null     object
 4   Principal_Investigator_5_Middle_Name                    4 non-null      object
 5   Principal_Investigator_5_Last_Name                      43 non-null     object
 6   Principal_Investigator_5_Name_Suffix                    18 non-null     object
 7   Principal_Investigator_5_Business_Street_Address_Line1  43 non-null     object
 8   Principal_Investigator_5_City                           43 non-null     object
 9   Principal_Investigator_5_Business_Street_Address_Line2  2 non-null      object
 10  Principal_Investigator_5_State                          43 non-null     object
 11  Principal_Investigator_5_Zip_Code                       43 non-null     float64
 12  Principal_Investigator_5_Country                        43 non-null     object
 13  Principal_Investigator_5_Province                       0 non-null      float64
 14  Principal_Investigator_5_Postal_Code                    0 non-null      float64
dtypes: float64(5), object(10)
memory usage: 117.7+ MB

In [399]:
df1['Principal_Investigator_5_Zip_Code']=df1['Principal_Investigator_5_Zip_Code'].astype(object)

In [400]:
df1['Principal_Investigator_5_Zip_Code'].value_counts(dropna=False)

Principal_Investigator_5_Zip_Code
NaN        1028429
35801.0         18
23502.0          6
29615.0          3
33908.0          1
42003.0          1
22903.0          1
97401.0          1
92123.0          1
91206.0          1
77096.0          1
20191.0          1
30677.0          1
48201.0          1
46032.0          1
33445.0          1
15213.0          1
85054.0          1
28207.0          1
75001.0          1
Name: count, dtype: int64

In [401]:
df1['Principal_Investigator_5_Covered_Recipient_Type'].value_counts(dropna=False)

Principal_Investigator_5_Covered_Recipient_Type
NaN                            1028429
Covered Recipient Physician         43
Name: count, dtype: int64

In [402]:
df1['Principal_Investigator_5_Profile_ID']=df1['Principal_Investigator_5_Profile_ID'].astype(object)

In [403]:
df1['Principal_Investigator_5_Profile_ID'].value_counts(dropna=False)

Principal_Investigator_5_Profile_ID
NaN          1028429
883425.0          18
207688.0           6
1199740.0          1
838313.0           1
30229.0            1
1154984.0          1
58716.0            1
894217.0           1
142203.0           1
20180.0            1
252870.0           1
1353885.0          1
707299.0           1
345601.0           1
254295.0           1
2782379.0          1
343154.0           1
772168.0           1
203751.0           1
227297.0           1
344105.0           1
Name: count, dtype: int64

In [404]:
df1['Principal_Investigator_5_NPI']=df1['Principal_Investigator_5_NPI'].astype(object)

In [405]:
df1['Principal_Investigator_5_NPI'].describe()

count     4.300000e+01
unique    2.100000e+01
top       1.306059e+09
freq      1.800000e+01
Name: Principal_Investigator_5_NPI, dtype: float64

In [406]:
df1['Principal_Investigator_5_NPI'].value_counts(dropna=False)

Principal_Investigator_5_NPI
NaN             1028429
1306058557.0         18
1598722803.0          6
1386865426.0          1
1700014222.0          1
1659596179.0          1
1801868286.0          1
1306860465.0          1
1659536993.0          1
1134125818.0          1
1447233986.0          1
1568593390.0          1
1740669928.0          1
1063641637.0          1
1619072956.0          1
1598781478.0          1
1811338627.0          1
1568664480.0          1
1356674527.0          1
1487781175.0          1
1023090826.0          1
1598722654.0          1
Name: count, dtype: int64

In [407]:
# Lower case conversion

msk = df1['Principal_Investigator_5_First_Name'].notna()
df1.loc[msk, 'Principal_Investigator_5_First_Name'] = df1.loc[msk, 'Principal_Investigator_5_First_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_5_First_Name']= df1.loc[msk,'Principal_Investigator_5_First_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_5_First_Name'].nunique()

21

In [408]:
df1['Principal_Investigator_5_First_Name'].value_counts(dropna=False)

Principal_Investigator_5_First_Name
NaN            1028429
michael             18
kiranjit             6
kenneth              1
chun po              1
jeff                 1
joseph               1
raffi                1
amy                  1
saeeda               1
james                1
christopher          1
charles              1
kristen              1
rick                 1
david                1
thomas               1
suzanne              1
elizabeth            1
mahesh               1
eric                 1
andrew               1
Name: count, dtype: int64

In [409]:
# Lower case conversion

msk = df1['Principal_Investigator_5_Middle_Name'].notna()
df1.loc[msk, 'Principal_Investigator_5_Middle_Name'] = df1.loc[msk, 'Principal_Investigator_5_Middle_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_5_Middle_Name']= df1.loc[msk,'Principal_Investigator_5_Middle_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_5_Middle_Name'].nunique()

4

In [410]:
df1['Principal_Investigator_5_Middle_Name'].value_counts(dropna=False)

Principal_Investigator_5_Middle_Name
NaN         1028468
brian             1
heritage          1
d.                1
b.                1
Name: count, dtype: int64

In [411]:
# Lower case conversion

msk = df1['Principal_Investigator_5_Last_Name'].notna()
df1.loc[msk, 'Principal_Investigator_5_Last_Name'] = df1.loc[msk, 'Principal_Investigator_5_Last_Name'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_5_Last_Name']= df1.loc[msk,'Principal_Investigator_5_Last_Name'].apply(lambda x: x.lower())
df1['Principal_Investigator_5_Last_Name'].nunique()

21

In [412]:
df1['Principal_Investigator_5_Last_Name'].value_counts(dropna=False)

Principal_Investigator_5_Last_Name
NaN          1028429
butler            18
dhillon            6
strenge            1
yen                1
sharman            1
hebreo             1
minasian           1
chen               1
chowdhury          1
reeves             1
good               1
bodine             1
cares              1
sasso              1
buchalter          1
buell              1
fanning            1
cull               1
seetharam          1
laxer              1
park               1
Name: count, dtype: int64

In [413]:
# Lower case conversion

msk = df1['Principal_Investigator_5_Name_Suffix'].notna()
df1.loc[msk, 'Principal_Investigator_5_Name_Suffix'] = df1.loc[msk, 'Principal_Investigator_5_Name_Suffix'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_5_Name_Suffix']= df1.loc[msk,'Principal_Investigator_5_Name_Suffix'].apply(lambda x: x.lower())
df1['Principal_Investigator_5_Name_Suffix'].nunique()

1

In [414]:
df1['Principal_Investigator_5_Name_Suffix'].value_counts(dropna=False)

Principal_Investigator_5_Name_Suffix
NaN    1028454
md          18
Name: count, dtype: int64

In [415]:
df1['Principal_Investigator_5_Business_Street_Address_Line1'].value_counts(dropna=False)

Principal_Investigator_5_Business_Street_Address_Line1
NaN                               1028429
150 Rands Ave                          18
962 Norfolk Square                      6
65 International Dr                     2
15681 New Hampshire Ct                  1
2605 Kentucky Ave                       1
1300 Jefferson Park Ave                 1
520 Country Club Pkwy                   1
9610 Granite Ridge Drive                1
1505 Wilson Terrace, Suite 155          1
560 Meyerland Plaza Mall                1
1460 Resurgence Dr                      1
11800 Sunrise Valley Dr                 1
3901 Beaubien St                        1
13225 N Meridian St                     1
4800 Linton Blvd                        1
200 Lothrop St                          1
65 INTERNATIONAL DR                     1
5777 E MAYO BLVD                        1
2001 Randolph Rd                        1
17051 Dallas Pkwy                       1
Name: count, dtype: int64

In [416]:
# Lower case conversion

msk = df1['Principal_Investigator_5_City'].notna()
df1.loc[msk, 'Principal_Investigator_5_City'] = df1.loc[msk, 'Principal_Investigator_5_City'].astype(str)
# Converting all names to lower first to verify.
df1.loc[msk, 'Principal_Investigator_5_City']= df1.loc[msk,'Principal_Investigator_5_City'].apply(lambda x: x.lower())
df1['Principal_Investigator_5_City'].nunique()

19

In [417]:
df1['Principal_Investigator_5_City'].value_counts(dropna=False)

Principal_Investigator_5_City
NaN                1028429
huntsville              18
norfolk                  6
greenville               3
fort myers               1
paducah                  1
charlottesville          1
eugene                   1
san diego                1
glendale                 1
houston                  1
reston                   1
watkinsville             1
detroit                  1
carmel                   1
delray beach             1
pittsburgh               1
phoenix                  1
charlotte                1
addison                  1
Name: count, dtype: int64

In [418]:
df1['Principal_Investigator_5_State'].value_counts(dropna=False)

Principal_Investigator_5_State
NaN    1028429
AL          18
VA           8
SC           3
FL           2
TX           2
CA           2
NC           1
AZ           1
PA           1
IN           1
MI           1
GA           1
OR           1
KY           1
Name: count, dtype: int64

In [419]:
df1['Principal_Investigator_5_Zip_Code'].value_counts(dropna=False)

Principal_Investigator_5_Zip_Code
NaN        1028429
35801.0         18
23502.0          6
29615.0          3
33908.0          1
42003.0          1
22903.0          1
97401.0          1
92123.0          1
91206.0          1
77096.0          1
20191.0          1
30677.0          1
48201.0          1
46032.0          1
33445.0          1
15213.0          1
85054.0          1
28207.0          1
75001.0          1
Name: count, dtype: int64

In [420]:
df1['Principal_Investigator_5_Country'].value_counts(dropna=False)

Principal_Investigator_5_Country
NaN              1028429
United States         43
Name: count, dtype: int64

In [421]:
# reverify after lower case conv

df1[['Principal_Investigator_5_Covered_Recipient_Type','Principal_Investigator_5_Profile_ID',
    'Principal_Investigator_5_NPI', 'Principal_Investigator_5_First_Name',
    'Principal_Investigator_5_Middle_Name', 'Principal_Investigator_5_Last_Name',
    'Principal_Investigator_5_Name_Suffix', 'Principal_Investigator_5_Business_Street_Address_Line1',
     'Principal_Investigator_5_City','Principal_Investigator_5_Business_Street_Address_Line2',
    'Principal_Investigator_5_State','Principal_Investigator_5_Zip_Code',
    'Principal_Investigator_5_Country','Principal_Investigator_5_Province',
     'Principal_Investigator_5_Postal_Code']].describe(include=object)

,Principal_Investigator_5_Covered_Recipient_Type,Principal_Investigator_5_Profile_ID,Principal_Investigator_5_NPI,Principal_Investigator_5_First_Name,Principal_Investigator_5_Middle_Name,Principal_Investigator_5_Last_Name,Principal_Investigator_5_Name_Suffix,Principal_Investigator_5_Business_Street_Address_Line1,Principal_Investigator_5_City,Principal_Investigator_5_Business_Street_Address_Line2,Principal_Investigator_5_State,Principal_Investigator_5_Zip_Code,Principal_Investigator_5_Country
count,43,43.0,4.300000e+01,43,4,43,18,43,43,2,43,43.0,43
unique,1,21.0,2.100000e+01,21,4,21,1,20,19,1,14,19.0,1
top,Covered Recipient Physician,883425.0,1.306059e+09,michael,brian,butler,md,150 Rands Ave,huntsville,--,AL,35801.0,United States
freq,43,18.0,1.800000e+01,18,1,18,18,18,18,2,18,18.0,43

In [422]:
df1[['Principal_Investigator_5_Primary_Type_1',
     'Principal_Investigator_5_Primary_Type_2', 'Principal_Investigator_5_Primary_Type_3',
     'Principal_Investigator_5_Primary_Type_4', 'Principal_Investigator_5_Primary_Type_5',
     'Principal_Investigator_5_Primary_Type_6']].describe(include=object)

       Principal_Investigator_5_Primary_Type_1
count                                       43
unique                                       2
top                             Medical Doctor
freq                                        41

In [423]:
df1[['Principal_Investigator_5_Primary_Type_1',
     'Principal_Investigator_5_Primary_Type_2', 'Principal_Investigator_5_Primary_Type_3',
     'Principal_Investigator_5_Primary_Type_4', 'Principal_Investigator_5_Primary_Type_5',
     'Principal_Investigator_5_Primary_Type_6']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Principal_Investigator_5_Primary_Type_1  43 non-null     object
 1   Principal_Investigator_5_Primary_Type_2  0 non-null      float64
 2   Principal_Investigator_5_Primary_Type_3  0 non-null      float64
 3   Principal_Investigator_5_Primary_Type_4  0 non-null      float64
 4   Principal_Investigator_5_Primary_Type_5  0 non-null      float64
 5   Principal_Investigator_5_Primary_Type_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [424]:
df1['Principal_Investigator_5_Primary_Type_1'].value_counts(dropna=False)

Principal_Investigator_5_Primary_Type_1
NaN                     1028429
Medical Doctor               41
Doctor of Osteopathy          2
Name: count, dtype: int64

In [425]:

df1[['Principal_Investigator_5_Specialty_1', 'Principal_Investigator_5_Specialty_2', 
     'Principal_Investigator_5_Specialty_3', 'Principal_Investigator_5_Specialty_4',
     'Principal_Investigator_5_Specialty_5', 'Principal_Investigator_5_Specialty_6',
    ]].describe(include=object)

                     Principal_Investigator_5_Specialty_1
count                                                  43
unique                                                 10
top     Allopathic & Osteopathic Physicians|Internal M...
freq                                                   18

In [426]:

df1[['Principal_Investigator_5_Specialty_1', 'Principal_Investigator_5_Specialty_2', 
     'Principal_Investigator_5_Specialty_3', 'Principal_Investigator_5_Specialty_4',
     'Principal_Investigator_5_Specialty_5', 'Principal_Investigator_5_Specialty_6',
    ]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 6 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Principal_Investigator_5_Specialty_1  43 non-null     object
 1   Principal_Investigator_5_Specialty_2  0 non-null      float64
 2   Principal_Investigator_5_Specialty_3  0 non-null      float64
 3   Principal_Investigator_5_Specialty_4  0 non-null      float64
 4   Principal_Investigator_5_Specialty_5  0 non-null      float64
 5   Principal_Investigator_5_Specialty_6  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 47.1+ MB

In [427]:
df1[['Principal_Investigator_5_Specialty_1']].value_counts(dropna=False)

Principal_Investigator_5_Specialty_1
NaN                                                                                         1028429
Allopathic & Osteopathic Physicians|Internal Medicine|Interventional Cardiology                  18
Allopathic & Osteopathic Physicians|Internal Medicine|Nephrology                                  8
Allopathic & Osteopathic Physicians|Internal Medicine|Hematology & Oncology                       5
Allopathic & Osteopathic Physicians|Orthopaedic Surgery                                           3
Allopathic & Osteopathic Physicians|Orthopaedic Surgery|Orthopaedic Surgery of the Spine          3
Allopathic & Osteopathic Physicians|Neurological Surgery                                          2
Allopathic & Osteopathic Physicians|Family Medicine                                               1
Allopathic & Osteopathic Physicians|Internal Medicine|Hematology                                  1
Allopathic & Osteopathic Physicians|Internal Medicine|Medical Oncology                            1
Allopathic & Osteopathic Physicians|Pediatrics|Pediatric Gastroenterology                         1
Name: count, dtype: int64

In [428]:
df1[['Principal_Investigator_5_License_State_code1', 'Principal_Investigator_5_License_State_code2',
    'Principal_Investigator_5_License_State_code3', 'Principal_Investigator_5_License_State_code4',
    'Principal_Investigator_5_License_State_code5']].describe(include=object)

       Principal_Investigator_5_License_State_code1
count                                            43
unique                                           13
top                                              AL
freq                                             18

In [429]:
df1[['Principal_Investigator_5_License_State_code1', 'Principal_Investigator_5_License_State_code2',
    'Principal_Investigator_5_License_State_code3', 'Principal_Investigator_5_License_State_code4',
    'Principal_Investigator_5_License_State_code5']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028472 entries, 0 to 1028471
Data columns (total 5 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Principal_Investigator_5_License_State_code1  43 non-null     object
 1   Principal_Investigator_5_License_State_code2  0 non-null      float64
 2   Principal_Investigator_5_License_State_code3  0 non-null      float64
 3   Principal_Investigator_5_License_State_code4  0 non-null      float64
 4   Principal_Investigator_5_License_State_code5  0 non-null      float64
dtypes: float64(4), object(1)
memory usage: 39.2+ MB

In [430]:
df1[['Principal_Investigator_5_License_State_code1']].value_counts(dropna=False)

Principal_Investigator_5_License_State_code1
NaN                                             1028429
AL                                                   18
VA                                                    7
CA                                                    3
SC                                                    3
FL                                                    2
NC                                                    2
TX                                                    2
AZ                                                    1
GA                                                    1
IL                                                    1
IN                                                    1
MI                                                    1
MO                                                    1
Name: count, dtype: int64

Creating final dataset

In [431]:
df1=df1.drop(columns=['Change_Type','Recipient_Province',
                      'Recipient_Postal_Code', 'Covered_Recipient_Primary_Type_2',
                      'Covered_Recipient_Primary_Type_3', 'Covered_Recipient_Primary_Type_4',
                      'Covered_Recipient_Primary_Type_5','Covered_Recipient_Primary_Type_6',
                      'Covered_Recipient_Specialty_2', 'Covered_Recipient_Specialty_3',
                      'Covered_Recipient_Specialty_4','Covered_Recipient_Specialty_5',
                      'Covered_Recipient_Specialty_6','Principal_Investigator_1_Province',
                      'Principal_Investigator_1_Postal_Code', 'Principal_Investigator_1_Primary_Type_2',
                      'Principal_Investigator_1_Primary_Type_3','Principal_Investigator_1_Primary_Type_4',
                      'Principal_Investigator_1_Primary_Type_5','Principal_Investigator_1_Primary_Type_6',
                      'Principal_Investigator_1_Specialty_2','Principal_Investigator_1_Specialty_3',
                      'Principal_Investigator_1_Specialty_4','Principal_Investigator_1_Specialty_5',
                      'Principal_Investigator_1_Specialty_6','Principal_Investigator_2_Province',
                      'Principal_Investigator_2_Postal_Code','Principal_Investigator_2_Primary_Type_2',
                      'Principal_Investigator_2_Primary_Type_3','Principal_Investigator_2_Primary_Type_4',
                      'Principal_Investigator_2_Primary_Type_5','Principal_Investigator_2_Primary_Type_6',
                      'Principal_Investigator_2_Specialty_2','Principal_Investigator_2_Specialty_3',
                      'Principal_Investigator_2_Specialty_4','Principal_Investigator_2_Specialty_5',
                      'Principal_Investigator_2_Specialty_6','Principal_Investigator_2_License_State_code5',
                      'Principal_Investigator_3_Name_Suffix','Principal_Investigator_3_Province',
                      'Principal_Investigator_3_Postal_Code', 'Principal_Investigator_3_Primary_Type_2',
                      'Principal_Investigator_3_Primary_Type_3','Principal_Investigator_3_Primary_Type_4',
                      'Principal_Investigator_3_Primary_Type_5','Principal_Investigator_3_Primary_Type_6',
                      'Principal_Investigator_3_Specialty_2','Principal_Investigator_3_Specialty_3',
                      'Principal_Investigator_3_Specialty_4','Principal_Investigator_3_Specialty_5',
                      'Principal_Investigator_3_Specialty_6','Principal_Investigator_3_License_State_code5',
                      'Principal_Investigator_4_Province','Principal_Investigator_4_Postal_Code',
                      'Principal_Investigator_4_Primary_Type_2','Principal_Investigator_4_Primary_Type_3',
                      'Principal_Investigator_4_Primary_Type_4','Principal_Investigator_4_Primary_Type_5',
                      'Principal_Investigator_4_Primary_Type_6', 'Principal_Investigator_4_Specialty_2',
                      'Principal_Investigator_4_Specialty_3','Principal_Investigator_4_Specialty_4',
                      'Principal_Investigator_4_Specialty_5','Principal_Investigator_4_Specialty_6',
                      'Principal_Investigator_4_License_State_code4','Principal_Investigator_4_License_State_code5',
                      'Principal_Investigator_5_Province','Principal_Investigator_5_Postal_Code',
                       'Principal_Investigator_5_Primary_Type_2','Principal_Investigator_5_Primary_Type_3',
                     'Principal_Investigator_5_Primary_Type_4','Principal_Investigator_5_Primary_Type_5',
                     'Principal_Investigator_5_Primary_Type_6', 'Principal_Investigator_5_Specialty_2',
                     'Principal_Investigator_5_Specialty_3','Principal_Investigator_5_Specialty_4',
                     'Principal_Investigator_5_Specialty_5','Principal_Investigator_5_Specialty_6',
                     'Principal_Investigator_5_License_State_code2', 'Principal_Investigator_5_License_State_code3',
                     'Principal_Investigator_5_License_State_code4','Principal_Investigator_5_License_State_code5',
                     'Delay_in_Publication_Indicator','Dispute_Status_for_Publication',
                     'Record_ID','Program_Year','Payment_Publication_Date', 'Teaching_Hospital_ID', 
                     'Teaching_Hospital_CCN', 
                     'Recipient_Primary_Business_Street_Address_Line1', 'Recipient_Primary_Business_Street_Address_Line2',
                     'Principal_Investigator_1_Business_Street_Address_Line1',
                     'Principal_Investigator_1_Business_Street_Address_Line2', 'Principal_Investigator_2_Middle_Name',
                     'Principal_Investigator_2_Business_Street_Address_Line1','Principal_Investigator_2_Business_Street_Address_Line2',
                     'Principal_Investigator_3_Business_Street_Address_Line1','Principal_Investigator_3_Business_Street_Address_Line2',
                     'Principal_Investigator_4_Business_Street_Address_Line1', 'Principal_Investigator_4_Business_Street_Address_Line2',
                     'Principal_Investigator_5_Business_Street_Address_Line1','Principal_Investigator_5_Business_Street_Address_Line2'],
                      axis=1)

In [432]:
df1_columns=df1.columns
l1=list(enumerate(df1_columns))
for i,j in l1:
    print(j)

Covered_Recipient_Type
Noncovered_Recipient_Entity_Name
Teaching_Hospital_Name
Covered_Recipient_Profile_ID
Covered_Recipient_NPI
Covered_Recipient_First_Name
Covered_Recipient_Middle_Name
Covered_Recipient_Last_Name
Covered_Recipient_Name_Suffix
Recipient_City
Recipient_State
Recipient_Zip_Code
Recipient_Country
Covered_Recipient_Primary_Type_1
Covered_Recipient_Specialty_1
Covered_Recipient_License_State_code1
Covered_Recipient_License_State_code2
Covered_Recipient_License_State_code3
Covered_Recipient_License_State_code4
Covered_Recipient_License_State_code5
Principal_Investigator_1_Covered_Recipient_Type
Principal_Investigator_1_Profile_ID
Principal_Investigator_1_NPI
Principal_Investigator_1_First_Name
Principal_Investigator_1_Middle_Name
Principal_Investigator_1_Last_Name
Principal_Investigator_1_Name_Suffix
Principal_Investigator_1_City
Principal_Investigator_1_State
Principal_Investigator_1_Zip_Code
Principal_Investigator_1_Country
Principal_Investigator_1_Primary_Type_1
Principal_Investigator_1_Specialty_1
Principal_Investigator_1_License_State_code1
Principal_Investigator_1_License_State_code2
Principal_Investigator_1_License_State_code3
Principal_Investigator_1_License_State_code4
Principal_Investigator_1_License_State_code5
Principal_Investigator_2_Covered_Recipient_Type
Principal_Investigator_2_Profile_ID
Principal_Investigator_2_NPI
Principal_Investigator_2_First_Name
Principal_Investigator_2_Last_Name
Principal_Investigator_2_Name_Suffix
Principal_Investigator_2_City
Principal_Investigator_2_State
Principal_Investigator_2_Zip_Code
Principal_Investigator_2_Country
Principal_Investigator_2_Primary_Type_1
Principal_Investigator_2_Specialty_1
Principal_Investigator_2_License_State_code1
Principal_Investigator_2_License_State_code2
Principal_Investigator_2_License_State_code3
Principal_Investigator_2_License_State_code4
Principal_Investigator_3_Covered_Recipient_Type
Principal_Investigator_3_Profile_ID
Principal_Investigator_3_NPI
Principal_Investigator_3_First_Name
Principal_Investigator_3_Middle_Name
Principal_Investigator_3_Last_Name
Principal_Investigator_3_City
Principal_Investigator_3_State
Principal_Investigator_3_Zip_Code
Principal_Investigator_3_Country
Principal_Investigator_3_Primary_Type_1
Principal_Investigator_3_Specialty_1
Principal_Investigator_3_License_State_code1
Principal_Investigator_3_License_State_code2
Principal_Investigator_3_License_State_code3
Principal_Investigator_3_License_State_code4
Principal_Investigator_4_Covered_Recipient_Type
Principal_Investigator_4_Profile_ID
Principal_Investigator_4_NPI
Principal_Investigator_4_First_Name
Principal_Investigator_4_Middle_Name
Principal_Investigator_4_Last_Name
Principal_Investigator_4_Name_Suffix
Principal_Investigator_4_City
Principal_Investigator_4_State
Principal_Investigator_4_Zip_Code
Principal_Investigator_4_Country
Principal_Investigator_4_Primary_Type_1
Principal_Investigator_4_Specialty_1
Principal_Investigator_4_License_State_code1
Principal_Investigator_4_License_State_code2
Principal_Investigator_4_License_State_code3
Principal_Investigator_5_Covered_Recipient_Type
Principal_Investigator_5_Profile_ID
Principal_Investigator_5_NPI
Principal_Investigator_5_First_Name
Principal_Investigator_5_Middle_Name
Principal_Investigator_5_Last_Name
Principal_Investigator_5_Name_Suffix
Principal_Investigator_5_City
Principal_Investigator_5_State
Principal_Investigator_5_Zip_Code
Principal_Investigator_5_Country
Principal_Investigator_5_Primary_Type_1
Principal_Investigator_5_Specialty_1
Principal_Investigator_5_License_State_code1
Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State
Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country
Related_Product_Indicator
Covered_or_Noncovered_Indicator_1
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1
Product_Category_or_Therapeutic_Area_1
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1
Associated_Drug_or_Biological_NDC_1
Associated_Device_or_Medical_Supply_PDI_1
Covered_or_Noncovered_Indicator_2
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2
Product_Category_or_Therapeutic_Area_2
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2
Associated_Drug_or_Biological_NDC_2
Associated_Device_or_Medical_Supply_PDI_2
Covered_or_Noncovered_Indicator_3
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3
Product_Category_or_Therapeutic_Area_3
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3
Associated_Drug_or_Biological_NDC_3
Associated_Device_or_Medical_Supply_PDI_3
Covered_or_Noncovered_Indicator_4
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4
Product_Category_or_Therapeutic_Area_4
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4
Associated_Drug_or_Biological_NDC_4
Associated_Device_or_Medical_Supply_PDI_4
Covered_or_Noncovered_Indicator_5
Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5
Product_Category_or_Therapeutic_Area_5
Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
Associated_Drug_or_Biological_NDC_5
Associated_Device_or_Medical_Supply_PDI_5
Total_Amount_of_Payment_USDollars
Date_of_Payment
Form_of_Payment_or_Transfer_of_Value
Expenditure_Category1
Expenditure_Category2
Expenditure_Category3
Expenditure_Category4
Expenditure_Category5
Expenditure_Category6
Preclinical_Research_Indicator
Name_of_Study
ClinicalTrials_Gov_Identifier
Research_Information_Link
Context_of_Research

In [433]:
# Dropping more columns
df1=df1.drop(['Covered_Recipient_NPI','Covered_Recipient_Middle_Name','Covered_Recipient_Name_Suffix',
                       'Recipient_City','Recipient_Zip_Code','Covered_Recipient_License_State_code1',
                       'Covered_Recipient_License_State_code2','Covered_Recipient_License_State_code3','Covered_Recipient_License_State_code4',
                       'Covered_Recipient_License_State_code5',  'Principal_Investigator_1_NPI', 'Principal_Investigator_1_Middle_Name','Principal_Investigator_1_Name_Suffix',
                       'Principal_Investigator_1_City','Principal_Investigator_1_Zip_Code','Principal_Investigator_1_License_State_code1',
                       'Principal_Investigator_1_License_State_code2','Principal_Investigator_1_License_State_code3','Principal_Investigator_1_License_State_code4',
                       'Principal_Investigator_1_License_State_code5','Principal_Investigator_2_NPI','Principal_Investigator_2_Name_Suffix',
                       'Principal_Investigator_2_City','Principal_Investigator_2_Zip_Code','Principal_Investigator_2_License_State_code1',
                       'Principal_Investigator_2_License_State_code2','Principal_Investigator_2_License_State_code3','Principal_Investigator_2_License_State_code4',
                       'Principal_Investigator_3_NPI','Principal_Investigator_3_Middle_Name','Principal_Investigator_3_City','Principal_Investigator_3_Zip_Code',
                       'Principal_Investigator_3_License_State_code1','Principal_Investigator_3_License_State_code2','Principal_Investigator_3_License_State_code3',
                       'Principal_Investigator_3_License_State_code4','Principal_Investigator_4_NPI','Principal_Investigator_4_Middle_Name',
                        'Principal_Investigator_4_Name_Suffix','Principal_Investigator_4_City','Principal_Investigator_4_Zip_Code',
                       'Principal_Investigator_4_License_State_code1', 'Principal_Investigator_4_License_State_code2','Principal_Investigator_4_License_State_code3',
                       'Principal_Investigator_5_NPI','Principal_Investigator_5_Middle_Name','Principal_Investigator_5_Name_Suffix','Principal_Investigator_5_City',
                       'Principal_Investigator_5_Zip_Code'], axis=1)

In [434]:
df1.columns

Index(['Covered_Recipient_Type', 'Noncovered_Recipient_Entity_Name',
       'Teaching_Hospital_Name', 'Covered_Recipient_Profile_ID',
       'Covered_Recipient_First_Name', 'Covered_Recipient_Last_Name',
       'Recipient_State', 'Recipient_Country',
       'Covered_Recipient_Primary_Type_1', 'Covered_Recipient_Specialty_1',
       ...
       'Expenditure_Category2', 'Expenditure_Category3',
       'Expenditure_Category4', 'Expenditure_Category5',
       'Expenditure_Category6', 'Preclinical_Research_Indicator',
       'Name_of_Study', 'ClinicalTrials_Gov_Identifier',
       'Research_Information_Link', 'Context_of_Research'],
      dtype='object', length=101)

## Extraction of unique names

In [435]:
## Extractin unique names from various name columns
df1['Covered_Recipient_First_Name'].nunique()

2201

In [436]:
## Extractin unique names from various name columns
Covered_recipient_unique_names=pd.Series(df1['Covered_Recipient_First_Name'].unique())

In [52]:
## Extractin unique names from various name columns
df1['Principal_Investigator_1_First_Name'].nunique(dropna=True)

7405

In [7]:
Principal_Investigator_1_unique_names=pd.Series(df1['Principal_Investigator_1_First_Name'].unique())

In [439]:
## Principal_Investigator_2_First_Name
## Extractin unique names from various name columns
df1['Principal_Investigator_2_First_Name'].nunique()

374

In [440]:
Principal_Investigator_2_unique_names=pd.Series(df1['Principal_Investigator_2_First_Name'].unique())

In [441]:
## Principal_Investigator_3_First_Name
## Extractin unique names from various name columns
df1['Principal_Investigator_3_First_Name'].nunique()

72

In [442]:
Principal_Investigator_3_unique_names=pd.Series(df1['Principal_Investigator_3_First_Name'].unique())

In [443]:
## Principal_Investigator_4_First_Name
## Extractin unique names from various name columns
df1['Principal_Investigator_4_First_Name'].nunique()

33

In [444]:
Principal_Investigator_4_unique_names=pd.Series(df1['Principal_Investigator_4_First_Name'].unique())

In [445]:
## Principal_Investigator_5_First_Name
## Extractin unique names from various name columns
df1['Principal_Investigator_5_First_Name'].nunique()

21

In [446]:
Principal_Investigator_5_unique_names=pd.Series(df1['Principal_Investigator_5_First_Name'].unique())

In [8]:
Principal_Investigator_1_unique_names.to_csv('Principal_Investigator_1_unique_names.csv')

In [447]:
## Data to run gender identification model

Principal_Investigator_5_unique_names.to_csv('/Users/malachaurasia/Downloads/Principal_Investigator_5_unique_names.csv')
Principal_Investigator_4_unique_names.to_csv('/Users/malachaurasia/Downloads/Principal_Investigator_4_unique_names.csv')
Principal_Investigator_3_unique_names.to_csv('/Users/malachaurasia/Downloads/Principal_Investigator_3_unique_names.csv')
Principal_Investigator_2_unique_names.to_csv('/Users/malachaurasia/Downloads/Principal_Investigator_2_unique_names.csv')
Principal_Investigator_1_unique_names.to_csv('/Users/malachaurasia/Downloads/Principal_Investigator_1_unique_names.csv')
Covered_recipient_unique_names.to_csv('/Users/malachaurasia/Downloads/Covered_recipient_unique_names.csv')

In [448]:
## Dropping more columns to just have unique names.
#df1=df1.drop(columns=['Covered_Recipient_Profile_ID', 'Principal_Investigator_1_Profile_ID',
#                      'Principal_Investigator_2_Profile_ID',
#                     'Principal_Investigator_3_Profile_ID',
#                     'Principal_Investigator_4_Profile_ID', 
#                     'Principal_Investigator_5_Profile_ID'], axis=1)

In [449]:
df1.columns

Index(['Covered_Recipient_Type', 'Noncovered_Recipient_Entity_Name',
       'Teaching_Hospital_Name', 'Covered_Recipient_Profile_ID',
       'Covered_Recipient_First_Name', 'Covered_Recipient_Last_Name',
       'Recipient_State', 'Recipient_Country',
       'Covered_Recipient_Primary_Type_1', 'Covered_Recipient_Specialty_1',
       ...
       'Expenditure_Category2', 'Expenditure_Category3',
       'Expenditure_Category4', 'Expenditure_Category5',
       'Expenditure_Category6', 'Preclinical_Research_Indicator',
       'Name_of_Study', 'ClinicalTrials_Gov_Identifier',
       'Research_Information_Link', 'Context_of_Research'],
      dtype='object', length=101)

In [454]:
# Adding gender column for 'Covered_Recipient_First_Name' predicted usin LLama

#names_mapping=pd.read_csv('/Users/malachaurasia/Desktop/XN-project/Globus-share-DooCrew-team/union_unique_names_with_gender_research.csv')
names_mapping=pd.read_csv('union_unique_names_with_gender_research.csv')

In [455]:
names_mapping.head()

,Unnamed: 0,Names,REA_GenderIdentification_v1_Confidence,REA_GenderIdentification_v1_Prediction,priyabrat/gender_Confidence,priyabrat/gender_Prediction,finetuned_llama3.1_Prediction
0,0,latasha,0.998951,F,0.999156,F,F
1,1,veena,0.997120,F,0.998177,F,F
2,2,timberly,0.593854,F,0.619893,F,F
3,3,reade,0.955686,M,0.969743,M,M
4,4,adrienne,0.995483,F,0.997683,F,F

In [456]:
# Finding mode in gender for all the three predictions.
# Stastically improves the outcomes

names_mapping['mode']= names_mapping[['REA_GenderIdentification_v1_Prediction','priyabrat/gender_Prediction','finetuned_llama3.1_Prediction']].mode(axis=1, numeric_only=False, dropna=True)

names_mapping['mode']

0       F
1       F
2       F
3       M
4       F
       ..
7720    M
7721    F
7722    M
7723    F
7724    M
Name: mode, Length: 7725, dtype: object

In [461]:
# Creating dictionary of names and gender mapping , using mode of all name predictions.
namesdict=names_mapping.set_index('Names')['mode'].to_dict()

In [462]:
# Verifying few values
df1['Covered_Recipient_First_Name'].head()

0       NaN
1       NaN
2    connie
3       NaN
4       NaN
Name: Covered_Recipient_First_Name, dtype: object

In [463]:
df1['Covered_Recipient_First_Name'][50:60]

50             NaN
51            atif
52             NaN
53              le
54    bhaktasharan
55             amy
56             NaN
57            mark
58             NaN
59             NaN
Name: Covered_Recipient_First_Name, dtype: object

In [464]:
# df1['Covered_Recipient_First_Name']

df1['Covered_Recipient_gender'] = df1['Covered_Recipient_First_Name'].map(namesdict)

In [465]:
# Verification of added column
df1[['Covered_Recipient_gender', 'Covered_Recipient_First_Name']].head()

  Covered_Recipient_gender Covered_Recipient_First_Name
0                      NaN                          NaN
1                      NaN                          NaN
2                        F                       connie
3                      NaN                          NaN
4                      NaN                          NaN

In [466]:
df1[['Covered_Recipient_gender', 'Covered_Recipient_First_Name']][50:60]

   Covered_Recipient_gender Covered_Recipient_First_Name
50                      NaN                          NaN
51                        M                         atif
52                      NaN                          NaN
53                        F                           le
54                        M                 bhaktasharan
55                        F                          amy
56                      NaN                          NaN
57                        M                         mark
58                      NaN                          NaN
59                      NaN                          NaN

In [467]:
# Getting genders for all principle investigators

df1['Principal_Investigator_5_gender'] = df1['Principal_Investigator_5_First_Name'].map(namesdict)
df1['Principal_Investigator_4_gender'] = df1['Principal_Investigator_4_First_Name'].map(namesdict)
df1['Principal_Investigator_3_gender'] = df1['Principal_Investigator_3_First_Name'].map(namesdict)
df1['Principal_Investigator_2_gender'] = df1['Principal_Investigator_2_First_Name'].map(namesdict)
df1['Principal_Investigator_1_gender'] = df1['Principal_Investigator_1_First_Name'].map(namesdict)

In [468]:
# Basic verification
df1[['Principal_Investigator_5_gender']].value_counts(dropna=False)

Principal_Investigator_5_gender
NaN                                1028429
M                                       38
F                                        5
Name: count, dtype: int64

In [469]:
df1[['Principal_Investigator_5_gender', 'Principal_Investigator_5_First_Name']].describe()

       Principal_Investigator_5_gender Principal_Investigator_5_First_Name
count                               43                                  43
unique                               2                                  21
top                                  M                             michael
freq                                38                                  18

In [470]:

df1[['Principal_Investigator_4_gender']].value_counts(dropna=False)

Principal_Investigator_4_gender
NaN                                1028378
M                                       74
F                                       20
Name: count, dtype: int64

In [471]:
df1[['Principal_Investigator_4_gender','Principal_Investigator_4_First_Name']].describe()

       Principal_Investigator_4_gender Principal_Investigator_4_First_Name
count                               94                                  94
unique                               2                                  33
top                                  M                                 hal
freq                                74                                  18

In [472]:
df1[['Principal_Investigator_3_gender']].value_counts(dropna=False)

Principal_Investigator_3_gender
NaN                                1028221
M                                      207
F                                       44
Name: count, dtype: int64

In [473]:
df1[['Principal_Investigator_3_gender','Principal_Investigator_3_First_Name']].describe()

       Principal_Investigator_3_gender Principal_Investigator_3_First_Name
count                              251                                 251
unique                               2                                  72
top                                  M                               david
freq                               207                                  34

In [474]:

df1[['Principal_Investigator_1_gender']].value_counts(dropna=False)

Principal_Investigator_1_gender
M                                  742993
F                                  254346
NaN                                 31133
Name: count, dtype: int64

In [475]:
df1[['Principal_Investigator_1_gender','Principal_Investigator_1_First_Name']].describe()

       Principal_Investigator_1_gender Principal_Investigator_1_First_Name
count                           997339                              997356
unique                               2                                7406
top                                  M                               david
freq                            742993                               26836

In [476]:
df1[['Principal_Investigator_2_gender']].value_counts(dropna=False)

Principal_Investigator_2_gender
NaN                                1026300
M                                     1748
F                                      424
Name: count, dtype: int64

In [477]:
df1[['Principal_Investigator_2_gender','Principal_Investigator_2_First_Name']].describe()

       Principal_Investigator_2_gender Principal_Investigator_2_First_Name
count                             2172                                2172
unique                               2                                 374
top                                  M                              sameer
freq                              1748                                 363

In [478]:
df1[['Covered_Recipient_gender']].value_counts(dropna=False)

Covered_Recipient_gender
NaN                         1002167
M                             18248
F                              8057
Name: count, dtype: int64

In [479]:
df1[['Covered_Recipient_gender', 'Covered_Recipient_First_Name']].describe()

       Covered_Recipient_gender Covered_Recipient_First_Name
count                     26305                        26305
unique                        2                         2201
top                           M                        david
freq                      18248                          783

In [480]:
# Saving the clean data for further analysis
df1.to_csv('Master_data_research_with_gender_clean-oct21.csv')
#df1.to_csv('/Users/malachaurasia/Desktop/XN-project/Globus-share-DooCrew-team/Dataset/research_gender_clean.csv')

## Remapping the names for Principal_Investigator_1_gender, as few were missing in first iteration

In [2]:
df1=pd.read_csv('Master_data_research_with_gender_clean-oct21.csv',index_col='Unnamed: 0', low_memory=False)

In [7]:
names_pi1=pd.read_csv('principal_Investigator_1_gender_3predictions.csv', index_col='Unnamed: 0')

In [8]:
names_pi1

,0,malcolm/REA_GenderIdentification_v1_Prediction,malcolm/REA_GenderIdentification_v1_Confidence,priyabrat/gender_Prediction,priyabrat/gender_Confidence,finetuned_llama3.1_Prediction
Unnamed: 0,,,,,,
0,alexandru,M,0.984735,M,0.989374,M
1,kristina,F,0.998976,F,0.999169,F
2,NaN,F,0.991524,F,0.996269,F
3,delaram,F,0.916133,F,0.953317,F
4,nowreen,F,0.991202,F,0.996462,F
...,...,...,...,...,...,...
7402,roneka,F,0.998352,F,0.998854,F
7403,rachit,M,0.855950,M,0.893891,M
7404,shoeb,M,0.985667,M,0.991372,M
7405,sharina,F,0.999252,F,0.999341,F
7406,luiz,M,0.977729,M,0.983108,M

In [9]:
names_pi1=names_pi1.drop(2,axis=0).reset_index()

In [10]:
names_pi1=names_pi1.dropna()
names_pi1

,Unnamed: 0,0,malcolm/REA_GenderIdentification_v1_Prediction,malcolm/REA_GenderIdentification_v1_Confidence,priyabrat/gender_Prediction,priyabrat/gender_Confidence,finetuned_llama3.1_Prediction
0,0,alexandru,M,0.984735,M,0.989374,M
1,1,kristina,F,0.998976,F,0.999169,F
2,3,delaram,F,0.916133,F,0.953317,F
3,4,nowreen,F,0.991202,F,0.996462,F
4,5,david,M,0.997462,M,0.997911,M
...,...,...,...,...,...,...,...
7401,7402,roneka,F,0.998352,F,0.998854,F
7402,7403,rachit,M,0.855950,M,0.893891,M
7403,7404,shoeb,M,0.985667,M,0.991372,M
7404,7405,sharina,F,0.999252,F,0.999341,F
7405,7406,luiz,M,0.977729,M,0.983108,M

In [11]:
# mapping
names_pi1['mode']= names_pi1[['malcolm/REA_GenderIdentification_v1_Prediction','priyabrat/gender_Prediction','finetuned_llama3.1_Prediction']].mode(axis=1, numeric_only=False, dropna=True)

names_pi1['mode']

0       M
1       F
2       F
3       F
4       M
       ..
7401    F
7402    M
7403    M
7404    F
7405    M
Name: mode, Length: 7405, dtype: object

In [12]:
# Creating dictionary of names and gender mapping , using mode of all name predictions.
namesdict_PI1=names_pi1.set_index('0')['mode'].to_dict()


df1['Principal_Investigator_1_gender'] = df1['Principal_Investigator_1_First_Name'].map(namesdict_PI1)

In [13]:
df1[['Principal_Investigator_1_First_Name', 'Principal_Investigator_1_gender']]

        Principal_Investigator_1_First_Name Principal_Investigator_1_gender
0                                 alexandru                               M
1                                  kristina                               F
2                                       NaN                             NaN
3                                   delaram                               F
4                                   nowreen                               F
...                                     ...                             ...
1028467                                aziz                               M
1028468                                juan                               M
1028469                                john                               M
1028470                              nashat                               F
1028471                                john                               M

[1028472 rows x 2 columns]

In [14]:
df1[df1['Principal_Investigator_1_First_Name'].isna()]['Principal_Investigator_1_gender']

2         NaN
5         NaN
12        NaN
21        NaN
26        NaN
         ...
790580    NaN
800334    NaN
828173    NaN
959760    NaN
988876    NaN
Name: Principal_Investigator_1_gender, Length: 31133, dtype: object

In [15]:
df1[['Principal_Investigator_1_First_Name','Principal_Investigator_1_gender']].describe()

       Principal_Investigator_1_First_Name Principal_Investigator_1_gender
count                               997339                          997339
unique                                7405                               2
top                                  david                               M
freq                                 26836                          743011

In [16]:
# Saving the clean data for further analysis
df1.to_csv('Master_data_research_with_gender_clean_11_Nov.csv')

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1028472 entries, 0 to 1028471
Columns: 107 entries, Covered_Recipient_Type to Principal_Investigator_1_gender
dtypes: float64(9), int64(1), object(97)
memory usage: 847.4+ MB

### Master data file created for future processing